//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIResponder.h"

#import "CrashlyticsDelegate.h"
#import "UIApplicationDelegate.h"

@class JDLBootstrap, JDLUIBootstrap, NSString, UIWindow;

@interface AppDelegate : UIResponder <CrashlyticsDelegate, UIApplicationDelegate>
{
    UIWindow *_window;
    JDLBootstrap *_bootstrap;
    JDLUIBootstrap *_uiBootstrap;
}

+ (void)initialize;
@property(retain, nonatomic) JDLUIBootstrap *uiBootstrap; // @synthesize uiBootstrap=_uiBootstrap;
@property(retain, nonatomic) JDLBootstrap *bootstrap; // @synthesize bootstrap=_bootstrap;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (_Bool)crashlyticsCanUseBackgroundSessions:(id)arg1;
- (void)crashlyticsDidDetectReportForLastExecution:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)application:(id)arg1 performActionForShortcutItem:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

