//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "APToastDelegate.h"

@class NSMutableArray, NSString;

@interface APToaster : NSObject <APToastDelegate>
{
    NSMutableArray *_toasts;
}

+ (void)setToasterAnimationDuration:(double)arg1;
+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableArray *toasts; // @synthesize toasts=_toasts;
- (void).cxx_destruct;
- (void)toastDidFinished:(id)arg1;
- (void)showNextToast;
- (void)hideToast:(id)arg1 animated:(_Bool)arg2;
- (void)showToast:(id)arg1;
- (void)ejectToastWithID:(long long)arg1 animated:(_Bool)arg2;
- (long long)makeToast:(id)arg1 parentView:(id)arg2 duration:(double)arg3 tapToComplete:(_Bool)arg4 completion:(CDUnknownBlockType)arg5;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

