//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BLKFlexibleHeightBarBehaviorDefiner.h"

@interface FacebookStyleBarBehaviorDefiner : BLKFlexibleHeightBarBehaviorDefiner
{
    double _thresholdFromTop;
    double _thresholdNegativeDirection;
    double _thresholdPositiveDirection;
    double _previousYOffset;
    double _previousProgress;
}

@property(nonatomic) double previousProgress; // @synthesize previousProgress=_previousProgress;
@property(nonatomic) double previousYOffset; // @synthesize previousYOffset=_previousYOffset;
@property(nonatomic) double thresholdPositiveDirection; // @synthesize thresholdPositiveDirection=_thresholdPositiveDirection;
@property(nonatomic) double thresholdNegativeDirection; // @synthesize thresholdNegativeDirection=_thresholdNegativeDirection;
@property(nonatomic) double thresholdFromTop; // @synthesize thresholdFromTop=_thresholdFromTop;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)applyPositiveDirectionProgressTrackingThreshold;
- (void)applyNegativeDirectionProgressTrackingThreshold;
- (void)applyFromTopProgressTrackingThreshold;
- (id)init;

@end

