//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RLTStatsConfiguration.h"

@interface JDLAppStatsConfiguration : RLTStatsConfiguration
{
    _Bool _locationPermissionGranted;
}

@property(nonatomic) _Bool locationPermissionGranted; // @synthesize locationPermissionGranted=_locationPermissionGranted;
- (id)metaInformation;
- (void)updateLocationPermissions;
- (void)locationPermissionsDidChange;
- (long long)reachabilityStatus;
- (id)initWithApplicationId:(id)arg1;

@end

