//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface JDLAPIHealthMonitor : NSObject
{
    NSObject<OS_dispatch_queue> *_dispatchBgQueue;
    NSMutableDictionary *_dataQueue;
    NSMutableDictionary *_imageQueue;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *imageQueue; // @synthesize imageQueue=_imageQueue;
@property(retain, nonatomic) NSMutableDictionary *dataQueue; // @synthesize dataQueue=_dataQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dispatchBgQueue; // @synthesize dispatchBgQueue=_dispatchBgQueue;
- (void).cxx_destruct;
- (id)getErrorCodeForStatsKeyValue:(id)arg1;
- (id)getStatusCode:(long long)arg1;
- (id)getPathWithTemplate:(id)arg1;
- (id)getMethod:(id)arg1;
- (id)imageTypeForSource:(long long)arg1;
- (void)markJodelImageResponseFailureForSource:(long long)arg1 withURL:(id)arg2 responseStatusCode:(long long)arg3 error:(id)arg4;
- (void)markJodelImageResponseSuccessForSource:(long long)arg1 withURL:(id)arg2 responseHeaderFields:(id)arg3;
- (void)markJodelImageRequestStartForSource:(long long)arg1 withURL:(id)arg2 isThumbnail:(_Bool)arg3;
- (void)logRequestFailureWithResponse:(id)arg1 error:(id)arg2;
- (void)markRequestFailureWithRequestId:(id)arg1 response:(id)arg2 generalErrorType:(long long)arg3 operationType:(long long)arg4 responseStatusCode:(long long)arg5 error:(id)arg6;
- (void)markRequestFailureWithRequestId:(id)arg1 response:(id)arg2 responseStatusCode:(long long)arg3 error:(id)arg4;
- (void)markRequestSuccessWithRequestId:(id)arg1 responseDataLength:(unsigned long long)arg2 responseStatusCode:(long long)arg3;
- (void)markRequestStartWithRequestId:(id)arg1 requestPathTemplate:(id)arg2 requestMethod:(id)arg3 requestDataLength:(unsigned long long)arg4;
- (id)init;

@end

