//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString;

@interface JDLAPIHealthMonitorDataRequestMeta : NSObject
{
    NSNumber *_startTime;
    NSString *_requestPathTemplate;
    NSString *_requestMethod;
}

@property(copy, nonatomic) NSString *requestMethod; // @synthesize requestMethod=_requestMethod;
@property(copy, nonatomic) NSString *requestPathTemplate; // @synthesize requestPathTemplate=_requestPathTemplate;
@property(retain, nonatomic) NSNumber *startTime; // @synthesize startTime=_startTime;
- (void).cxx_destruct;
- (id)initWithStartTime:(id)arg1 requestPathTemplate:(id)arg2 requestMethod:(id)arg3;

@end

