//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JDLFeedCellParentProtocol.h"
#import "JDLFeedViewModelSourceProtocol.h"

@class NSString, RACSignal;

@interface JDLBaseFeedViewModel : NSObject <JDLFeedViewModelSourceProtocol, JDLFeedCellParentProtocol>
{
    long long _feedType;
    long long _feedOrder;
    RACSignal *_errorMessages;
    id <JDLFeedDataSourceProtocol> _dataSource;
}

@property(retain, nonatomic) id <JDLFeedDataSourceProtocol> dataSource; // @synthesize dataSource=_dataSource;
@property(readonly, nonatomic) RACSignal *errorMessages; // @synthesize errorMessages=_errorMessages;
@property(readonly, nonatomic) long long feedOrder; // @synthesize feedOrder=_feedOrder;
@property(nonatomic) long long feedType; // @synthesize feedType=_feedType;
- (void).cxx_destruct;
- (void)openPostForPostCellViewModel:(id)arg1;
- (void)openChannelForPostCellViewModel:(id)arg1 channel:(id)arg2;
- (void)openHashtagForPostCellViewModel:(id)arg1 hashtag:(id)arg2;
- (void)signalErrorMessage:(id)arg1;
- (void)voteForPostCellViewModel:(id)arg1 upvote:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)showPostActionsForPostCellViewModel:(id)arg1;
- (void)openChannel:(id)arg1;
- (void)openHashtag:(id)arg1;
- (id)buildCellViewModelForPost:(id)arg1;
- (id)cellsForPosts:(id)arg1;
- (id)removeCellForPostWithId:(id)arg1;
- (id)findAndRefreshCellViewModelWithPost:(id)arg1;
- (id)cellViewModelAtIndexPath:(id)arg1;
- (unsigned long long)numberOfRowsInSection:(long long)arg1;
- (id)initWithDataSource:(id)arg1 feedType:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

