//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class JDLRLTServicesDelegate;

@interface JDLBootstrap : NSObject
{
    JDLRLTServicesDelegate *_rltServicesDelegate;
}

@property(retain, nonatomic) JDLRLTServicesDelegate *rltServicesDelegate; // @synthesize rltServicesDelegate=_rltServicesDelegate;
- (void).cxx_destruct;
- (void)trackAccessibility;
- (void)startUserConfigService;
- (void)startLocalization;
- (void)startConfig;
- (void)startRLTAnalytics;
- (void)startFBAnalytics;
- (void)rltConfigDownloaded;
- (void)startServicesWithApplication:(id)arg1 launchOptions:(id)arg2;
- (id)init;

@end

