//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JDLNetworkCheckingBaseViewController.h"

@class JDLKarmaButtonItem;

@interface JDLBaseTabViewController : JDLNetworkCheckingBaseViewController
{
    JDLKarmaButtonItem *_karmaButtonItem;
}

@property(retain, nonatomic) JDLKarmaButtonItem *karmaButtonItem; // @synthesize karmaButtonItem=_karmaButtonItem;
- (void).cxx_destruct;
- (void)updateKarmaTitleLabel;
- (id)karmaTitleLabelColor;
- (void)showKarmaViewOnNavigationBar;
- (void)updateTitleLabelWithLocation;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)updateTitleAndCoordinatesWithNewLocation;
- (_Bool)displayKarmaValueOnNavigationBar;
- (void)viewDidLoad;
- (void)dealloc;

@end

