//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "JDLFeedCellProtocol.h"
#import "ZSWTappableLabelTapDelegate.h"

@class JDLBasePostCellViewModel, JDLFeedImageView, NSString, RACDisposable, UIButton, UIImageView, UILabel, UITapGestureRecognizer, UIView, ZSWTappableLabel;

@interface JDLBasePostCell : UITableViewCell <ZSWTappableLabelTapDelegate, JDLFeedCellProtocol>
{
    ZSWTappableLabel *_contentLabel;
    UIView *_whiteLine;
    UIButton *_actionButton;
    UIButton *_imageOpenButton;
    UILabel *_locationLabel;
    UIImageView *_locationIconView;
    UILabel *_markingPostLabel;
    UIImageView *_markingPostIconView;
    UILabel *_timeLabel;
    UIImageView *_timeIconView;
    UILabel *_centralLabel;
    UIImageView *_centralImageView;
    UIButton *_upvoteButton;
    UILabel *_voteCountLabel;
    UIButton *_downvoteButton;
    JDLFeedImageView *_jodelImageView;
    UILabel *_tapToViewLabel;
    UIView *_bottomView;
    UIButton *_thankJodlerButton;
    UIView *_thanksCellIcon;
    RACDisposable *_thankJodlerSubscription;
    RACDisposable *_thankJodlerIconSubscription;
    JDLBasePostCellViewModel *_viewModel;
    UITapGestureRecognizer *_cellGestureRecognizer;
}

+ (id)cellReuseIdentifier;
+ (id)cellNibName;
@property(retain, nonatomic) UITapGestureRecognizer *cellGestureRecognizer; // @synthesize cellGestureRecognizer=_cellGestureRecognizer;
@property(retain, nonatomic) JDLBasePostCellViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(retain, nonatomic) RACDisposable *thankJodlerIconSubscription; // @synthesize thankJodlerIconSubscription=_thankJodlerIconSubscription;
@property(retain, nonatomic) RACDisposable *thankJodlerSubscription; // @synthesize thankJodlerSubscription=_thankJodlerSubscription;
@property(nonatomic) __weak UIView *thanksCellIcon; // @synthesize thanksCellIcon=_thanksCellIcon;
@property(nonatomic) __weak UIButton *thankJodlerButton; // @synthesize thankJodlerButton=_thankJodlerButton;
@property(nonatomic) __weak UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(nonatomic) __weak UILabel *tapToViewLabel; // @synthesize tapToViewLabel=_tapToViewLabel;
@property(nonatomic) __weak JDLFeedImageView *jodelImageView; // @synthesize jodelImageView=_jodelImageView;
@property(nonatomic) __weak UIButton *downvoteButton; // @synthesize downvoteButton=_downvoteButton;
@property(nonatomic) __weak UILabel *voteCountLabel; // @synthesize voteCountLabel=_voteCountLabel;
@property(nonatomic) __weak UIButton *upvoteButton; // @synthesize upvoteButton=_upvoteButton;
@property(nonatomic) __weak UIImageView *centralImageView; // @synthesize centralImageView=_centralImageView;
@property(nonatomic) __weak UILabel *centralLabel; // @synthesize centralLabel=_centralLabel;
@property(nonatomic) __weak UIImageView *timeIconView; // @synthesize timeIconView=_timeIconView;
@property(nonatomic) __weak UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(nonatomic) __weak UIImageView *markingPostIconView; // @synthesize markingPostIconView=_markingPostIconView;
@property(nonatomic) __weak UILabel *markingPostLabel; // @synthesize markingPostLabel=_markingPostLabel;
@property(nonatomic) __weak UIImageView *locationIconView; // @synthesize locationIconView=_locationIconView;
@property(nonatomic) __weak UILabel *locationLabel; // @synthesize locationLabel=_locationLabel;
@property(nonatomic) __weak UIButton *imageOpenButton; // @synthesize imageOpenButton=_imageOpenButton;
@property(nonatomic) __weak UIButton *actionButton; // @synthesize actionButton=_actionButton;
@property(nonatomic) __weak UIView *whiteLine; // @synthesize whiteLine=_whiteLine;
@property(nonatomic) __weak ZSWTappableLabel *contentLabel; // @synthesize contentLabel=_contentLabel;
- (void).cxx_destruct;
- (id)getAccessibilityElements;
- (void)prepareAccessibility;
- (void)tappableLabel:(id)arg1 tappedAtIndex:(long long)arg2 withAttributes:(id)arg3;
- (void)showMarkingPost:(_Bool)arg1;
- (void)showSeparatorLine:(_Bool)arg1;
- (void)showLocation:(_Bool)arg1;
- (void)showCommentsIcon:(_Bool)arg1;
- (void)showActionButton:(_Bool)arg1;
- (void)setInteractionEnabled:(_Bool)arg1 enableButtons:(_Bool)arg2;
- (_Bool)isImagePost;
- (void)dismissLargeImage;
- (void)showLargeImage;
- (void)refreshVoteState:(long long)arg1 voteCount:(id)arg2;
- (void)refreshVoteState;
- (_Bool)cellStillHasTheSameCellId:(id)arg1;
- (void)setupPostMessage:(id)arg1;
- (void)upvote:(_Bool)arg1;
- (void)openImageTap:(id)arg1;
- (void)downvoteTap:(id)arg1;
- (void)tappedThanks:(id)arg1;
- (void)upvoteTap:(id)arg1;
- (void)actionTap:(id)arg1;
- (void)hideThankJodlerButtonAnimated:(_Bool)arg1;
- (void)showThankJodlerButtonAnimated:(_Bool)arg1;
- (void)updateThankAJodlerButton;
- (void)updateThankAJodlerIcon;
- (void)prepareForReuse;
- (void)configureWithViewModel:(id)arg1;
- (void)didTapCell;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

