//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JDLFeedCellViewModelProtocol.h"

@class NSString, SWGPost;

@interface JDLBasePostCellViewModel : NSObject <JDLFeedCellViewModelProtocol>
{
    _Bool _showThankJodlerButton;
    _Bool _showThankedIcon;
    SWGPost *_post;
    unsigned long long _cellType;
    id <JDLFeedCellParentProtocol> _feedCellParent;
}

@property(nonatomic) __weak id <JDLFeedCellParentProtocol> feedCellParent; // @synthesize feedCellParent=_feedCellParent;
@property(nonatomic) _Bool showThankedIcon; // @synthesize showThankedIcon=_showThankedIcon;
@property(nonatomic) _Bool showThankJodlerButton; // @synthesize showThankJodlerButton=_showThankJodlerButton;
@property(nonatomic) unsigned long long cellType; // @synthesize cellType=_cellType;
@property(retain, nonatomic) SWGPost *post; // @synthesize post=_post;
- (void).cxx_destruct;
- (void)dismissThankButton;
- (_Bool)shouldShowHomeLocationIcon;
- (id)dequeueIdentifier;
- (void)didSelect;
- (double)cellHeight;
- (id)cellId;
- (_Bool)shouldShowLinks;
- (_Bool)isCellTypeOptionSet:(unsigned long long)arg1;
- (_Bool)shouldEnableButtons;
- (_Bool)shouldEnableUserInteractions;
- (_Bool)shouldShowComments;
- (_Bool)shouldApplyLightStyle;
- (_Bool)shouldShowPictureFeedButton;
- (_Bool)shouldUseBoldFont;
- (_Bool)shouldShowChannels;
- (_Bool)shouldShowHashtags;
- (_Bool)shouldShowMarking;
- (_Bool)shouldShowActionButton;
- (_Bool)shouldShowSeparatorLine;
- (_Bool)shouldShowLocation;
- (void)showAvailableActions;
- (void)openPictureFeed;
- (void)openURL:(id)arg1;
- (void)openChannel:(id)arg1;
- (void)openHashtag:(id)arg1;
- (id)dateFormatter;
- (_Bool)hasImage;
- (void)upvote:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)hasPossibilityToVote;
- (id)postVoteCount;
- (id)postReplyCount;
- (long long)votingState;
- (id)postMessage;
- (id)postLocationName;
- (_Bool)hasLocation;
- (id)postColor;
- (id)postCreatedAtText;
- (id)postId;
- (void)giveThanks;
- (id)initWithPost:(id)arg1 parent:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

