//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JDLComboFeedFetchServiceProtocol.h"

@class NSString;

@interface JDLChannelsFeedFetchService : NSObject <JDLComboFeedFetchServiceProtocol>
{
    id <JDLChannelsFeedFetchServiceDelegate> _channelsDelegate;
    NSString *_channel;
}

@property(copy, nonatomic) NSString *channel; // @synthesize channel=_channel;
@property(nonatomic) __weak id <JDLChannelsFeedFetchServiceDelegate> channelsDelegate; // @synthesize channelsDelegate=_channelsDelegate;
- (void).cxx_destruct;
- (_Bool)isSetToHome;
- (id)fetchPostsForFeedOrder:(long long)arg1 afterId:(id)arg2 skip:(long long)arg3 completion:(CDUnknownBlockType)arg4;
- (id)fetchComboWithCompletion:(CDUnknownBlockType)arg1;
- (id)initWithChannel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

