//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JDLConfigValues : NSObject
{
}

+ (_Bool)isDevOrTestflightEnvironment;
+ (id)settingsCustomLinkURL;
+ (id)zendeskFAQURL;
+ (id)zendeskTicketURL;
+ (id)termsURL;
+ (id)privacyPolicyURL;
+ (id)eulaURLForComposing;
+ (id)eulaURL;
+ (id)moderationRulesURL;
+ (long long)pictureFeedRequestLimit;
+ (long long)fetchRequestLimit;
+ (double)serverTimestampThreshold;
+ (id)rateAppIdeaEmail;

@end

