//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JDLChannelsNotificationsStorableProtocol.h"

@class NSString;

@interface JDLChannelsNotificationsDefaults : NSObject <JDLChannelsNotificationsStorableProtocol>
{
}

- (id)getChannelsNotificationsKey;
- (id)getChannelOpensKey;
- (void)removeTimestampsForOtherThan:(id)arg1;
- (void)removeTimestampForChannel:(id)arg1;
- (void)removeNotificationForChannel:(id)arg1;
- (id)getChannelsWithNotifications;
- (void)addChannelsWithNotifications:(id)arg1;
- (id)getChannelOpensTimestamps;
- (void)saveChannelOpen:(id)arg1 withOverwrite:(_Bool)arg2;
- (void)saveChannelOpenIfMissing:(id)arg1;
- (void)saveChannelOpen:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

