//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class JDLChannelCellViewModel, UIImageView, UILabel, UIView;

@interface JDLChannelCollectionCell : UICollectionViewCell
{
    UIView *_containerView;
    UIImageView *_channelImage;
    UILabel *_channelName;
    UILabel *_followers;
    UIImageView *_channelPlaceholderIcon;
    JDLChannelCellViewModel *_currentViewModel;
}

@property(retain, nonatomic) JDLChannelCellViewModel *currentViewModel; // @synthesize currentViewModel=_currentViewModel;
@property(nonatomic) __weak UIImageView *channelPlaceholderIcon; // @synthesize channelPlaceholderIcon=_channelPlaceholderIcon;
@property(nonatomic) __weak UILabel *followers; // @synthesize followers=_followers;
@property(nonatomic) __weak UILabel *channelName; // @synthesize channelName=_channelName;
@property(nonatomic) __weak UIImageView *channelImage; // @synthesize channelImage=_channelImage;
@property(nonatomic) __weak UIView *containerView; // @synthesize containerView=_containerView;
- (void).cxx_destruct;
- (void)accessibilityElementDidBecomeFocused;
- (unsigned long long)accessibilityTraits;
- (id)accessibilityLabel;
- (_Bool)isAccessibilityElement;
- (void)loadImageForViewModel:(id)arg1;
- (void)configureWithViewModel:(id)arg1;
- (void)awakeFromNib;

@end

