//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString;

@interface JDLChannelCellViewModel : NSObject
{
    _Bool _containsNotification;
    _Bool _shouldShowFollowButton;
    _Bool _isFollowing;
    _Bool _isLoading;
    NSString *_channelLabel;
    NSNumber *_numberOfFollowers;
    NSString *_imageUrl;
}

@property(retain, nonatomic) NSString *imageUrl; // @synthesize imageUrl=_imageUrl;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(nonatomic) _Bool isFollowing; // @synthesize isFollowing=_isFollowing;
@property(nonatomic) _Bool shouldShowFollowButton; // @synthesize shouldShowFollowButton=_shouldShowFollowButton;
@property(retain, nonatomic) NSNumber *numberOfFollowers; // @synthesize numberOfFollowers=_numberOfFollowers;
@property(nonatomic) _Bool containsNotification; // @synthesize containsNotification=_containsNotification;
@property(copy, nonatomic) NSString *channelLabel; // @synthesize channelLabel=_channelLabel;
- (void).cxx_destruct;
- (id)initWithChannel:(id)arg1 containsNotification:(_Bool)arg2 numberOfFollowers:(id)arg3;

@end

