//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class JDLDraft, NSString;

@protocol JDLDraftStorable <NSObject>
- (JDLDraft *)retrieveDraftWithId:(NSString *)arg1;
- (void)removeDraft:(JDLDraft *)arg1;
- (void)saveDraft:(JDLDraft *)arg1;
@end

