//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

#import "JDLScrollableContentProtocol.h"

@class NSString;

@interface JDLDefaultNavigationController : UINavigationController <JDLScrollableContentProtocol>
{
}

- (void)scrollToTopAnimated:(_Bool)arg1;
- (void)updateKarmaTitleLabel;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

