//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

@interface JDLDraft : NSObject
{
    NSString *_text;
    NSString *_threadId;
    NSDate *_creationDate;
    unsigned long long _cursorPosition;
}

@property(nonatomic) unsigned long long cursorPosition; // @synthesize cursorPosition=_cursorPosition;
@property(retain, nonatomic) NSDate *creationDate; // @synthesize creationDate=_creationDate;
@property(copy, nonatomic) NSString *threadId; // @synthesize threadId=_threadId;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
- (void).cxx_destruct;

@end

