//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel, UITapGestureRecognizer;

@interface JDLErrorMessageView : UIView
{
    UILabel *_errorTextLabel;
    UITapGestureRecognizer *_tapRecognizer;
}

+ (id)loadFromNib;
@property(retain, nonatomic) UITapGestureRecognizer *tapRecognizer; // @synthesize tapRecognizer=_tapRecognizer;
@property(nonatomic) __weak UILabel *errorTextLabel; // @synthesize errorTextLabel=_errorTextLabel;
- (void).cxx_destruct;
- (void)setErrorMessage:(id)arg1;
- (void)dismissView;
- (void)awakeFromNib;

@end

