//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSMutableSet;

@interface JDLFeedFetchLockTrackHelper : NSObject
{
    _Bool _isLoading;
    NSMutableSet *_loadFinishedForOrder;
    NSMutableDictionary *_lastMoreLoadDetailsForDuplicateFix;
    NSObject *_lock;
}

@property(retain, nonatomic) NSObject *lock; // @synthesize lock=_lock;
@property(retain, nonatomic) NSMutableDictionary *lastMoreLoadDetailsForDuplicateFix; // @synthesize lastMoreLoadDetailsForDuplicateFix=_lastMoreLoadDetailsForDuplicateFix;
@property(retain, nonatomic) NSMutableSet *loadFinishedForOrder; // @synthesize loadFinishedForOrder=_loadFinishedForOrder;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
- (void).cxx_destruct;
- (void)trackFeedPaging:(long long)arg1 order:(long long)arg2 source:(id)arg3 feedItemsCount:(unsigned long long)arg4;
- (_Bool)isFullListLoadedForType:(long long)arg1 order:(long long)arg2 responseItemsCount:(unsigned long long)arg3 error:(id)arg4 withStartAfterId:(id)arg5 skip:(unsigned long long)arg6 feedItemsCount:(unsigned long long)arg7;
- (void)pullToRefreshCompleted:(long long)arg1 feedOrder:(long long)arg2 error:(id)arg3;
- (void)pullToRefreshStartedFrom:(id)arg1 feedType:(long long)arg2 feedOrder:(long long)arg3;
- (void)fetchMoreCompleted:(long long)arg1 feedOrder:(long long)arg2 error:(id)arg3 responseItemsCount:(unsigned long long)arg4 afterId:(id)arg5 skip:(unsigned long long)arg6 feedItemsCount:(unsigned long long)arg7;
- (void)fetchMoreStarted:(long long)arg1 feedOrder:(long long)arg2;
- (void)fetchInitialCompleted:(long long)arg1 feedOrder:(long long)arg2;
- (void)fetchInitialStarted:(long long)arg1 feedOrder:(long long)arg2;
- (_Bool)isPossibleToFetchMore:(long long)arg1;
- (id)init;

@end

