//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JDLFeedActionManager : NSObject
{
}

- (void)trackFlagJodel:(id)arg1 statsContext:(id)arg2 withReasonId:(id)arg3 subreasonId:(id)arg4;
- (void)trackDeleteJodel:(id)arg1 statsContext:(id)arg2;
- (id)viewToPresentOn;
- (void)showToastWithMessage:(id)arg1;
- (void)showToastAfterNotificationPermissionsDenied;
- (void)showToastAfterNotificationSubscriptionEnabled:(_Bool)arg1;
- (void)showToastAfterDeleting;
- (void)showToastAfterFlagging;
- (void)flagJodel:(id)arg1 reasonId:(id)arg2 subreasonId:(id)arg3 statsContext:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)flagJodel:(id)arg1 withReason:(long long)arg2 statsContext:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)hideJodel:(id)arg1 statsContext:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)confirmDeleteJodel:(id)arg1 statsContext:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (_Bool)userHasNotificationEnabledForRootPost:(id)arg1;
- (void)addCancelItemForAlertView:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)addCancelItemForActionSheet:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)showNewFlaggingMenuForJodel:(id)arg1 statsContext:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)showOldFlaggingMenuForJodel:(id)arg1 statsContext:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)sendToggleNotificationForPost:(id)arg1 enabled:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)addNotificationItemForActionSheet:(id)arg1 rootJodel:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)showActionsForJodel:(id)arg1 rootJodel:(id)arg2 statsContext:(id)arg3 withCompletionBlock:(CDUnknownBlockType)arg4;

@end

