//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class JDLBasePostCell, UITableView, UIViewController;

@interface JDLFeedFullScreenPreview : NSObject
{
    UIViewController *_feedViewController;
    UITableView *_feedTableView;
    JDLBasePostCell *_currentCell;
}

@property(nonatomic) __weak JDLBasePostCell *currentCell; // @synthesize currentCell=_currentCell;
@property(nonatomic) __weak UITableView *feedTableView; // @synthesize feedTableView=_feedTableView;
@property(nonatomic) __weak UIViewController *feedViewController; // @synthesize feedViewController=_feedViewController;
- (void).cxx_destruct;
- (void)dismissLargePostImage;
- (void)showLargePostImageFromIndexPath:(id)arg1;
- (void)handleLongPress:(id)arg1;
- (_Bool)isVisible;
- (void)setupLongPressPreviewWithViewController:(id)arg1 tableView:(id)arg2;

@end

