//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@class JDLFeedFullScreenImageView, NSString;

@interface JDLFeedImageView : UIImageView
{
    long long _trackingSource;
    NSString *_thumbnailURL;
    NSString *_largeImageURL;
    JDLFeedFullScreenImageView *_fullScreenImageView;
}

@property(retain, nonatomic) JDLFeedFullScreenImageView *fullScreenImageView; // @synthesize fullScreenImageView=_fullScreenImageView;
@property(copy, nonatomic) NSString *largeImageURL; // @synthesize largeImageURL=_largeImageURL;
@property(copy, nonatomic) NSString *thumbnailURL; // @synthesize thumbnailURL=_thumbnailURL;
@property(nonatomic) long long trackingSource; // @synthesize trackingSource=_trackingSource;
- (void).cxx_destruct;
- (void)loadImageThumbnail:(_Bool)arg1 withCompletionBlock:(CDUnknownBlockType)arg2;
- (id)imageLoadRequestForURLString:(id)arg1;
- (void)destroyLargeImageView;
- (_Bool)isLargeImageDisplayed;
- (void)dismissLargeImage;
- (void)showLargeImage;
- (void)resetState;
- (void)setupAndLoadThumbnail:(id)arg1 imageUrl:(id)arg2;

@end

