//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JDLFeedConstants : NSObject
{
}

+ (id)subreasonForReason:(long long)arg1;
+ (id)reasonsKeysForImagePost;
+ (id)reasonsKeysForTextPost;
+ (id)getLocalisedTitleForReason:(long long)arg1;

@end

