//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JDLGeneralSettings : NSObject
{
}

+ (void)clearSettings;
+ (void)setClientID:(id)arg1;
+ (id)getClientID;
+ (void)setDistinctID:(id)arg1;
+ (id)getDistinctID;
+ (void)increasePictureFeedOpenCount;
+ (long long)pictureFeedOpenCount;
+ (void)increaseAppColdStartCount;
+ (long long)appColdStartCount;
+ (void)setUserProfileType:(id)arg1;
+ (id)userProfileType;
+ (void)setApiRequestToken:(id)arg1;
+ (id)apiRequestToken;
+ (id)lastStoredUserCountry;
+ (id)lastStoredUserCountryISOCode;
+ (void)setLastUserCountryISOCode:(id)arg1;
+ (id)lastStoredUserCity;
+ (void)setLastUserCity:(id)arg1;
+ (id)lastServerSavedUserLocation;
+ (void)setLastServerSavedUserLocation:(id)arg1;
+ (id)lastStoredUserLocation;
+ (void)setLastUserLocation:(id)arg1;
+ (_Bool)storePushToken:(id)arg1;
+ (id)storedPushToken;
+ (_Bool)pushPermissionsAllowed;
+ (void)setPushPermissionStatusToActive:(_Bool)arg1;
+ (void)setHomeCity:(id)arg1;
+ (id)homeCity;
+ (void)updateHomeIsSet:(_Bool)arg1;
+ (_Bool)isHomeSet;
+ (void)toggleFlash;
+ (_Bool)flashEnabled;
+ (void)increasePostPinSucceededCalls;
+ (long long)numberOfPostPinSucceededCalls;
+ (void)increaseSentJodelCount;
+ (long long)numberOfSentJodels;
+ (void)setNewKarmaValue:(id)arg1;
+ (id)currentKarmaValue;
+ (void)setEULAAccepted:(_Bool)arg1;
+ (_Bool)wasEULAAccepted;
+ (void)setDidUseCameraShortcut:(_Bool)arg1;
+ (_Bool)didUseCameraShortcut;

@end

