//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class RACSubject;

@interface JDLHomeMapViewModel : NSObject
{
    RACSubject *_didSetHomeWithSuccess;
    RACSubject *_setHomeFailed;
}

@property(retain, nonatomic) RACSubject *setHomeFailed; // @synthesize setHomeFailed=_setHomeFailed;
@property(retain, nonatomic) RACSubject *didSetHomeWithSuccess; // @synthesize didSetHomeWithSuccess=_didSetHomeWithSuccess;
- (void).cxx_destruct;
- (void)setCurentHome:(id)arg1;
- (id)init;

@end

