//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface JDLKarmaResetInvestigation : NSObject
{
    NSMutableArray *_events;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableArray *events; // @synthesize events=_events;
- (void).cxx_destruct;
- (void)saveHistoryToKeychainWithNewItem:(id)arg1 oldItem:(id)arg2 forKey:(id)arg3;
- (id)keychainHistoryValueForKey:(id)arg1;
- (id)jsonToSend;
- (void)send;
- (void)addEvent:(id)arg1 values:(id)arg2;
- (void)defaultsUuidChangedTo:(id)arg1 old:(id)arg2;
- (void)keychainUuidChangedTo:(id)arg1 old:(id)arg2;
- (void)distinctIdChangedTo:(id)arg1 old:(id)arg2;
- (void)clientIdChangedTo:(id)arg1 old:(id)arg2;
- (void)karmaResetHappenedNewKarma:(id)arg1 old:(id)arg2;
- (id)init;

@end

