//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

@class NSNumber, NSString;

@interface JDLLocalizedLabel : UILabel
{
    _Bool _upperCase;
    NSString *_localizationKey;
    NSNumber *_letterSpacing;
}

@property(nonatomic) _Bool upperCase; // @synthesize upperCase=_upperCase;
@property(retain, nonatomic) NSNumber *letterSpacing; // @synthesize letterSpacing=_letterSpacing;
@property(copy, nonatomic) NSString *localizationKey; // @synthesize localizationKey=_localizationKey;
- (void).cxx_destruct;
- (void)updateAttributes;
- (void)awakeFromNib;

@end

