//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JDLSubfeedViewModel.h"

@class NSString;

@interface JDLModerationSubfeedViewModel : JDLSubfeedViewModel
{
    NSString *_focusedPostId;
}

@property(readonly, nonatomic) NSString *focusedPostId; // @synthesize focusedPostId=_focusedPostId;
- (void).cxx_destruct;
- (void)refreshBasePostCellViewModel:(id)arg1;
- (id)fetchReversed:(_Bool)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (id)initWithFocusPostId:(id)arg1 withParentId:(id)arg2 postColor:(id)arg3 feedType:(long long)arg4 feedOrder:(long long)arg5;

@end

