//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class JDLTriangleView, UILabel;

@interface JDLMapAnnotationView : UIView
{
    JDLTriangleView *_triangleView;
    UILabel *_annotationLabel;
}

@property(nonatomic) __weak UILabel *annotationLabel; // @synthesize annotationLabel=_annotationLabel;
@property(retain, nonatomic) JDLTriangleView *triangleView; // @synthesize triangleView=_triangleView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)awakeFromNib;

@end

