//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JDLOAuthHandler : NSObject
{
}

+ (id)storedCredentials;
+ (_Bool)clearCredentialsFromKeychain;
+ (void)storeRegistrationCredentials:(id)arg1;
+ (void)updateOAuthCredentials:(id)arg1;
+ (_Bool)isExpired;
+ (_Bool)hasAccessToken;
+ (id)refreshToken;
+ (id)accessToken;

@end

