//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

@class NSArray, UILabel;

@interface JDLPostFlagDetailsViewController : UITableViewController
{
    long long _reason;
    CDUnknownBlockType _completion;
    UILabel *_headerLabel;
    NSArray *_detailedReasons;
}

@property(retain, nonatomic) NSArray *detailedReasons; // @synthesize detailedReasons=_detailedReasons;
@property(nonatomic) __weak UILabel *headerLabel; // @synthesize headerLabel=_headerLabel;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(nonatomic) long long reason; // @synthesize reason=_reason;
- (void).cxx_destruct;
- (id)detailedReasonKeyForIndexPath:(id)arg1;
- (id)detailedReasonAttributedStringForIndexPath:(id)arg1;
- (void)flag:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewDidLoad;

@end

