//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JDLPictureGeoFilterHelper : NSObject
{
}

+ (id)attributedStringForGeoFilterText:(id)arg1 fontSize:(double)arg2 screenWidth:(double)arg3 withMaxWidth:(double)arg4;
+ (id)attributedStringForGeoFilterText:(id)arg1 screenWidth:(double)arg2 withMaxWidth:(double)arg3;

@end

