//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CLLocationManagerDelegate.h"

@class CLGeocoder, CLLocationManager, NSString, RACSignal;

@interface JDLPictureGeoFilter : NSObject <CLLocationManagerDelegate>
{
    RACSignal *_filterTextSignal;
    CLLocationManager *_locationManager;
    CLGeocoder *_geocoder;
    double _trackingStartedAt;
}

@property(nonatomic) double trackingStartedAt; // @synthesize trackingStartedAt=_trackingStartedAt;
@property(retain, nonatomic) CLGeocoder *geocoder; // @synthesize geocoder=_geocoder;
@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property(retain, nonatomic) RACSignal *filterTextSignal; // @synthesize filterTextSignal=_filterTextSignal;
- (void).cxx_destruct;
- (void)trackSuccess:(id)arg1 duration:(unsigned long long)arg2;
- (void)trackFailure:(id)arg1;
- (void)trackLocationReversed:(double)arg1 error:(id)arg2;
- (void)trackLocationExists;
- (void)trackLocationFail:(id)arg1;
- (void)currentLocationUpdate:(id)arg1;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
- (void)startLocationGeoTrackingAndReversing;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

