//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JDLNetworkCheckingBaseViewController.h"

#import "TLMColorPickerViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UITextViewDelegate.h"

@class JDLPictureGeoFilter, JTImageLabel, NSLayoutConstraint, NSString, SWGPost, TLMColorPickerView, TLMShadowButton, UIActivityIndicatorView, UIButton, UIColor, UIImage, UIImageView, UILabel, UISwipeGestureRecognizer, UITextView, UIView;

@interface JDLPreviewViewController : JDLNetworkCheckingBaseViewController <TLMColorPickerViewDelegate, UITextViewDelegate, UIGestureRecognizerDelegate>
{
    UIImage *_previewImage;
    UIColor *_postColor;
    SWGPost *_ancestorPost;
    NSString *_channel;
    id <JDLPreviewViewControllerDelegate> _delegate;
    UIView *_captureView;
    UISwipeGestureRecognizer *_swipeLeftGesture;
    UISwipeGestureRecognizer *_swipeRightGesture;
    UILabel *_geoFilterLabel;
    UIImageView *_previewImageView;
    TLMShadowButton *_sendButton;
    TLMColorPickerView *_pickerView;
    TLMShadowButton *_backButton;
    UIActivityIndicatorView *_indicatorView;
    UIButton *_savePictureButton;
    NSLayoutConstraint *_geoPicFilterCenterConstraint;
    UIButton *_geoPicFilterButton;
    JTImageLabel *_savedHud;
    UITextView *_textInputView;
    JDLPictureGeoFilter *_geoPicFilter;
    NSString *_placeholderString;
    double _textViewYOrigin;
    double _currentKeyboardHeight;
    unsigned long long _postExtras;
}

@property(nonatomic) unsigned long long postExtras; // @synthesize postExtras=_postExtras;
@property(nonatomic) double currentKeyboardHeight; // @synthesize currentKeyboardHeight=_currentKeyboardHeight;
@property(nonatomic) double textViewYOrigin; // @synthesize textViewYOrigin=_textViewYOrigin;
@property(retain, nonatomic) NSString *placeholderString; // @synthesize placeholderString=_placeholderString;
@property(retain, nonatomic) JDLPictureGeoFilter *geoPicFilter; // @synthesize geoPicFilter=_geoPicFilter;
@property(retain, nonatomic) UITextView *textInputView; // @synthesize textInputView=_textInputView;
@property(retain, nonatomic) JTImageLabel *savedHud; // @synthesize savedHud=_savedHud;
@property(nonatomic) __weak UIButton *geoPicFilterButton; // @synthesize geoPicFilterButton=_geoPicFilterButton;
@property(nonatomic) __weak NSLayoutConstraint *geoPicFilterCenterConstraint; // @synthesize geoPicFilterCenterConstraint=_geoPicFilterCenterConstraint;
@property(nonatomic) __weak UIButton *savePictureButton; // @synthesize savePictureButton=_savePictureButton;
@property(nonatomic) __weak UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(nonatomic) __weak TLMShadowButton *backButton; // @synthesize backButton=_backButton;
@property(nonatomic) __weak TLMColorPickerView *pickerView; // @synthesize pickerView=_pickerView;
@property(nonatomic) __weak TLMShadowButton *sendButton; // @synthesize sendButton=_sendButton;
@property(nonatomic) __weak UIImageView *previewImageView; // @synthesize previewImageView=_previewImageView;
@property(nonatomic) __weak UILabel *geoFilterLabel; // @synthesize geoFilterLabel=_geoFilterLabel;
@property(retain, nonatomic) UISwipeGestureRecognizer *swipeRightGesture; // @synthesize swipeRightGesture=_swipeRightGesture;
@property(retain, nonatomic) UISwipeGestureRecognizer *swipeLeftGesture; // @synthesize swipeLeftGesture=_swipeLeftGesture;
@property(nonatomic) __weak UIView *captureView; // @synthesize captureView=_captureView;
@property(nonatomic) __weak id <JDLPreviewViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *channel; // @synthesize channel=_channel;
@property(retain, nonatomic) SWGPost *ancestorPost; // @synthesize ancestorPost=_ancestorPost;
@property(retain, nonatomic) UIColor *postColor; // @synthesize postColor=_postColor;
@property(retain, nonatomic) UIImage *previewImage; // @synthesize previewImage=_previewImage;
- (void).cxx_destruct;
- (void)setTextCaptionEnabled:(_Bool)arg1;
- (void)setGeoFilterEnabled:(_Bool)arg1;
- (_Bool)geoPicFilterEnabled;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)showLoadingIndicator:(_Bool)arg1;
- (id)imageWithView:(id)arg1;
- (void)colorPickerDidSelectColor:(id)arg1;
- (void)colorPickerWillExpand;
- (void)keyboardWillDisappear:(id)arg1;
- (void)keyboardWillAppear:(id)arg1;
- (void)resizeTextInputForText:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidChangeSelection:(id)arg1;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (void)resignTextInputResponderAndRemoveIfNeeded;
- (void)tappedOnPhoto:(id)arg1;
- (void)panGesture:(id)arg1;
- (struct CGRect)validateBoxOutOfScreen:(struct CGRect)arg1;
- (void)thisImage:(id)arg1 hasBeenSavedInPhotoAlbumWithError:(id)arg2 usingContextInfo:(void *)arg3;
- (_Bool)isSavePhotoDenied;
- (void)showSavePhotoDeniedMessage;
- (void)refreshGeoFilterVisibility;
- (void)refreshGeoFilterText:(id)arg1;
- (void)refreshFilterButtonState;
- (void)setupGeoFilter;
- (void)refreshGeoPicFilterEnabled:(_Bool)arg1;
- (void)swipeRight:(id)arg1;
- (void)swipeLeft:(id)arg1;
- (void)filterTap:(id)arg1;
- (void)backTap:(id)arg1;
- (id)postImage;
- (void)sendPressed:(id)arg1;
- (void)savePictureTap:(id)arg1;
- (_Bool)disableAutomaticNetworkErrorMessageView;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (_Bool)prefersStatusBarHidden;
- (void)registerForKeyboardNotifications;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

