//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JDLRemoteNotificationsService : NSObject
{
}

+ (id)sharedInstance;
- (id)pushPermissionsCountMagicSequence;
- (_Bool)shouldCheckPermissionsForSentJodels:(long long)arg1;
- (_Bool)shouldCheckPermissionsForPinnedCalls:(long long)arg1;
- (void)tryToAskForPushPermissions;
- (void)sendUserToSettings;
- (void)registerForNotifications;
- (void)askUserToReceiveNotifications:(CDUnknownBlockType)arg1;
- (void)askForPermissionsWithCompletion:(CDUnknownBlockType)arg1;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (_Bool)checkIfUserEnabledPushNotification;

@end

