//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RLTConfigDelegate.h"
#import "RLTLocalizationDelegate.h"
#import "RLTStatsDelegate.h"

@class NSString;

@interface JDLRLTServicesDelegate : NSObject <RLTStatsDelegate, RLTLocalizationDelegate, RLTConfigDelegate>
{
}

- (void)trackDebugEventWithSubject:(id)arg1 item:(id)arg2 subItem:(id)arg3 duration:(unsigned long long)arg4;
- (void)rltConfigParsedWithDuration:(unsigned long long)arg1;
- (void)rltConfigFetchedFromServerWithDuration:(unsigned long long)arg1;
- (void)rltConfigFetchingFromServerFailedWithError:(id)arg1;
- (void)rltConfigFetchingFromServerStartedWithURL:(id)arg1;
- (void)rltConfigFetchingFromServerSkippedWithError:(id)arg1;
- (void)rltConfigFetchingFromServerSkipped;
- (void)rltLocalizationParsedWithDuration:(unsigned long long)arg1;
- (void)rltLocalizationFetchedFromServerWithDuration:(unsigned long long)arg1;
- (void)rltLocalizationFetchingFromServerFailedWithError:(id)arg1;
- (void)rltLocalizationFetchingFromServerStartedWithURL:(id)arg1;
- (void)rltLocalizationFetchingFromServerSkippedWithError:(id)arg1;
- (void)rltLocalizationFetchingFromServerSkipped;
- (void)collectorWillFlushStatistics:(id)arg1;
- (void)dispatcher:(id)arg1 sentWithDuration:(double)arg2;
- (void)dispatcher:(id)arg1 sendingFailedWithError:(id)arg2 duration:(double)arg3;
- (void)dispatcher:(id)arg1 willSendDataToURL:(id)arg2 length:(unsigned long long)arg3;
- (void)serializer:(id)arg1 willSerializeDictionary:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

