//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JDLRateApp : NSObject
{
}

+ (id)sharedInstance;
+ (void)load;
- (void)swizzle_promptForRating;
- (void)promptIfAllCriteriaMet;
- (void)promptForRating;
- (void)checkToShowRating;
- (void)setupRateDialogConfig;

@end

