//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "JDLLocationDelegate.h"

@class JDLRegistrationButton, JDLRegistrationViewModel, NSString, UILabel;

@interface JDLRegistrationViewController : UIViewController <JDLLocationDelegate>
{
    _Bool _isRegisteringUser;
    _Bool _isToastVisible;
    UILabel *_descriptionLabel;
    JDLRegistrationButton *_registrationButton;
    JDLRegistrationViewModel *_viewModel;
}

@property(retain, nonatomic) JDLRegistrationViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(nonatomic) _Bool isToastVisible; // @synthesize isToastVisible=_isToastVisible;
@property(nonatomic) _Bool isRegisteringUser; // @synthesize isRegisteringUser=_isRegisteringUser;
@property(nonatomic) __weak JDLRegistrationButton *registrationButton; // @synthesize registrationButton=_registrationButton;
@property(nonatomic) __weak UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
- (void).cxx_destruct;
- (_Bool)prefersStatusBarHidden;
- (void)jdlLocationUpdateNewLocationReceived;
- (void)jdlLocationUpdateDidFail;
- (void)openLocationPermissionPanel;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)setDefaultIntroText;
- (void)checkCurrentGPSPermission;
- (void)showErrorStateWithErrorMessage:(id)arg1;
- (void)showLoadingState;
- (void)registerUser;
- (void)registerTapped:(id)arg1;
- (void)bindViewModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

