//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JDLSWGRequestProcessor : NSObject
{
    double _serverDiffInterval;
}

+ (id)sharedInstance;
@property(nonatomic) double serverDiffInterval; // @synthesize serverDiffInterval=_serverDiffInterval;
- (id)currentServerTimestamp;
- (double)storedServerDiffInterval;
- (void)trackServerTimestampDiff:(double)arg1;
- (void)processCompletedRequestResponse:(id)arg1;
- (id)iso8601DateDateFormatter;
- (id)init;

@end

