//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface JDLSettingsViewModel : NSObject
{
    NSArray *_menuItems;
}

@property(retain, nonatomic) NSArray *menuItems; // @synthesize menuItems=_menuItems;
- (void).cxx_destruct;
- (id)items;
- (void)refreshItems;
- (id)emojiAtIndexPath:(id)arg1;
- (id)textAtIndexPath:(id)arg1;
- (id)detailedTextAtIndexPath:(id)arg1;
- (long long)numberOfItems;
- (unsigned long long)menuTypeForIndexPath:(id)arg1;

@end

