//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JDLFeedCellParentProtocol.h"
#import "JDLFeedViewModelSourceProtocol.h"

@class JDLBaseFeedDataSource, JDLFeedActionManager, NSString, RACSignal, UIColor;

@interface JDLSubfeedViewModel : NSObject <JDLFeedViewModelSourceProtocol, JDLFeedCellParentProtocol>
{
    _Bool _isPostPinned;
    _Bool _postPinningEnabled;
    _Bool _hideReplyButton;
    _Bool _shouldScrollToBottom;
    _Bool _shouldShowLinks;
    _Bool _isLoading;
    _Bool _parentPostIsMyJodel;
    long long _feedType;
    long long _feedOrder;
    RACSignal *_cellIndexPathDeleteSignal;
    RACSignal *_deleteSubfeedSignal;
    RACSignal *_errorMessages;
    NSString *_originalPostId;
    UIColor *_postColor;
    NSString *_pinCountFormattedValue;
    NSString *_channel;
    NSString *_hashtag;
    NSString *_nextPageOffset;
    NSString *_previousPageOffset;
    NSObject *_lock;
    NSString *_originalUserHandle;
    JDLFeedActionManager *_actionManager;
    JDLBaseFeedDataSource *_dataSource;
}

@property(nonatomic) _Bool parentPostIsMyJodel; // @synthesize parentPostIsMyJodel=_parentPostIsMyJodel;
@property(retain, nonatomic) JDLBaseFeedDataSource *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) JDLFeedActionManager *actionManager; // @synthesize actionManager=_actionManager;
@property(copy, nonatomic) NSString *originalUserHandle; // @synthesize originalUserHandle=_originalUserHandle;
@property(retain, nonatomic) NSObject *lock; // @synthesize lock=_lock;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(copy, nonatomic) NSString *previousPageOffset; // @synthesize previousPageOffset=_previousPageOffset;
@property(copy, nonatomic) NSString *nextPageOffset; // @synthesize nextPageOffset=_nextPageOffset;
@property(nonatomic) _Bool shouldShowLinks; // @synthesize shouldShowLinks=_shouldShowLinks;
@property(copy, nonatomic) NSString *hashtag; // @synthesize hashtag=_hashtag;
@property(copy, nonatomic) NSString *channel; // @synthesize channel=_channel;
@property(nonatomic) _Bool shouldScrollToBottom; // @synthesize shouldScrollToBottom=_shouldScrollToBottom;
@property(nonatomic) _Bool hideReplyButton; // @synthesize hideReplyButton=_hideReplyButton;
@property(nonatomic) _Bool postPinningEnabled; // @synthesize postPinningEnabled=_postPinningEnabled;
@property(nonatomic) _Bool isPostPinned; // @synthesize isPostPinned=_isPostPinned;
@property(copy, nonatomic) NSString *pinCountFormattedValue; // @synthesize pinCountFormattedValue=_pinCountFormattedValue;
@property(readonly, nonatomic) UIColor *postColor; // @synthesize postColor=_postColor;
@property(copy, nonatomic) NSString *originalPostId; // @synthesize originalPostId=_originalPostId;
@property(readonly, nonatomic) RACSignal *errorMessages; // @synthesize errorMessages=_errorMessages;
@property(readonly, nonatomic) RACSignal *deleteSubfeedSignal; // @synthesize deleteSubfeedSignal=_deleteSubfeedSignal;
@property(readonly, nonatomic) RACSignal *cellIndexPathDeleteSignal; // @synthesize cellIndexPathDeleteSignal=_cellIndexPathDeleteSignal;
@property(nonatomic) long long feedOrder; // @synthesize feedOrder=_feedOrder;
@property(nonatomic) long long feedType; // @synthesize feedType=_feedType;
- (void).cxx_destruct;
- (_Bool)isPossibleToFetchMore;
- (_Bool)shouldFetchInitialDataAfterScrollToTop;
- (void)loadMoreReversed:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)tryToLoadPreviousPageWithCompletion:(CDUnknownBlockType)arg1;
- (void)tryToLoadNextPageWithCompletion:(CDUnknownBlockType)arg1;
- (void)refreshViewModels;
- (void)refreshBasePostCellViewModel:(id)arg1;
- (void)followCurrentChannelWithCompletion:(CDUnknownBlockType)arg1;
- (_Bool)isSubfeedForUnfollowedChannel;
@property(readonly, nonatomic) _Bool shouldShowPinButton;
- (void)refreshPinStateWithPinCount:(id)arg1 pinned:(_Bool)arg2 notify:(_Bool)arg3;
- (void)pinPostWithCompletion:(CDUnknownBlockType)arg1;
- (void)unpinPostWithCompletion:(CDUnknownBlockType)arg1;
- (void)signalErrorMessage:(id)arg1;
- (void)voteForPostCellViewModel:(id)arg1 upvote:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)giveThanksForPostCellViewModel:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)shouldShowThankAJodlerForUpvotedPost:(id)arg1;
- (void)openChannelForPostCellViewModel:(id)arg1 channel:(id)arg2;
- (void)openHashtagForPostCellViewModel:(id)arg1 hashtag:(id)arg2;
- (void)openPostForPostCellViewModel:(id)arg1;
- (void)showPostActionsForPostCellViewModel:(id)arg1;
- (_Bool)shouldShowMarkOPForPost:(id)arg1;
- (id)buildCellViewModelForPost:(id)arg1;
- (id)cellsForPosts:(id)arg1;
- (_Bool)isFirstPost:(id)arg1;
- (void)deleteSubfeed;
- (void)deleteCellViewModel:(id)arg1;
- (id)indexPathOfCellViewModel:(id)arg1;
- (void)bottomPullToRefresh:(CDUnknownBlockType)arg1;
- (void)pullToRefresh:(CDUnknownBlockType)arg1;
- (void)fetchInitialDataInReversedOrder:(_Bool)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)refreshParentPostIsMyJodelForPosts:(id)arg1;
- (void)removeAllCells;
- (void)removeCellAtIndexPath:(id)arg1;
- (id)cellViewModelAtIndexPath:(id)arg1;
- (unsigned long long)numberOfRowsInSection:(long long)arg1;
- (id)ancestorPostForReply;
- (id)initWithPostId:(id)arg1 postColor:(id)arg2 feedType:(long long)arg3 feedOrder:(long long)arg4;
- (id)initWithPost:(id)arg1 feedType:(long long)arg2 feedOrder:(long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

