//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITabBarController.h"

@class JDLTabBarViewModel;

@interface JDLTabBarController : UITabBarController
{
    JDLTabBarViewModel *_viewModel;
}

@property(retain, nonatomic) JDLTabBarViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
- (void)setSelectedViewController:(id)arg1;
- (void)tabBar:(id)arg1 didSelectItem:(id)arg2;
- (void)selectMainFeedTab;
- (void)refreshChannelsAnimated:(_Bool)arg1;
- (unsigned long long)getViewControllerIndexForClass:(Class)arg1;
- (void)refreshChannelsBadge;
- (void)refreshMeTabBadge;
- (void)refreshBadges;
- (void)moderationTasksUpdateNotification:(id)arg1;
- (void)tryToShowUserProfilingScreen;
- (void)dealloc;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

@end

