//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface JDLTabBarViewModel : NSObject
{
    _Bool _didTapOnLastChannelsNotification;
    NSArray *_lastChannelsWithNotifications;
}

@property(nonatomic) _Bool didTapOnLastChannelsNotification; // @synthesize didTapOnLastChannelsNotification=_didTapOnLastChannelsNotification;
@property(retain, nonatomic) NSArray *lastChannelsWithNotifications; // @synthesize lastChannelsWithNotifications=_lastChannelsWithNotifications;
- (void).cxx_destruct;
- (_Bool)hasNewNotifications:(id)arg1;
- (void)didChangeHomeStatus;
- (void)didTapChannelsTab;
- (_Bool)calculateShowChannelsBadgeForTabVisible:(_Bool)arg1;
- (id)init;
- (void)dealloc;

@end

