//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JDLUserService : NSObject
{
    _Bool _userCurrentlySwitchedToHometown;
    double _lastSucceededFetchConfigTime;
}

+ (id)userProfileTypeNameForType:(long long)arg1;
+ (id)sharedInstance;
@property(nonatomic) double lastSucceededFetchConfigTime; // @synthesize lastSucceededFetchConfigTime=_lastSucceededFetchConfigTime;
@property(nonatomic) _Bool userCurrentlySwitchedToHometown; // @synthesize userCurrentlySwitchedToHometown=_userCurrentlySwitchedToHometown;
- (_Bool)shouldAskForUserProfiling;
- (void)sendUserProfile:(long long)arg1;
- (void)trackConfigSkipWithReason:(id)arg1;
- (void)wipeUserDataAndStorage;
- (void)refreshAccessTokenWithSourceIdentifier:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)sendPushToken:(id)arg1;
- (void)fetchKarma;
- (void)checkDistinctId;
- (void)fetchUserConfig;
- (void)onApplicationDidBecomeActiveNotification:(id)arg1;
- (id)init;

@end

