//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSUserDefaults;

@interface JDLVotingReasonsService : NSObject
{
    NSUserDefaults *_defaults;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSUserDefaults *defaults; // @synthesize defaults=_defaults;
- (void).cxx_destruct;
- (id)subjectNameForUpvote:(_Bool)arg1;
- (id)numberForVotingReson:(id)arg1;
- (double)probability;
- (long long)timePeriod;
- (id)votingReasonsForUpvote:(_Bool)arg1;
- (void)showUpvotingReasonsForUpvote:(_Bool)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (id)viewToPresentFrom;
- (_Bool)randomBoolWithYesPercentage:(double)arg1;
- (_Bool)setLastQuestionDate;
- (id)dateOfLastQuestion;
- (_Bool)shouldAskForVotingReason;
- (_Bool)fitsTimeframe;
- (void)votePostWithId:(id)arg1 withUpvote:(_Bool)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)init;

@end

