//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (JDLBaseFeedTracking)
- (_Bool)isRootFeedType:(long long)arg1;
- (void)trackSortingChangeFeedType:(long long)arg1 feedOrder:(long long)arg2;
- (void)trackVoteForPost:(id)arg1 upvote:(_Bool)arg2 isMainSubfeedPost:(_Bool)arg3 feedType:(long long)arg4 feedOrder:(long long)arg5;
- (void)trackClientActivityLoadMoreFeedType:(long long)arg1 feedOrder:(long long)arg2;
- (void)trackPullToRefreshSucceededFeedType:(long long)arg1 feedOrder:(long long)arg2;
- (void)trackPullToRefreshActionContentName:(id)arg1 feedType:(long long)arg2 feedOrder:(long long)arg3;
@end

