//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, UIViewController;

@protocol RLTAnalyticsVCModuleControllerWrapperProtocol <NSObject>
@property(readonly, nonatomic) NSArray *parentViewControllerChildViewControllers;
@property(readonly, nonatomic) NSArray *childViewControllers;
@property(readonly, nonatomic) UIViewController *presentingViewController;
@property(readonly, nonatomic) UIViewController *presentedViewController;
@property(readonly, nonatomic) UIViewController *parentViewController;
@property(readonly, nonatomic) UIViewController *instance;
@end

