//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIViewController;

@protocol RLTAnalyticsButtonsModuleDelegate <NSObject>
- (void)buttonsModule:(id <RLTAnalyticsModuleProtocol>)arg1 buttonTap:(id)arg2 withType:(long long)arg3 withLabel:(NSString *)arg4 onViewController:(UIViewController *)arg5;
@end

