//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RLTAnalyticsModule.h"

#import "RLTAnalyticsApplicationSessionModuleProtocol.h"

@class NSDictionary, NSNumber, NSString;

@interface RLTAnalyticsApplicationSessionModule : RLTAnalyticsModule <RLTAnalyticsApplicationSessionModuleProtocol>
{
    _Bool _moduleStartHandled;
    _Bool _wasInBackground;
    id <RLTAnalyticsApplicationSessionModuleConfigProtocol> _config;
    id <RLTAnalyticsApplicationSessionModuleDelegate> _delegate;
    NSString *_archiveFilePath;
    NSDictionary *_appVersionDataDictionary;
    NSNumber *_didEnterBackgroundTime;
    NSNumber *_didBecomeActiveTime;
}

@property(retain, nonatomic) NSNumber *didBecomeActiveTime; // @synthesize didBecomeActiveTime=_didBecomeActiveTime;
@property(retain, nonatomic) NSNumber *didEnterBackgroundTime; // @synthesize didEnterBackgroundTime=_didEnterBackgroundTime;
@property(nonatomic) _Bool wasInBackground; // @synthesize wasInBackground=_wasInBackground;
@property(retain, nonatomic) NSDictionary *appVersionDataDictionary; // @synthesize appVersionDataDictionary=_appVersionDataDictionary;
@property(retain, nonatomic) NSString *archiveFilePath; // @synthesize archiveFilePath=_archiveFilePath;
@property(nonatomic) _Bool moduleStartHandled; // @synthesize moduleStartHandled=_moduleStartHandled;
@property(retain, nonatomic) id <RLTAnalyticsApplicationSessionModuleDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) id <RLTAnalyticsApplicationSessionModuleConfigProtocol> config; // @synthesize config=_config;
- (void).cxx_destruct;
- (void)setupArchiveFolder;
- (void)saveAppVersionDataDictionary;
- (id)previousAppVersion;
- (id)previousAppVersionUniqueIdentifier;
- (id)currentAppVersionUniqueIdentifier;
- (void)handleModuleStart;
- (void)onUIApplicationDidEnterBackgroundNotification:(id)arg1;
- (void)onUIApplicationDidBecomeActiveNotification:(id)arg1;
- (void)subscribe;
- (_Bool)startModule:(id *)arg1;
- (void)dealloc;
- (id)initWithConfig:(id)arg1 delegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

