//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RLTAnalyticsBModuleUIControlWrapper.h"

@class NSString;

@interface RLTAnalyticsBModuleButtonWrapper : RLTAnalyticsBModuleUIControlWrapper
{
}

- (id)findBarButtomItemInArrayOfUIBarButtonItems:(id)arg1 thatMatchesFrame:(struct CGRect)arg2;
- (id)getNavBarLabel:(id)arg1;
- (id)getLabelFromUIButton:(id)arg1;
- (id)initWithUIButton:(id)arg1;

// Remaining properties
@property(copy, nonatomic) NSString *label; // @dynamic label;

@end

