//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RLTAnalyticsModuleProtocol.h"

@protocol RLTAnalyticsViewControllersModuleProtocol <RLTAnalyticsModuleProtocol>
- (void)handleHookViewDidDisappear:(id <RLTAnalyticsVCModuleControllerWrapperProtocol>)arg1;
- (void)handleHookViewWillDisappear:(id <RLTAnalyticsVCModuleControllerWrapperProtocol>)arg1;
- (void)handleHookViewDidAppear:(id <RLTAnalyticsVCModuleControllerWrapperProtocol>)arg1;
- (void)handleHookViewWillAppear:(id <RLTAnalyticsVCModuleControllerWrapperProtocol>)arg1;
@end

