//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RLTAnalyticsModuleProtocol.h"

@class NSString;

@interface RLTAnalyticsModule : NSObject <RLTAnalyticsModuleProtocol>
{
    id <RLTAnalyticsModuleManagerProtocol> _moduleManager;
    long long _state;
    long long _type;
}

@property(nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic) long long state; // @synthesize state=_state;
@property(retain, nonatomic) id <RLTAnalyticsModuleManagerProtocol> moduleManager; // @synthesize moduleManager=_moduleManager;
- (void).cxx_destruct;
- (void)messageReceived:(id)arg1 ofType:(id)arg2;
- (_Bool)stopModule:(id *)arg1;
- (_Bool)startModule:(id *)arg1;
- (long long)moduleType;
- (long long)moduleState;
- (id)init;
- (id)initWithType:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

