//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class RLTAnalyticsRegistry;

@interface RLTAnalytics : NSObject
{
    RLTAnalyticsRegistry *_analyticsRegistry;
    id <RLTAnalyticsConfigurationProtocol> _configuration;
}

@property(retain, nonatomic) id <RLTAnalyticsConfigurationProtocol> configuration; // @synthesize configuration=_configuration;
@property(retain, nonatomic) RLTAnalyticsRegistry *analyticsRegistry; // @synthesize analyticsRegistry=_analyticsRegistry;
- (void).cxx_destruct;
- (void)createAndRegisterModules;
- (void)checkState;
@property(readonly, nonatomic) long long applicationColdStartType;
- (id)initWithConfiguration:(id)arg1;

@end

