//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol RLTAnalyticsModuleProtocol <NSObject>
- (void)setModuleManager:(id <RLTAnalyticsModuleManagerProtocol>)arg1;
- (void)messageReceived:(id)arg1 ofType:(id)arg2;
- (_Bool)stopModule:(id *)arg1;
- (_Bool)startModule:(id *)arg1;
- (long long)moduleType;
- (long long)moduleState;
@end

