//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RLTAnalyticsVCModuleControllerWrapperProtocol.h"

@class NSArray, NSString, UIViewController;

@interface RLTAnalyticsVCModuleControllerWrapper : NSObject <RLTAnalyticsVCModuleControllerWrapperProtocol>
{
    UIViewController *_instance;
    UIViewController *_parentViewController;
    UIViewController *_presentedViewController;
    UIViewController *_presentingViewController;
    NSArray *_childViewControllers;
    NSArray *_parentViewControllerChildViewControllers;
}

@property(retain, nonatomic) NSArray *parentViewControllerChildViewControllers; // @synthesize parentViewControllerChildViewControllers=_parentViewControllerChildViewControllers;
@property(retain, nonatomic) NSArray *childViewControllers; // @synthesize childViewControllers=_childViewControllers;
@property(retain, nonatomic) UIViewController *presentingViewController; // @synthesize presentingViewController=_presentingViewController;
@property(retain, nonatomic) UIViewController *presentedViewController; // @synthesize presentedViewController=_presentedViewController;
@property(retain, nonatomic) UIViewController *parentViewController; // @synthesize parentViewController=_parentViewController;
@property(retain, nonatomic) UIViewController *instance; // @synthesize instance=_instance;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (id)initWithInstance:(id)arg1 parentViewController:(id)arg2 presentedViewController:(id)arg3 presentingViewController:(id)arg4 childViewControllers:(id)arg5 parentViewControllerChildViewControllers:(id)arg6;
- (id)initWithInstance:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

