//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RLTAnalyticsModule.h"

@interface RLTAnalyticsPermanentSwizzlingModule : RLTAnalyticsModule
{
    id <RLTAnalyticsPermanentSwizzlingModuleDelegate> _swizzleDelegate;
}

@property(retain, nonatomic) id <RLTAnalyticsPermanentSwizzlingModuleDelegate> swizzleDelegate; // @synthesize swizzleDelegate=_swizzleDelegate;
- (void).cxx_destruct;
- (_Bool)startModule:(id *)arg1;

@end

