//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSNumberFormatter, RLTConfigAppStateHookService;

@interface RLTConfig : NSObject
{
    NSDictionary *_config;
    id <RLTConfigControllerProtocol> _controller;
    RLTConfigAppStateHookService *_taskPerformer;
    NSObject *_configLock;
    NSNumberFormatter *_numberFormatter;
}

+ (id)sharedInstance;
+ (id)startWithConfiguration:(id)arg1;
+ (id)startWithServerURLString:(id)arg1;
@property(retain, nonatomic) NSNumberFormatter *numberFormatter; // @synthesize numberFormatter=_numberFormatter;
@property(retain, nonatomic) NSObject *configLock; // @synthesize configLock=_configLock;
@property(retain, nonatomic) RLTConfigAppStateHookService *taskPerformer; // @synthesize taskPerformer=_taskPerformer;
@property(retain, nonatomic) id <RLTConfigControllerProtocol> controller; // @synthesize controller=_controller;
@property(retain, nonatomic) NSDictionary *config; // @synthesize config=_config;
- (void).cxx_destruct;
- (void)fetchAsync;
- (void)setupAutomaticFetch;
- (void)setupNumberFormatter;
- (id)numberForKey:(id)arg1;
- (id)fullConfig;
- (id)objectForKeyedSubscript:(id)arg1;
- (id)objectForKey:(id)arg1;
- (id)arrayForKey:(id)arg1 defaultValue:(id)arg2;
- (id)arrayForKey:(id)arg1;
- (id)dictionaryForKey:(id)arg1 defaultValue:(id)arg2;
- (id)dictionaryForKey:(id)arg1;
- (float)floatForKey:(id)arg1 defaultValue:(float)arg2 min:(float)arg3 max:(float)arg4;
- (float)floatForKey:(id)arg1 defaultValue:(float)arg2;
- (float)floatForKey:(id)arg1;
- (long long)integerForKey:(id)arg1 defaultValue:(long long)arg2 min:(long long)arg3 max:(long long)arg4;
- (long long)integerForKey:(id)arg1 defaultValue:(long long)arg2;
- (long long)integerForKey:(id)arg1;
- (_Bool)boolForKey:(id)arg1 defaultValue:(_Bool)arg2;
- (_Bool)boolForKey:(id)arg1;
- (id)stringForKey:(id)arg1 defaultValue:(id)arg2;
- (id)stringForKey:(id)arg1;
- (id)initWithConfigController:(id)arg1;
- (id)initWithConfiguration:(id)arg1;
- (id)localizedStringFromDictionaryWithKey:(id)arg1 defaultValue:(id)arg2;
- (id)localizedURLFromDictionaryWithKey:(id)arg1 defaultValue:(id)arg2;

@end

