//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface RLTConfigAppVersionCheck : NSObject
{
    _Bool _versionChanged;
}

+ (_Bool)isAppVersionUpdated;
+ (id)sharedInstance;
@property(nonatomic) _Bool versionChanged; // @synthesize versionChanged=_versionChanged;
- (id)appVersionWithBuildVersion;
- (void)setupVersionCheck;
- (id)init;

@end

