//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURLSession;

@interface RLTLocalizationConfiguration : NSObject
{
    NSString *_serverURLString;
    NSURLSession *_URLSession;
    double _timeoutInterval;
    NSString *_defaultLanguageISOCode;
    id <RLTLocalizationDelegate> _delegate;
}

@property(nonatomic) __weak id <RLTLocalizationDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *defaultLanguageISOCode; // @synthesize defaultLanguageISOCode=_defaultLanguageISOCode;
@property(nonatomic) double timeoutInterval; // @synthesize timeoutInterval=_timeoutInterval;
@property(retain, nonatomic) NSURLSession *URLSession; // @synthesize URLSession=_URLSession;
@property(copy, nonatomic) NSString *serverURLString; // @synthesize serverURLString=_serverURLString;
- (void).cxx_destruct;
- (id)initWithServerURLString:(id)arg1;

@end

