//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class RLTLocalizationConfiguration, RLTLocalizationLocaleProvider, RLTLocalizationParser, RLTLocalizationRestManager, RLTLocalizationStorage;

@interface RLTLocalizationController : NSObject
{
    RLTLocalizationRestManager *_fetchService;
    RLTLocalizationStorage *_storage;
    RLTLocalizationConfiguration *_configuration;
    RLTLocalizationLocaleProvider *_localeProvider;
    RLTLocalizationParser *_parser;
}

@property(retain, nonatomic) RLTLocalizationParser *parser; // @synthesize parser=_parser;
@property(retain, nonatomic) RLTLocalizationLocaleProvider *localeProvider; // @synthesize localeProvider=_localeProvider;
@property(retain, nonatomic) RLTLocalizationConfiguration *configuration; // @synthesize configuration=_configuration;
@property(retain, nonatomic) RLTLocalizationStorage *storage; // @synthesize storage=_storage;
@property(retain, nonatomic) RLTLocalizationRestManager *fetchService; // @synthesize fetchService=_fetchService;
- (void).cxx_destruct;
- (id)currentLanguageWithFallback;
- (id)currentStoredLanguageKey;
- (void)resetSavedLanguage;
- (void)saveCurrentLanguage;
- (_Bool)isCurrentLanguageChanged;
- (id)storedCurrentLanguage;
- (id)updateIdKey;
- (void)resetUpdateId;
- (void)setCurrentUpdateId:(id)arg1;
- (id)getCurrentUpdateId;
- (void)fetchAsync:(CDUnknownBlockType)arg1;
- (void)updateLanguage:(id)arg1 updateId:(id)arg2 dictionary:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (id)currentLanguageLocalization;
- (void)fullReset;
- (id)initWithConfiguration:(id)arg1 storage:(id)arg2 fetchService:(id)arg3 parser:(id)arg4 localeProvider:(id)arg5;
- (id)initWithConfiguration:(id)arg1;

@end

