//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSFileManager, NSMutableSet, NSString, RLTLocalizationConfiguration, RLTLocalizationLocaleProvider;

@interface RLTLocalizationStorage : NSObject
{
    NSFileManager *_fileManager;
    RLTLocalizationConfiguration *_configuration;
    RLTLocalizationLocaleProvider *_localeProvider;
    NSMutableSet *_supportedLanguagesCodes;
    NSObject *_lock;
    NSString *_storagePath;
}

@property(copy, nonatomic) NSString *storagePath; // @synthesize storagePath=_storagePath;
@property(retain, nonatomic) NSObject *lock; // @synthesize lock=_lock;
@property(retain, nonatomic) NSMutableSet *supportedLanguagesCodes; // @synthesize supportedLanguagesCodes=_supportedLanguagesCodes;
@property(retain, nonatomic) RLTLocalizationLocaleProvider *localeProvider; // @synthesize localeProvider=_localeProvider;
@property(retain, nonatomic) RLTLocalizationConfiguration *configuration; // @synthesize configuration=_configuration;
@property(retain, nonatomic) NSFileManager *fileManager; // @synthesize fileManager=_fileManager;
- (void).cxx_destruct;
- (id)lprojFileType;
- (id)dirPathForLanguage:(id)arg1;
- (id)filePathForLanguage:(id)arg1;
- (id)getDirNamesInDir:(id)arg1;
- (void)scanForSupportedLanguages;
- (id)normalizeLanguageCode:(id)arg1;
- (void)updateLanguage:(id)arg1 withDictionary:(id)arg2;
- (void)addSupportedLanguage:(id)arg1;
- (id)supportedLanguages;
- (void)saveData:(id)arg1 language:(id)arg2;
- (id)dictionaryForLanguage:(id)arg1;
- (void)appendLanguageValuesFromFile:(id)arg1 toFile:(id)arg2;
- (void)refreshStringsFromBundle;
- (void)reset;
- (void)setup;
- (id)initWithConfiguration:(id)arg1 localeProvider:(id)arg2;

@end

