//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, NSString, NSURLComponents, RLTStatsConfiguration, RLTStatsSerializer;

@interface RLTStatsDispatcher : NSObject
{
    id <RLTStatsDispatcherDelegate> _delegate;
    NSString *_serverHost;
    unsigned long long _serverPort;
    RLTStatsSerializer *_serializer;
    RLTStatsConfiguration *_configuration;
    NSURLComponents *_urlComponents;
    NSObject<OS_dispatch_queue> *_bgQueue;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *bgQueue; // @synthesize bgQueue=_bgQueue;
@property(retain, nonatomic) NSURLComponents *urlComponents; // @synthesize urlComponents=_urlComponents;
@property(retain, nonatomic) RLTStatsConfiguration *configuration; // @synthesize configuration=_configuration;
@property(retain, nonatomic) RLTStatsSerializer *serializer; // @synthesize serializer=_serializer;
@property(nonatomic) unsigned long long serverPort; // @synthesize serverPort=_serverPort;
@property(copy, nonatomic) NSString *serverHost; // @synthesize serverHost=_serverHost;
@property(nonatomic) __weak id <RLTStatsDispatcherDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)buildURL;
- (void)sendObject:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)initWithSerializer:(id)arg1 serverHost:(id)arg2 serverPort:(unsigned long long)arg3 configuration:(id)arg4;

@end

