//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class RLTStatsConfiguration;

@interface RLTStatsSerializer : NSObject
{
    id <RLTStatsSerializerDelegate> _delegate;
    RLTStatsConfiguration *_configuration;
    long long _version;
}

@property(nonatomic) long long version; // @synthesize version=_version;
@property(retain, nonatomic) RLTStatsConfiguration *configuration; // @synthesize configuration=_configuration;
@property(nonatomic) __weak id <RLTStatsSerializerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (long long)serializerVersion;
- (id)serializeObject:(id)arg1;
- (id)initWithConfiguration:(id)arg1 version:(long long)arg2;

@end

