//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RLTStatsDispatchObject.h"

@class NSArray, NSString;

@interface RLTStatsChunk : NSObject <RLTStatsDispatchObject>
{
    NSArray *_events;
    NSArray *_activities;
}

@property(copy, nonatomic) NSArray *activities; // @synthesize activities=_activities;
@property(copy, nonatomic) NSArray *events; // @synthesize events=_events;
- (void).cxx_destruct;
- (id)dictionaryRepresentationWithConfiguration:(id)arg1;
- (id)initWithEvents:(id)arg1 activities:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

