//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSDictionary;

@protocol RLTStatsSerializerDelegate <NSObject>

@optional
- (void)serializer:(id)arg1 didSerializeObjectIntoRawData:(NSData *)arg2;
- (void)serializer:(id)arg1 willSerializeDictionary:(NSDictionary *)arg2;
@end

