//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface RLTStatsDeviceInfo : NSObject
{
}

+ (id)deviceModelDataForMachineIDs;
+ (id)deviceVendorIdentifier;
+ (id)appStoreReceiptURLLastPathComponent;
+ (id)countryISOCode;
+ (id)deviceHWMachine;
+ (id)appName;
+ (id)deviceModel;
+ (id)deviceGeneration;
+ (id)appVersionWithBuildVersion;
+ (id)appBuildVersion;
+ (id)appVersion;
+ (id)bundleIdentifier;
+ (id)systemVersion;
+ (double)systemUptime;
+ (id)deviceInfoDictionary;

@end

