//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface RLTStatsUtils : NSObject
{
}

+ (id)getKeyBasedOnInterval:(id)arg1 intervals:(id)arg2 number:(int)arg3;

@end

