//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>, RLTStatsDispatcher;

@interface RLTStatsCollector : NSObject
{
    id <RLTStatsCollectorDelegate> _delegate;
    RLTStatsDispatcher *_dispatcher;
    NSMutableDictionary *_eventsByEventName;
    NSMutableArray *_activities;
    NSObject *_lock;
    NSObject<OS_dispatch_queue> *_bgQueue;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *bgQueue; // @synthesize bgQueue=_bgQueue;
@property(retain, nonatomic) NSObject *lock; // @synthesize lock=_lock;
@property(retain, nonatomic) NSMutableArray *activities; // @synthesize activities=_activities;
@property(retain, nonatomic) NSMutableDictionary *eventsByEventName; // @synthesize eventsByEventName=_eventsByEventName;
@property(retain, nonatomic) RLTStatsDispatcher *dispatcher; // @synthesize dispatcher=_dispatcher;
@property(nonatomic) __weak id <RLTStatsCollectorDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)flushStatistics;
- (id)buildEventWithName:(id)arg1 withAttributes:(id)arg2 withStatus:(long long)arg3 duration:(unsigned long long)arg4;
- (void)addActivity:(id)arg1;
- (void)addEvent:(id)arg1;
- (void)flush;
- (void)trackActivity:(id)arg1 type:(id)arg2 subtype:(id)arg3;
- (void)trackEvent:(id)arg1 attributes:(id)arg2 status:(long long)arg3 duration:(unsigned long long)arg4;
- (id)initWithDispatcher:(id)arg1;

@end

