//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SWGObject.h"

@class NSNumber;

@interface SWGCoordinates : SWGObject
{
    NSNumber *_lat;
    NSNumber *_lng;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
@property(retain, nonatomic) NSNumber *lng; // @synthesize lng=_lng;
@property(retain, nonatomic) NSNumber *lat; // @synthesize lat=_lat;
- (void).cxx_destruct;
- (id)init;

@end

