//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SWGObject.h"

@class NSArray<SWGPost>, NSNumber;

@interface SWGChannelComboPosts : SWGObject
{
    NSArray<SWGPost> *_recent;
    NSArray<SWGPost> *_replied;
    NSArray<SWGPost> *_voted;
    NSNumber *_sponsored;
    NSNumber *_max;
    NSNumber *_followersCount;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
@property(retain, nonatomic) NSNumber *followersCount; // @synthesize followersCount=_followersCount;
@property(retain, nonatomic) NSNumber *max; // @synthesize max=_max;
@property(retain, nonatomic) NSNumber *sponsored; // @synthesize sponsored=_sponsored;
@property(retain, nonatomic) NSArray<SWGPost> *voted; // @synthesize voted=_voted;
@property(retain, nonatomic) NSArray<SWGPost> *replied; // @synthesize replied=_replied;
@property(retain, nonatomic) NSArray<SWGPost> *recent; // @synthesize recent=_recent;
- (void).cxx_destruct;
- (id)init;

@end

