//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SWGObject.h"

@class NSArray<SWGChannelMeta>;

@interface SWGChannelsMeta : SWGObject
{
    NSArray<SWGChannelMeta> *_channels;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
@property(retain, nonatomic) NSArray<SWGChannelMeta> *channels; // @synthesize channels=_channels;
- (void).cxx_destruct;
- (id)init;

@end

