//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SWGObject.h"

@class NSString, SWGLocationMin;

@interface SWGCredentials : SWGObject
{
    NSString *_clientId;
    NSString *_deviceUid;
    SWGLocationMin *_location;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
+ (id)storedUser;
@property(retain, nonatomic) SWGLocationMin *location; // @synthesize location=_location;
@property(retain, nonatomic) NSString *deviceUid; // @synthesize deviceUid=_deviceUid;
@property(retain, nonatomic) NSString *clientId; // @synthesize clientId=_clientId;
- (void).cxx_destruct;
- (id)init;

@end

