//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableDictionary, NSString, SWGApiClient, SWGLogger;

@interface SWGConfiguration : NSObject
{
    _Bool _verifySSL;
    SWGLogger *_logger;
    SWGApiClient *_apiClient;
    NSString *_host;
    NSString *_username;
    NSString *_password;
    NSString *_accessToken;
    NSString *_tempFolderPath;
    NSString *_sslCaCert;
    NSMutableDictionary *_mutableDefaultHeaders;
    NSMutableDictionary *_mutableApiKey;
    NSMutableDictionary *_mutableApiKeyPrefix;
}

+ (id)sharedConfig;
@property(retain, nonatomic) NSMutableDictionary *mutableApiKeyPrefix; // @synthesize mutableApiKeyPrefix=_mutableApiKeyPrefix;
@property(retain, nonatomic) NSMutableDictionary *mutableApiKey; // @synthesize mutableApiKey=_mutableApiKey;
@property(retain, nonatomic) NSMutableDictionary *mutableDefaultHeaders; // @synthesize mutableDefaultHeaders=_mutableDefaultHeaders;
@property(retain, nonatomic) NSString *sslCaCert; // @synthesize sslCaCert=_sslCaCert;
@property(nonatomic) _Bool verifySSL; // @synthesize verifySSL=_verifySSL;
@property(retain, nonatomic) NSString *tempFolderPath; // @synthesize tempFolderPath=_tempFolderPath;
@property(retain, nonatomic) NSString *accessToken; // @synthesize accessToken=_accessToken;
@property(retain, nonatomic) NSString *password; // @synthesize password=_password;
@property(retain, nonatomic) NSString *username; // @synthesize username=_username;
@property(retain, nonatomic) NSString *host; // @synthesize host=_host;
@property(retain, nonatomic) SWGApiClient *apiClient; // @synthesize apiClient=_apiClient;
@property(retain, nonatomic) SWGLogger *logger; // @synthesize logger=_logger;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSDictionary *defaultHeaders;
- (id)defaultHeaderForKey:(id)arg1;
- (void)removeDefaultHeaderForKey:(id)arg1;
- (void)setDefaultHeaderValue:(id)arg1 forKey:(id)arg2;
@property(nonatomic) _Bool debug;
- (id)authSettings;
@property(readonly, nonatomic) NSDictionary *apiKeyPrefix;
@property(readonly, nonatomic) NSDictionary *apiKey;
- (void)removeApiKeyPrefix:(id)arg1;
- (void)setApiKeyPrefix:(id)arg1 forApiKeyPrefixIdentifier:(id)arg2;
- (void)removeApiKey:(id)arg1;
- (void)setApiKey:(id)arg1 forApiKeyIdentifier:(id)arg2;
- (id)getAccessToken;
- (id)getBasicAuthToken;
- (id)getApiKeyWithPrefix:(id)arg1;
- (id)init;

@end

