//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SWGObject.h"

@class NSString;

@interface SWGDistinctIdResponse : SWGObject
{
    NSString *_distinctId;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
@property(retain, nonatomic) NSString *distinctId; // @synthesize distinctId=_distinctId;
- (void).cxx_destruct;
- (id)init;

@end

