//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SWGObject.h"

@class NSNumber, NSString;

@interface SWGModerationPost : SWGObject
{
    NSString *_postId;
    NSString *_taskId;
    NSString *_message;
    NSNumber *_flagCount;
    NSNumber *_flagReason;
    NSNumber *_voteCount;
    NSString *_imageUrl;
    NSString *_thumbnailUrl;
    NSString *_color;
    NSString *_parentId;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
@property(retain, nonatomic) NSString *parentId; // @synthesize parentId=_parentId;
@property(retain, nonatomic) NSString *color; // @synthesize color=_color;
@property(retain, nonatomic) NSString *thumbnailUrl; // @synthesize thumbnailUrl=_thumbnailUrl;
@property(retain, nonatomic) NSString *imageUrl; // @synthesize imageUrl=_imageUrl;
@property(retain, nonatomic) NSNumber *voteCount; // @synthesize voteCount=_voteCount;
@property(retain, nonatomic) NSNumber *flagReason; // @synthesize flagReason=_flagReason;
@property(retain, nonatomic) NSNumber *flagCount; // @synthesize flagCount=_flagCount;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
@property(retain, nonatomic) NSString *taskId; // @synthesize taskId=_taskId;
@property(retain, nonatomic) NSString *postId; // @synthesize postId=_postId;
- (void).cxx_destruct;
- (id)init;
- (_Bool)containsImage;

@end

