//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SWGObject.h"

@class NSNumber, NSString, SWGLocation;

@interface SWGModerationResult : SWGObject
{
    NSString *_taskId;
    NSNumber *_decision;
    SWGLocation *_location;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
@property(retain, nonatomic) SWGLocation *location; // @synthesize location=_location;
@property(retain, nonatomic) NSNumber *decision; // @synthesize decision=_decision;
@property(retain, nonatomic) NSString *taskId; // @synthesize taskId=_taskId;
- (void).cxx_destruct;
- (id)init;

@end

