//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SWGObject.h"

@class SWGPost;

@interface SWGModerationPostsBounty : SWGObject
{
    SWGPost *_picturePost;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
@property(retain, nonatomic) SWGPost *picturePost; // @synthesize picturePost=_picturePost;
- (void).cxx_destruct;
- (id)init;

@end

