//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SWGApi.h"

@class NSMutableDictionary, NSString, SWGApiClient;

@interface SWGPostsApi : NSObject <SWGApi>
{
    SWGApiClient *_apiClient;
    NSMutableDictionary *_defaultHeaders;
}

+ (id)sharedAPI;
@property(retain, nonatomic) NSMutableDictionary *defaultHeaders; // @synthesize defaultHeaders=_defaultHeaders;
@property(nonatomic) SWGApiClient *apiClient; // @synthesize apiClient=_apiClient;
- (void).cxx_destruct;
- (id)upvoteStickypostWithId:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)upvotePostWithId:(id)arg1 body:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)unpinPostWithId:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)pinPostWithId:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)hidePostWithId:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)giveThanksWithId:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)getStandardFeedWithSkip:(id)arg1 limit:(id)arg2 home:(id)arg3 after:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (id)getPostDetailsWithId:(id)arg1 details:(id)arg2 reply:(id)arg3 reversed:(id)arg4 highlight:(id)arg5 completionHandler:(CDUnknownBlockType)arg6;
- (id)getPostByIdWithId:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)getPopularLocationFeedWithSkip:(id)arg1 limit:(id)arg2 home:(id)arg3 after:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (id)getPopularHashtagFeedWithHashtag:(id)arg1 home:(id)arg2 skip:(id)arg3 after:(id)arg4 limit:(id)arg5 completionHandler:(CDUnknownBlockType)arg6;
- (id)getPopularChannelFeedWithChannel:(id)arg1 home:(id)arg2 skip:(id)arg3 after:(id)arg4 limit:(id)arg5 completionHandler:(CDUnknownBlockType)arg6;
- (id)getMineVotesFeedWithSkip:(id)arg1 limit:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)getMineRepliesFeedWithSkip:(id)arg1 limit:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)getMinePopularFeedWithSkip:(id)arg1 limit:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)getMinePinnedFeedWithSkip:(id)arg1 limit:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)getMineFeedWithSkip:(id)arg1 limit:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)getMineDiscussedFeedWithSkip:(id)arg1 limit:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)getLocationFeedWithSkip:(id)arg1 limit:(id)arg2 home:(id)arg3 after:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (id)getHashtagFeedWithHashtag:(id)arg1 home:(id)arg2 skip:(id)arg3 after:(id)arg4 limit:(id)arg5 completionHandler:(CDUnknownBlockType)arg6;
- (id)getDiscussedLocationFeedWithSkip:(id)arg1 limit:(id)arg2 home:(id)arg3 after:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (id)getDiscussedHashtagFeedWithHashtag:(id)arg1 home:(id)arg2 skip:(id)arg3 after:(id)arg4 limit:(id)arg5 completionHandler:(CDUnknownBlockType)arg6;
- (id)getDiscussedChannelFeedWithChannel:(id)arg1 home:(id)arg2 skip:(id)arg3 after:(id)arg4 limit:(id)arg5 completionHandler:(CDUnknownBlockType)arg6;
- (id)getComboMineFeedWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)getComboLocationFeedWithStickiesWithHome:(id)arg1 stickies:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)getComboLocationFeedWithHome:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)getComboHashtagFeedWithHashtag:(id)arg1 home:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)getComboChannelFeedWithChannel:(id)arg1 home:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)getChannelFeedWithChannel:(id)arg1 home:(id)arg2 skip:(id)arg3 after:(id)arg4 limit:(id)arg5 completionHandler:(CDUnknownBlockType)arg6;
- (id)flagPostByIdWithId:(id)arg1 body:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)enableNotificationsWithId:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)downvoteStickypostWithId:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)downvotePostWithId:(id)arg1 body:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)dismissStickypostWithId:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)disableNotificationsWithId:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)deletePostWithId:(id)arg1 highlight:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)createPostWithCreatePostRequest:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)createNewPostWithBody:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (unsigned long long)requestQueueSize;
- (void)setDefaultHeaderValue:(id)arg1 forKey:(id)arg2;
- (void)addHeader:(id)arg1 forKey:(id)arg2;
- (id)defaultHeaderForKey:(id)arg1;
- (id)initWithApiClient:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

