//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface SWGQueryParamCollection : NSObject
{
    NSArray *_values;
    NSString *_format;
}

@property(readonly, nonatomic) NSString *format; // @synthesize format=_format;
@property(readonly, nonatomic) NSArray *values; // @synthesize values=_values;
- (void).cxx_destruct;
- (id)initWithValuesAndFormat:(id)arg1 format:(id)arg2;

@end

