//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SWGObject.h"

@class NSArray<SWGPost>, NSNumber;

@interface SWGRecentPosts : SWGObject
{
    NSArray<SWGPost> *_posts;
    NSNumber *_max;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
@property(retain, nonatomic) NSNumber *max; // @synthesize max=_max;
@property(retain, nonatomic) NSArray<SWGPost> *posts; // @synthesize posts=_posts;
- (void).cxx_destruct;
- (id)init;

@end

