//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SWGSanitizer.h"

@class NSRegularExpression, NSString;

@interface SWGSanitizer : NSObject <SWGSanitizer>
{
    NSRegularExpression *_jsonHeaderTypeExpression;
}

@property(retain, nonatomic) NSRegularExpression *jsonHeaderTypeExpression; // @synthesize jsonHeaderTypeExpression=_jsonHeaderTypeExpression;
- (void).cxx_destruct;
- (id)selectHeaderContentType:(id)arg1;
- (id)selectHeaderAccept:(id)arg1;
- (id)dateParameterToString:(id)arg1;
- (id)parameterToString:(id)arg1;
- (id)sanitizeForSerialization:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

