//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@protocol SWGSanitizer <NSObject>
- (NSString *)selectHeaderContentType:(NSArray *)arg1;
- (NSString *)selectHeaderAccept:(NSArray *)arg1;
- (NSString *)parameterToString:(id)arg1;
- (id)sanitizeForSerialization:(id)arg1;
@end

