//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SWGObject.h"

@class NSNumber, SWGVersionResponseFeatureConfig, SWGVersionResponseRefreshrate;

@interface SWGVersionResponse : SWGObject
{
    NSNumber *_minVersion;
    NSNumber *_currentVersion;
    SWGVersionResponseFeatureConfig *_featureConfig;
    SWGVersionResponseRefreshrate *_refreshrate;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
@property(retain, nonatomic) SWGVersionResponseRefreshrate *refreshrate; // @synthesize refreshrate=_refreshrate;
@property(retain, nonatomic) SWGVersionResponseFeatureConfig *featureConfig; // @synthesize featureConfig=_featureConfig;
@property(retain, nonatomic) NSNumber *currentVersion; // @synthesize currentVersion=_currentVersion;
@property(retain, nonatomic) NSNumber *minVersion; // @synthesize minVersion=_minVersion;
- (void).cxx_destruct;
- (id)init;

@end

