//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SWGObject.h"

@class NSNumber, SWGPost;

@interface SWGVoteCount : SWGObject
{
    NSNumber *_voteCount;
    SWGPost *_post;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
@property(retain, nonatomic) SWGPost *post; // @synthesize post=_post;
@property(retain, nonatomic) NSNumber *voteCount; // @synthesize voteCount=_voteCount;
- (void).cxx_destruct;
- (id)init;

@end

