//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVCaptureFileOutputRecordingDelegate.h"

@class AVCaptureMovieFileOutput, AVCaptureSession, NSString, NSURL;

@interface TLMAVCamRecorder : NSObject <AVCaptureFileOutputRecordingDelegate>
{
    _Bool _recordsVideo;
    _Bool _recordsAudio;
    AVCaptureSession *session;
    AVCaptureMovieFileOutput *movieFileOutput;
    NSURL *outputFileURL;
    id <NSObject><TLMAVCamRecorderDelegate> delegate;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
@property(readonly, nonatomic) _Bool recordsAudio; // @synthesize recordsAudio=_recordsAudio;
@property(readonly, nonatomic) _Bool recordsVideo; // @synthesize recordsVideo=_recordsVideo;
@property(nonatomic) id <NSObject><TLMAVCamRecorderDelegate> delegate; // @synthesize delegate;
@property(copy, nonatomic) NSURL *outputFileURL; // @synthesize outputFileURL;
@property(retain, nonatomic) AVCaptureMovieFileOutput *movieFileOutput; // @synthesize movieFileOutput;
@property(retain, nonatomic) AVCaptureSession *session; // @synthesize session;
- (void).cxx_destruct;
- (void)stopRecording;
- (void)startRecordingWithOrientation:(long long)arg1;
@property(readonly, nonatomic, getter=isRecording) _Bool recording;
- (id)initWithSession:(id)arg1 outputFileURL:(id)arg2;
- (void)captureOutput:(id)arg1 didFinishRecordingToOutputFileAtURL:(id)arg2 fromConnections:(id)arg3 error:(id)arg4;
- (void)captureOutput:(id)arg1 didStartRecordingToOutputFileAtURL:(id)arg2 fromConnections:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

