//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TLMComposeViewController;

@protocol TLMComposeViewControllerDelegate <NSObject>
- (void)composeControllerDidReceiveOpenCameraTap:(TLMComposeViewController *)arg1;
- (void)closedEULA;
- (void)openedEULA;
- (void)composeControllerDidPostJodel:(unsigned long long)arg1;
- (void)composeControllerDidCancel;
@end

