//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIDevice.h"

@interface UIDevice (JDLDeviceNiceNames)
- (id)JDL_DeviceNiceName;
- (id)JDL_deviceTypeLookupTable;
- (unsigned long long)JDL_deviceType;
- (id)JDL_deviceDescription;
@end

