//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIFont.h"

@interface UIFont (TLM)
+ (id)tlm_fontForAlbertoRegularWithSize:(double)arg1;
+ (id)tlm_fontForGothamBookWithSize:(double)arg1;
+ (id)tlm_fontForGothamBoldWithSize:(double)arg1;
@end

