//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSString;

@interface UIViewController (DBPrivacyHelper)
@property(retain, nonatomic) NSString *appIcon;
- (id)snapshot;
- (void)showPrivacyHelperForType:(unsigned long long)arg1 controller:(CDUnknownBlockType)arg2 didPresent:(CDUnknownBlockType)arg3 didDismiss:(CDUnknownBlockType)arg4 useDefaultSettingPane:(_Bool)arg5;
- (void)showPrivacyHelperForType:(unsigned long long)arg1;
@end

