//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (APToastStyle)
+ (_Bool)ap_toastTapToComplete;
+ (double)ap_toastDuration;
+ (long long)ap_toastMaxNumberOfLines;
+ (id)ap_toastFont;
+ (double)ap_toastOpacity;
+ (double)ap_toastCornerRadius;
+ (double)ap_toastMinHeight;
+ (double)ap_toastVerticalPadding;
+ (double)ap_toastHorizontalPadding;
+ (double)ap_toastMaxHeightPercent;
@end

