//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIWebViewDelegate.h"
#import "WKNavigationDelegate.h"

@class NSString, UIScrollView, UIWebView, WKWebView;

@interface WKUIWebView : UIView <UIWebViewDelegate, WKNavigationDelegate>
{
    id <WKUIWebViewDelegate> _delegate;
    UIWebView *_webView;
    WKWebView *_webViewWK;
}

+ (_Bool)requiresConstraintBasedLayout;
@property(retain, nonatomic) WKWebView *webViewWK; // @synthesize webViewWK=_webViewWK;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
@property(nonatomic) __weak id <WKUIWebViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (long long)mapWKNavigationTypeToYSWebViewNavigationType:(long long)arg1;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webView:(id)arg1 didStartProvisionalNavigation:(id)arg2;
- (long long)mapUIWebViewNavigationTypeToYSWebViewNavigationType:(long long)arg1;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (void)handleError:(id)arg1;
- (void)handleFinishLoad;
- (void)handleStartLoad;
- (void)evaluateJavaScriptFromString:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)stopLoading;
- (void)loadRequest:(id)arg1;
@property(readonly, nonatomic) __weak UIScrollView *scrollView;
- (void)dealloc;
- (void)setBackgroundColor:(id)arg1;
@property(nonatomic) _Bool suppressesIncrementalRendering;
- (void)setupWebView;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

