//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSTimer, UITapGestureRecognizer, UIView;

@interface APToast : NSObject
{
    _Bool _tapToComplete;
    long long _toastID;
    double _duration;
    UIView *_toastView;
    UIView *_parentView;
    id <APToastDelegate> _delegate;
    CDUnknownBlockType _completionBlock;
    NSTimer *_timeoutTimer;
    UITapGestureRecognizer *_tapGestureRecognizer;
}

+ (long long)getNextToastID;
@property(retain, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
@property(retain, nonatomic) NSTimer *timeoutTimer; // @synthesize timeoutTimer=_timeoutTimer;
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(nonatomic) __weak id <APToastDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak UIView *parentView; // @synthesize parentView=_parentView;
@property(retain, nonatomic) UIView *toastView; // @synthesize toastView=_toastView;
@property(nonatomic) _Bool tapToComplete; // @synthesize tapToComplete=_tapToComplete;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(nonatomic) long long toastID; // @synthesize toastID=_toastID;
- (void).cxx_destruct;
- (void)tapGestureRecognizerAction:(id)arg1;
- (void)timeoutTimerFired:(id)arg1;
- (_Bool)isStarted;
- (_Bool)isActive;
- (void)stopToasting;
- (void)addTapToCompleteIfNeeded;
- (void)startTimer;
- (void)dealloc;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isEqualToToast:(id)arg1;
- (id)init;

@end

