//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSObject.h"

@class NSString;

@interface BLKDelegateSplitter : NSObject <NSObject>
{
    id <NSObject> _firstDelegate;
    id <NSObject> _secondDelegate;
}

@property(nonatomic) __weak id <NSObject> secondDelegate; // @synthesize secondDelegate=_secondDelegate;
@property(nonatomic) __weak id <NSObject> firstDelegate; // @synthesize firstDelegate=_firstDelegate;
- (void).cxx_destruct;
- (_Bool)respondsToSelector:(SEL)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)forwardInvocation:(id)arg1;
- (id)initWithFirstDelegate:(id)arg1 secondDelegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

