//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIScrollViewDelegate.h"

@class BLKFlexibleHeightBar, NSMutableDictionary, NSString;

@interface BLKFlexibleHeightBarBehaviorDefiner : NSObject <UIScrollViewDelegate>
{
    _Bool _snappingEnabled;
    _Bool _currentlySnapping;
    _Bool _elasticMaximumHeightAtTop;
    BLKFlexibleHeightBar *_flexibleHeightBar;
    NSMutableDictionary *_snappingPositionsForProgressRanges;
}

@property(retain, nonatomic) NSMutableDictionary *snappingPositionsForProgressRanges; // @synthesize snappingPositionsForProgressRanges=_snappingPositionsForProgressRanges;
@property(nonatomic, getter=isElasticMaximumHeightAtTop) _Bool elasticMaximumHeightAtTop; // @synthesize elasticMaximumHeightAtTop=_elasticMaximumHeightAtTop;
@property(nonatomic, getter=isCurrentlySnapping) _Bool currentlySnapping; // @synthesize currentlySnapping=_currentlySnapping;
@property(nonatomic, getter=isSnappingEnabled) _Bool snappingEnabled; // @synthesize snappingEnabled=_snappingEnabled;
@property(readonly, nonatomic) __weak BLKFlexibleHeightBar *flexibleHeightBar; // @synthesize flexibleHeightBar=_flexibleHeightBar;
- (void).cxx_destruct;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)snapWithScrollView:(id)arg1;
- (void)snapToProgress:(double)arg1 scrollView:(id)arg2;
- (void)removeSnappingPositionProgressForProgressRangeStart:(double)arg1 end:(double)arg2;
- (void)addSnappingPositionProgress:(double)arg1 forProgressRangeStart:(double)arg2 end:(double)arg3;
- (void)BLK_Private_setFlexibleHeightBar:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

