//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BLKFlexibleHeightBarSubviewLayoutAttributes : NSObject
{
    _Bool _hidden;
    double _alpha;
    long long _zIndex;
    struct CGPoint _center;
    struct CGSize _size;
    struct CGRect _frame;
    struct CGRect _bounds;
    struct CGAffineTransform _transform;
    struct CATransform3D _transform3D;
}

@property(nonatomic, getter=isHidden) _Bool hidden; // @synthesize hidden=_hidden;
@property(nonatomic) long long zIndex; // @synthesize zIndex=_zIndex;
@property(nonatomic) double alpha; // @synthesize alpha=_alpha;
@property(nonatomic) struct CGAffineTransform transform; // @synthesize transform=_transform;
@property(nonatomic) struct CATransform3D transform3D; // @synthesize transform3D=_transform3D;
@property(nonatomic) struct CGSize size; // @synthesize size=_size;
@property(nonatomic) struct CGPoint center; // @synthesize center=_center;
@property(nonatomic) struct CGRect bounds; // @synthesize bounds=_bounds;
@property(nonatomic) struct CGRect frame; // @synthesize frame=_frame;
- (id)initWithExistingLayoutAttributes:(id)arg1;
- (id)init;

@end

