//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BLKFlexibleHeightBarBehaviorDefiner;

@interface BLKFlexibleHeightBar : UIView
{
    double _progress;
    double _maximumBarHeight;
    double _minimumBarHeight;
    BLKFlexibleHeightBarBehaviorDefiner *_behaviorDefiner;
}

@property(retain, nonatomic) BLKFlexibleHeightBarBehaviorDefiner *behaviorDefiner; // @synthesize behaviorDefiner=_behaviorDefiner;
@property(nonatomic) double minimumBarHeight; // @synthesize minimumBarHeight=_minimumBarHeight;
@property(nonatomic) double maximumBarHeight; // @synthesize maximumBarHeight=_maximumBarHeight;
@property(nonatomic) double progress; // @synthesize progress=_progress;
- (void).cxx_destruct;
- (double)interpolateFromValue:(double)arg1 toValue:(double)arg2 withProgress:(double)arg3;
- (void)applyFloorLayoutAttributes:(id)arg1 ceilingLayoutAttributes:(id)arg2 toSubview:(id)arg3 withFloorProgress:(double)arg4 ceilingProgress:(double)arg5;
- (void)layoutSubviews;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;
- (void)commonInit;

@end

