//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITableViewDelegate.h"

@class DBPrivacyHelperDataSource, NSString, UIButton, UIImage, UIImageView, UITableView;

@interface DBPrivateHelperController : UIViewController <UITableViewDelegate>
{
    unsigned long long _type;
    DBPrivacyHelperDataSource *_dataSource;
    UIImageView *_backgroundImage;
    UITableView *_tableView;
    _Bool _canRotate;
    long long _statusBarStyle;
    UIButton *_closeButton;
    UIImage *_snapshot;
    NSString *_appIcon;
    CDUnknownBlockType _didDismissViewController;
}

+ (id)helperForType:(unsigned long long)arg1;
@property(copy, nonatomic) CDUnknownBlockType didDismissViewController; // @synthesize didDismissViewController=_didDismissViewController;
@property(retain, nonatomic) NSString *appIcon; // @synthesize appIcon=_appIcon;
@property(retain, nonatomic) UIImage *snapshot; // @synthesize snapshot=_snapshot;
@property(readonly, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(nonatomic) _Bool canRotate; // @synthesize canRotate=_canRotate;
@property(nonatomic) long long statusBarStyle; // @synthesize statusBarStyle=_statusBarStyle;
- (void).cxx_destruct;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (long long)preferredStatusBarStyle;
- (void)bdph_dismissHelper:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithPrivacyType:(unsigned long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

