//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSDictionary, NSString;

@interface DBPrivacyHelperDataSource : NSObject <UITableViewDataSource, UITableViewDelegate>
{
    NSDictionary *_cellAttributes;
    NSString *_appIcon;
    unsigned long long _type;
}

@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *appIcon; // @synthesize appIcon=_appIcon;
- (void).cxx_destruct;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
@property(readonly, nonatomic) NSDictionary *cellData;
- (double)dbph_cellHeightForText:(id)arg1;
- (id)dbph_typeAllowText:(id)arg1;
- (id)dbph_typeTitle:(id)arg1;
- (id)dbph_headerText:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

