//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel;

@interface DBPrivateHelperCell : UITableViewCell
{
    UIImageView *_iconView;
    UILabel *_cellLabel;
}

- (void).cxx_destruct;
- (void)setIcon:(id)arg1 text:(id)arg2 row:(long long)arg3;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

