//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSSet, NSString, NSURL;

@interface JDLAPIRequestHMACHashBuilder : NSObject
{
    NSURL *_url;
    NSString *_requestHTTPMethod;
    NSString *_clientType;
    NSString *_secretKey;
    NSString *_accessToken;
    NSString *_timestamp;
    NSDictionary *_queryParameters;
    NSDictionary *_bodyParameters;
    NSSet *_HTTPMethodsEncodingParametersInURI;
}

@property(retain, nonatomic) NSSet *HTTPMethodsEncodingParametersInURI; // @synthesize HTTPMethodsEncodingParametersInURI=_HTTPMethodsEncodingParametersInURI;
@property(retain, nonatomic) NSDictionary *bodyParameters; // @synthesize bodyParameters=_bodyParameters;
@property(retain, nonatomic) NSDictionary *queryParameters; // @synthesize queryParameters=_queryParameters;
@property(copy, nonatomic) NSString *timestamp; // @synthesize timestamp=_timestamp;
@property(copy, nonatomic) NSString *accessToken; // @synthesize accessToken=_accessToken;
@property(copy, nonatomic) NSString *secretKey; // @synthesize secretKey=_secretKey;
@property(copy, nonatomic) NSString *clientType; // @synthesize clientType=_clientType;
@property(copy, nonatomic) NSString *requestHTTPMethod; // @synthesize requestHTTPMethod=_requestHTTPMethod;
@property(copy, nonatomic) NSURL *url; // @synthesize url=_url;
- (void).cxx_destruct;
- (id)jsonStringFromObject:(id)arg1;
- (id)escapeQueryPart:(id)arg1;
- (id)serializeParameters:(id)arg1 withPairSeparator:(id)arg2 componentJoinString:(id)arg3 clientType:(id)arg4;
- (id)buildHMACHash;
- (id)buildTemplate;
- (id)addBody:(id)arg1;
- (id)addQueryParameters:(id)arg1;
- (id)addTimestamp:(id)arg1;
- (id)initWithUrl:(id)arg1 requestHTTPMethod:(id)arg2 clientType:(id)arg3 secretKey:(id)arg4 accessToken:(id)arg5;

@end

