//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber;

@interface JDLAPIHealthMonitorImageRequestMeta : NSObject
{
    _Bool _isThumbnail;
    NSNumber *_startTime;
}

@property(nonatomic) _Bool isThumbnail; // @synthesize isThumbnail=_isThumbnail;
@property(retain, nonatomic) NSNumber *startTime; // @synthesize startTime=_startTime;
- (void).cxx_destruct;
- (id)initWithStartTime:(id)arg1 isThumbnail:(_Bool)arg2;

@end

