//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JDLActionTracking : NSObject
{
}

+ (long long)trackingOrderKeyForOrder:(long long)arg1;
+ (id)actionKeyNameForAction:(long long)arg1;
+ (void)trackActionString:(id)arg1;
+ (void)trackAction:(long long)arg1;
+ (void)trackHometownSetStarted;
+ (void)trackHometownSetCompleted;
+ (void)trackFilterBarOrderChangedTo:(long long)arg1 forFeedType:(long long)arg2;

@end

