//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JDLFeedDataSourceProtocol.h"

@class NSMutableArray, NSString;

@interface JDLBaseFeedDataSource : NSObject <JDLFeedDataSourceProtocol>
{
    NSObject *_lock;
    NSMutableArray *_cellViewModels;
}

@property(retain, nonatomic) NSMutableArray *cellViewModels; // @synthesize cellViewModels=_cellViewModels;
@property(retain, nonatomic) NSObject *lock; // @synthesize lock=_lock;
- (void).cxx_destruct;
- (id)getAllViewModels;
- (void)addCells:(id)arg1 toTheEnd:(_Bool)arg2;
- (void)resetAllCells:(id)arg1;
- (id)replaceCell:(id)arg1 withNewCell:(id)arg2;
- (id)indexPathForCellWithCellId:(id)arg1;
- (id)cellWithCellId:(id)arg1;
- (id)indexPathOfCell:(id)arg1;
- (id)lastCellId;
- (void)removeAllCells;
- (void)removeCellAtIndexPath:(id)arg1;
- (id)cellAtIndexPath:(id)arg1;
- (unsigned long long)cellsCountInSection:(long long)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

