//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JDLBaseFeedViewModel.h"

#import "JDLFeedViewModelFetchProtocol.h"
#import "JDLStickyPostCellParentProtocol.h"

@class JDLComboFeedDataSource, JDLFeedFetchLockTrackHelper, JDLStickyPostsManager, NSString, RACSignal;

@interface JDLComboBaseViewModel : JDLBaseFeedViewModel <JDLStickyPostCellParentProtocol, JDLFeedViewModelFetchProtocol>
{
    RACSignal *_cellIndexPathDeleteSignal;
    id <JDLComboFeedFetchServiceProtocol> _fetchService;
    JDLFeedFetchLockTrackHelper *_fetchHelper;
    JDLStickyPostsManager *_stickyManager;
}

@property(retain, nonatomic) JDLStickyPostsManager *stickyManager; // @synthesize stickyManager=_stickyManager;
@property(retain, nonatomic) JDLFeedFetchLockTrackHelper *fetchHelper; // @synthesize fetchHelper=_fetchHelper;
@property(retain, nonatomic) id <JDLComboFeedFetchServiceProtocol> fetchService; // @synthesize fetchService=_fetchService;
@property(readonly, nonatomic) RACSignal *cellIndexPathDeleteSignal; // @synthesize cellIndexPathDeleteSignal=_cellIndexPathDeleteSignal;
- (void).cxx_destruct;
- (void)openPostForStickyCellViewModel:(id)arg1 postId:(id)arg2 postColor:(id)arg3;
- (void)openChannelForStickyCellViewModel:(id)arg1 channel:(id)arg2;
- (void)openHashtagForStickyCellViewModel:(id)arg1 hashtag:(id)arg2;
- (void)dismissStickyPostForCellViewModel:(id)arg1;
- (void)voteStickyPostForCellViewModel:(id)arg1 upvote:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)removeCellViewModel:(id)arg1;
- (long long)orderAfterPostCreation;
- (void)fetchMore:(CDUnknownBlockType)arg1;
- (_Bool)isPossibleToFetchMore;
- (void)pullToRefresh:(CDUnknownBlockType)arg1;
- (id)cellsForPosts:(id)arg1 andStickies:(id)arg2;
- (void)fetchInitialData:(CDUnknownBlockType)arg1;
- (_Bool)useRandomBackgroundColor;
@property(nonatomic) long long feedOrder;
- (id)initWithFetchService:(id)arg1 feedType:(long long)arg2;

// Remaining properties
@property(retain, nonatomic) JDLComboFeedDataSource *dataSource; // @dynamic dataSource;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

