//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JDLConfigFeatures : NSObject
{
}

+ (_Bool)shouldHidePostButtonForHometown;
+ (_Bool)settingsCustomLinkEnabled;
+ (_Bool)moderationEnabled;
+ (_Bool)cloudUUIDSyncFeatureEnabled;
+ (_Bool)feedPostImageHoldToViewLabelEnabled;
+ (_Bool)hashtagFeedEnabled;
+ (_Bool)feedPostMarkOjEnabled;
+ (_Bool)postHashtagAutoInsertEnabled;
+ (_Bool)postDraftEnabled;
+ (_Bool)zendeskEnabled;
+ (_Bool)shouldUseNewFlagFlow;

@end

