//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface JDLComboResponse : NSObject
{
    NSArray *_stickyPosts;
    NSArray *_comboPosts;
}

@property(copy, nonatomic) NSArray *comboPosts; // @synthesize comboPosts=_comboPosts;
@property(copy, nonatomic) NSArray *stickyPosts; // @synthesize stickyPosts=_stickyPosts;
- (void).cxx_destruct;
- (id)postsForOrder:(long long)arg1;
- (id)initWithPosts1:(id)arg1 posts2:(id)arg2 posts3:(id)arg3 stickyPosts:(id)arg4;
- (id)initWithPosts1:(id)arg1 posts2:(id)arg2 posts3:(id)arg3;

@end

