//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CAAnimationDelegate.h"
#import "UIViewControllerAnimatedTransitioning.h"

@class CAShapeLayer, NSString;

@interface JDLCircleAnimatedTransitioning : NSObject <UIViewControllerAnimatedTransitioning, CAAnimationDelegate>
{
    id <UIViewControllerContextTransitioning> _transitionContext;
    CAShapeLayer *_borderLayer;
    struct CGRect _initialCircleExpandFrame;
}

@property(nonatomic) struct CGRect initialCircleExpandFrame; // @synthesize initialCircleExpandFrame=_initialCircleExpandFrame;
- (void).cxx_destruct;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (id)getDefaultCircleAnimationForStartPath:(id)arg1 endPath:(id)arg2;
- (void)animateTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

