//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

@class UISwitch;

@interface JDLCloudSettingsViewController : UITableViewController
{
    _Bool _cloudSyncEnabled;
    UISwitch *_switchControl;
}

@property(retain, nonatomic) UISwitch *switchControl; // @synthesize switchControl=_switchControl;
@property(nonatomic) _Bool cloudSyncEnabled; // @synthesize cloudSyncEnabled=_cloudSyncEnabled;
- (void).cxx_destruct;
- (void)cloudSyncSwitched:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(long long)arg2;
- (void)refreshCloudSyncState;
- (void)viewDidLoad;

@end

