//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UIButton, UILabel;

@interface JDLChannelFeedFollowOverlay : UIViewController
{
    UILabel *_topLabel;
    UIButton *_followButton;
}

@property(nonatomic) __weak UIButton *followButton; // @synthesize followButton=_followButton;
@property(nonatomic) __weak UILabel *topLabel; // @synthesize topLabel=_topLabel;
- (void).cxx_destruct;
- (void)removeOverlayFromWindow;
- (void)showBottomFollowOverlay:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)setupFollowButtonOverlayOverWindow;

@end

