//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JDLFeedDataSourceProtocol.h"

@class NSArray, NSDictionary, NSString;

@interface JDLComboFeedDataSource : NSObject <JDLFeedDataSourceProtocol>
{
    long long _feedOrder;
    NSArray *_feedOrders;
    NSDictionary *_dataSources;
}

@property(retain, nonatomic) NSDictionary *dataSources; // @synthesize dataSources=_dataSources;
@property(retain, nonatomic) NSArray *feedOrders; // @synthesize feedOrders=_feedOrders;
@property(nonatomic) long long feedOrder; // @synthesize feedOrder=_feedOrder;
- (void).cxx_destruct;
- (id)getAllViewModels;
- (void)addMore:(id)arg1 feedOrder:(long long)arg2;
- (void)reset:(id)arg1 feedOrder:(long long)arg2;
- (unsigned long long)cellsCountInSection:(long long)arg1;
- (void)removeCellAtIndexPath:(id)arg1 forOrder:(long long)arg2;
- (void)removeCellAtIndexPath:(id)arg1;
- (id)replaceCell:(id)arg1 withNewCell:(id)arg2;
- (id)indexPathOfCell:(id)arg1 forOrder:(long long)arg2;
- (id)indexPathOfCell:(id)arg1;
- (id)indexPathForCellWithCellId:(id)arg1;
- (id)cellWithCellId:(id)arg1;
- (id)lastCellId;
- (id)cellAtIndexPath:(id)arg1;
- (id)currentDataSource;
- (id)dataSourceForOrder:(long long)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

