//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JDLSingleFeedViewController.h"

@class JDLComboBaseViewModel, JDLFeedFilterView;

@interface JDLComboFeedViewController : JDLSingleFeedViewController
{
    JDLFeedFilterView *_filter;
}

@property(retain, nonatomic) JDLFeedFilterView *filter; // @synthesize filter=_filter;
- (void).cxx_destruct;
- (void)unwindFromPostCreation:(id)arg1;
- (void)scrollToTopAnimated:(_Bool)arg1;
- (void)setNewFeedOrder:(long long)arg1 andScrollToTopWithAnimation:(_Bool)arg2;
- (void)filterSegmentControlValueChanged:(id)arg1;
- (void)localiseFilter;
- (void)setupFilter;
- (void)refreshAfterFetchWithError:(id)arg1;
- (void)refreshRandomBackgroundColor;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, nonatomic) JDLComboBaseViewModel *viewModel; // @dynamic viewModel;

@end

