//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JDLComboBaseViewModel.h"

#import "JDLChannelsFeedFetchServiceDelegate.h"

@class JDLChannelsService, NSString;

@interface JDLChannelsFeedViewModel : JDLComboBaseViewModel <JDLChannelsFeedFetchServiceDelegate>
{
    _Bool _isSponsoredChannel;
    NSString *_channel;
    NSString *_followersCount;
    JDLChannelsService *_channelsService;
}

@property(retain, nonatomic) JDLChannelsService *channelsService; // @synthesize channelsService=_channelsService;
@property(nonatomic) _Bool isSponsoredChannel; // @synthesize isSponsoredChannel=_isSponsoredChannel;
@property(copy, nonatomic) NSString *followersCount; // @synthesize followersCount=_followersCount;
@property(copy, nonatomic) NSString *channel; // @synthesize channel=_channel;
- (void).cxx_destruct;
- (void)openPostForPostCellViewModel:(id)arg1;
- (void)channelSponsoredInfoUpdated:(_Bool)arg1;
- (void)channelFollowersCountUpdated:(long long)arg1;
- (void)refreshViewModels;
- (void)setupBasePostCellViewModel:(id)arg1;
- (id)buildCellViewModelForPost:(id)arg1;
- (void)openChannelForPostCellViewModel:(id)arg1 channel:(id)arg2;
- (_Bool)isChannelFollowed;
- (void)followToggleWithCompletion:(CDUnknownBlockType)arg1;
- (id)formattedChannel;
- (void)fetchInitialData:(CDUnknownBlockType)arg1;
- (id)initWithChannel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

