//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JDLFullWidthTableViewCell.h"

@class JDLChannelCellViewModel, NSLayoutConstraint, NSTimer, UIActivityIndicatorView, UIButton, UILabel;

@interface JDLChannelCell : JDLFullWidthTableViewCell
{
    UIButton *_followButton;
    NSLayoutConstraint *_buttonTrailingConstraint;
    NSLayoutConstraint *_buttonWidthConstraint;
    UILabel *_mainLabel;
    UILabel *_rightLabel;
    JDLChannelCellViewModel *_viewModel;
    id <JDLChannelCellFollowProtocol> _followViewModel;
    UIActivityIndicatorView *_loadingIndicator;
    NSTimer *_showLoadingIndicatorTimer;
}

@property(retain, nonatomic) NSTimer *showLoadingIndicatorTimer; // @synthesize showLoadingIndicatorTimer=_showLoadingIndicatorTimer;
@property(nonatomic) __weak UIActivityIndicatorView *loadingIndicator; // @synthesize loadingIndicator=_loadingIndicator;
@property(retain, nonatomic) id <JDLChannelCellFollowProtocol> followViewModel; // @synthesize followViewModel=_followViewModel;
@property(retain, nonatomic) JDLChannelCellViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(nonatomic) __weak UILabel *rightLabel; // @synthesize rightLabel=_rightLabel;
@property(nonatomic) __weak UILabel *mainLabel; // @synthesize mainLabel=_mainLabel;
@property(nonatomic) __weak NSLayoutConstraint *buttonWidthConstraint; // @synthesize buttonWidthConstraint=_buttonWidthConstraint;
@property(nonatomic) __weak NSLayoutConstraint *buttonTrailingConstraint; // @synthesize buttonTrailingConstraint=_buttonTrailingConstraint;
@property(nonatomic) __weak UIButton *followButton; // @synthesize followButton=_followButton;
- (void).cxx_destruct;
- (_Bool)isAccessibilityElement;
- (id)accessibilityViews;
- (void)prepareAccessibility;
- (void)didPressFollow:(id)arg1;
- (void)refreshButtonState:(_Bool)arg1;
- (void)showLoadingIndicator;
- (void)configureWithViewModel:(id)arg1 followViewModel:(id)arg2;

@end

