//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JDLChannelsDataSourceProtocol.h"

@class JDLChannelsService, NSArray, NSString, RACSubject;

@interface JDLChannelsViewModel : NSObject <JDLChannelsDataSourceProtocol>
{
    RACSubject *shouldRefreshChannelsList;
    NSArray *_channelsSections;
    JDLChannelsService *_service;
    NSArray *_currentLocalTrends;
}

@property(retain, nonatomic) NSArray *currentLocalTrends; // @synthesize currentLocalTrends=_currentLocalTrends;
@property(retain, nonatomic) JDLChannelsService *service; // @synthesize service=_service;
@property(retain, nonatomic) NSArray *channelsSections; // @synthesize channelsSections=_channelsSections;
@property(retain, nonatomic) RACSubject *shouldRefreshChannelsList; // @synthesize shouldRefreshChannelsList;
- (void).cxx_destruct;
- (_Bool)shouldShowHeaderForSection:(unsigned long long)arg1;
- (_Bool)shouldShowSuggestedChannels;
- (_Bool)shouldShowEmptyCellForFirstSection;
- (long long)numberOfSections;
- (id)numberOfFollowersForChannel:(id)arg1;
- (_Bool)hasNotificationForChannel:(id)arg1;
- (id)channelAtIndexPath:(id)arg1;
- (long long)rowsCountForSection:(unsigned long long)arg1;
- (id)rowsArrayForSection:(unsigned long long)arg1;
- (id)footerMessage;
- (id)getAllSuggestedChannels;
- (id)getLocalTrendChannels;
- (id)getShuffledUniqueFromChannels:(id)arg1;
- (id)sortViewModelsByFollowers:(id)arg1;
- (id)sortViewModelsAlphabetically:(id)arg1;
- (id)getRecommendedChannelViewModelsFrom:(id)arg1 withMaximum:(long long)arg2;
- (void)pickNewLocalTrends;
- (_Bool)shouldPickNewLocalTrends;
- (void)refreshChannelsList;
- (void)newRecommendedChannelsFetched;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

