//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JDLFeedPostButtonViewController.h"

@class JDLChannelFeedFollowOverlay, JDLChannelsFeedViewModel, UIButton;

@interface JDLChannelsFeedViewController : JDLFeedPostButtonViewController
{
    _Bool _viewAppearedInitialized;
    UIButton *_followTogglerButton;
    JDLChannelFeedFollowOverlay *_followButtonOverlay;
}

@property(retain, nonatomic) JDLChannelFeedFollowOverlay *followButtonOverlay; // @synthesize followButtonOverlay=_followButtonOverlay;
@property(nonatomic) _Bool viewAppearedInitialized; // @synthesize viewAppearedInitialized=_viewAppearedInitialized;
@property(nonatomic) __weak UIButton *followTogglerButton; // @synthesize followTogglerButton=_followTogglerButton;
- (void).cxx_destruct;
- (id)replyViewController;
- (void)configureForSponsoredChannel;
- (void)refreshFollowToggler;
- (void)refreshFollowState;
- (void)setupFollowButtonOverlay;
- (void)toggleFollowStatus;
- (void)bottomNotificationJoinChannel:(id)arg1;
- (void)followTogglePressed:(id)arg1;
- (_Bool)displayKarmaValueOnNavigationBar;
- (_Bool)updateTitleAndCoordinatesWithNewLocation;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)setFollowButtonCount:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)reloadInitialData;
- (void)viewDidLoad;
- (void)bindViewModel:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(retain, nonatomic) JDLChannelsFeedViewModel *viewModel; // @dynamic viewModel;

@end

