//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JDLDraftManager : NSObject
{
    id <JDLDraftStorable> _store;
}

@property(retain, nonatomic) id <JDLDraftStorable> store; // @synthesize store=_store;
- (void).cxx_destruct;
- (void)removeDraftForThreadId:(id)arg1;
- (id)getDraftForThread:(id)arg1;
- (void)saveDraftWithText:(id)arg1 forThreadWithId:(id)arg2 cursorPostition:(unsigned long long)arg3;
- (id)initWithStore:(id)arg1;

@end

