//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JDLEventNotifier : NSObject
{
}

+ (id)notificationCenter;
+ (void)postChangedHometownStatus;
+ (void)postNewRecommendedChannelsFetched;
+ (void)postChannelStatusNotification;
+ (void)postChannelNotificationsChanged;
+ (void)postPinUnpinNotificationForJodel:(id)arg1 byObject:(id)arg2;
+ (void)postVotingNotificationForJodel:(id)arg1 byObject:(id)arg2;
+ (void)postDeletionNotificationForJodel:(id)arg1 parentJodelId:(id)arg2 fromFeedType:(long long)arg3;

@end

