//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JDLFeedManager : NSObject
{
}

+ (_Bool)isHashtagFeedType:(long long)arg1;
+ (_Bool)isRootFeedType:(long long)arg1;
+ (id)nameForFeedOrder:(long long)arg1;
+ (id)nameForFeedType:(long long)arg1;
+ (long long)detailsFeedTypeForFeedType:(long long)arg1;

@end

