//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class JDLLoadingTableView, UIActivityIndicatorView;

@interface JDLFeedBottomPullToRefresh : NSObject
{
    _Bool _pullToRefreshEnabled;
    _Bool _isBottomRefreshing;
    UIActivityIndicatorView *_bottomIndicator;
    JDLLoadingTableView *_tableView;
    CDUnknownBlockType _pullToRefreshAction;
}

@property(nonatomic) _Bool isBottomRefreshing; // @synthesize isBottomRefreshing=_isBottomRefreshing;
@property(copy, nonatomic) CDUnknownBlockType pullToRefreshAction; // @synthesize pullToRefreshAction=_pullToRefreshAction;
@property(retain, nonatomic) JDLLoadingTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UIActivityIndicatorView *bottomIndicator; // @synthesize bottomIndicator=_bottomIndicator;
@property(nonatomic) _Bool pullToRefreshEnabled; // @synthesize pullToRefreshEnabled=_pullToRefreshEnabled;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)updateBottomRefresh;
- (void)stopPullToRefresh;
- (void)setupWithAction:(CDUnknownBlockType)arg1;
- (id)initWithTableView:(id)arg1;
- (void)dealloc;

@end

