//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JDLComboFeedViewController.h"

#import "JDLLongPressPopoverDelegate.h"

@class JDLLongPressTutorialPopover, NSString, NSTimer, UIButton, UILongPressGestureRecognizer;

@interface JDLFeedPostButtonViewController : JDLComboFeedViewController <JDLLongPressPopoverDelegate>
{
    _Bool _longPressTutorialIsVisible;
    _Bool _longPressPopoverDisabled;
    UIButton *_addPostButton;
    UILongPressGestureRecognizer *_longPressRecognizer;
    JDLLongPressTutorialPopover *_longPressPopover;
    NSTimer *_showPopoverTimer;
}

@property(retain, nonatomic) NSTimer *showPopoverTimer; // @synthesize showPopoverTimer=_showPopoverTimer;
@property(nonatomic) _Bool longPressPopoverDisabled; // @synthesize longPressPopoverDisabled=_longPressPopoverDisabled;
@property(nonatomic) _Bool longPressTutorialIsVisible; // @synthesize longPressTutorialIsVisible=_longPressTutorialIsVisible;
@property(retain, nonatomic) JDLLongPressTutorialPopover *longPressPopover; // @synthesize longPressPopover=_longPressPopover;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPressRecognizer; // @synthesize longPressRecognizer=_longPressRecognizer;
@property(nonatomic) __weak UIButton *addPostButton; // @synthesize addPostButton=_addPostButton;
- (void).cxx_destruct;
- (void)disableLongPressPopover;
- (id)replyViewController;
- (void)openReplyWithRoundAnimation:(_Bool)arg1;
- (void)replyPressed:(id)arg1;
- (void)longPressRecognizerChanged:(id)arg1;
- (void)hideLongPressTutorial;
- (void)didPressDismiss;
- (void)setPopoverFrame;
- (void)showPopoverAnimated;
- (void)showLongPressTutorial;
- (void)refreshPostButtonVisibility;
- (void)didChangeHomeStatus;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

