//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JDLFeedActionStatsContext : NSObject
{
    _Bool _isReply;
    long long _feedType;
    long long _rootFeedOrder;
    long long _actionSource;
}

@property(nonatomic) long long actionSource; // @synthesize actionSource=_actionSource;
@property(nonatomic) long long rootFeedOrder; // @synthesize rootFeedOrder=_rootFeedOrder;
@property(nonatomic) long long feedType; // @synthesize feedType=_feedType;
@property(nonatomic) _Bool isReply; // @synthesize isReply=_isReply;

@end

