//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UITableView;

@interface JDLFeedPullToRefresh : NSObject
{
    _Bool _pullToRefreshEnabled;
    UITableView *_tableView;
    double _topInset;
}

@property(nonatomic) double topInset; // @synthesize topInset=_topInset;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) _Bool pullToRefreshEnabled; // @synthesize pullToRefreshEnabled=_pullToRefreshEnabled;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)preloadImages;
- (void)dealloc;
- (void)triggerPullToRefresh;
- (void)stopPullToRefresh;
- (void)setTintColor:(id)arg1 redrawAnimatedImages:(_Bool)arg2;
- (void)setTintColor:(id)arg1;
- (void)setupWithAction:(CDUnknownBlockType)arg1;
- (id)initWithTableView:(id)arg1;

@end

