//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JDLComboBaseViewModel.h"

@class NSString;

@interface JDLHashtagFeedViewModel : JDLComboBaseViewModel
{
    NSString *_hashtag;
}

@property(copy, nonatomic) NSString *hashtag; // @synthesize hashtag=_hashtag;
- (void).cxx_destruct;
- (void)openPostForPostCellViewModel:(id)arg1;
- (void)openHashtagForPostCellViewModel:(id)arg1 hashtag:(id)arg2;
- (id)getUnformattedHashtag;
- (id)getFormattedHashtag;
- (id)initWithHashtag:(id)arg1;

@end

