//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "MKMapViewDelegate.h"

@class CLLocation, JDLHomeMapPopupsViewController, JDLHomeMapViewModel, JDLTutorialPageController, MKMapView, NSLayoutConstraint, NSString, UIButton, UIImageView, UILabel, UIView;

@interface JDLHomeMapViewController : UIViewController <MKMapViewDelegate>
{
    MKMapView *_mapView;
    JDLTutorialPageController *_tutorialPage;
    JDLHomeMapViewModel *_viewModel;
    JDLHomeMapPopupsViewController *_popupsViewController;
    UILabel *_locatonDescriptionLabel;
    UILabel *_locationLabel;
    NSLayoutConstraint *_bottomBarHeightConstraint;
    NSLayoutConstraint *_tutorialHeightConstraint;
    UIImageView *_sliderStateImage;
    UIButton *_nextButton;
    UIView *_annotationLabelView;
    NSLayoutConstraint *_mapTopConstraint;
    CLLocation *_lastLocation;
}

@property(retain, nonatomic) CLLocation *lastLocation; // @synthesize lastLocation=_lastLocation;
@property(nonatomic) __weak NSLayoutConstraint *mapTopConstraint; // @synthesize mapTopConstraint=_mapTopConstraint;
@property(nonatomic) __weak UIView *annotationLabelView; // @synthesize annotationLabelView=_annotationLabelView;
@property(nonatomic) __weak UIButton *nextButton; // @synthesize nextButton=_nextButton;
@property(nonatomic) __weak UIImageView *sliderStateImage; // @synthesize sliderStateImage=_sliderStateImage;
@property(nonatomic) __weak NSLayoutConstraint *tutorialHeightConstraint; // @synthesize tutorialHeightConstraint=_tutorialHeightConstraint;
@property(nonatomic) __weak NSLayoutConstraint *bottomBarHeightConstraint; // @synthesize bottomBarHeightConstraint=_bottomBarHeightConstraint;
@property(nonatomic) __weak UILabel *locationLabel; // @synthesize locationLabel=_locationLabel;
@property(nonatomic) __weak UILabel *locatonDescriptionLabel; // @synthesize locatonDescriptionLabel=_locatonDescriptionLabel;
@property(retain, nonatomic) JDLHomeMapPopupsViewController *popupsViewController; // @synthesize popupsViewController=_popupsViewController;
@property(retain, nonatomic) JDLHomeMapViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(retain, nonatomic) JDLTutorialPageController *tutorialPage; // @synthesize tutorialPage=_tutorialPage;
@property(nonatomic) __weak MKMapView *mapView; // @synthesize mapView=_mapView;
- (void).cxx_destruct;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)showConfirmHomePopups;
- (void)showMapAnnotation;
- (void)mapView:(id)arg1 didUpdateUserLocation:(id)arg2;
- (void)setUserCity:(id)arg1 country:(id)arg2;
- (void)setLocationInitialValues;
- (void)updateCurrentLocation;
- (id)getLastLocation;
- (void)pressedNext:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

