//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JDLFeedPostButtonViewController.h"

@class JDLHashtagFeedViewModel, UIButton;

@interface JDLHashtagFeedViewController : JDLFeedPostButtonViewController
{
    UIButton *_followTogglerButton;
}

@property(nonatomic) __weak UIButton *followTogglerButton; // @synthesize followTogglerButton=_followTogglerButton;
- (void).cxx_destruct;
- (_Bool)displayKarmaValueOnNavigationBar;
- (_Bool)updateTitleAndCoordinatesWithNewLocation;
- (id)replyViewController;
- (void)bindViewModel:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(retain, nonatomic) JDLHashtagFeedViewModel *viewModel; // @dynamic viewModel;

@end

