//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JDLNetworkCheckingBaseViewController.h"

#import "TLMAVCamCaptureManagerDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class AVCaptureVideoPreviewLayer, NSString, TLMAVCamCaptureManager, TLMShadowButton, UIButton, UIColor, UILabel, UIPinchGestureRecognizer, UITapGestureRecognizer, UIView;

@interface JDLImageCaptureViewController : JDLNetworkCheckingBaseViewController <TLMAVCamCaptureManagerDelegate, UIGestureRecognizerDelegate>
{
    double beginGestureScale;
    _Bool _captureSessionDidStart;
    UIColor *_postColor;
    id <TLMCaptureViewControllerDelegate> _delegate;
    TLMAVCamCaptureManager *_captureManager;
    AVCaptureVideoPreviewLayer *_captureVideoPreviewLayer;
    UIView *_videoPreviewView;
    UIPinchGestureRecognizer *_pinchGesture;
    UITapGestureRecognizer *_focusGesture;
    UILabel *_permissionLabel;
    UIButton *_permissionSettingsButton;
    UIButton *_captureButton;
    UIButton *_flashButton;
    TLMShadowButton *_cancelButton;
    UIButton *_toggleCameraButton;
    double _effectiveScale;
}

@property(nonatomic) _Bool captureSessionDidStart; // @synthesize captureSessionDidStart=_captureSessionDidStart;
@property(nonatomic) double effectiveScale; // @synthesize effectiveScale=_effectiveScale;
@property(nonatomic) __weak UIButton *toggleCameraButton; // @synthesize toggleCameraButton=_toggleCameraButton;
@property(nonatomic) __weak TLMShadowButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(nonatomic) __weak UIButton *flashButton; // @synthesize flashButton=_flashButton;
@property(nonatomic) __weak UIButton *captureButton; // @synthesize captureButton=_captureButton;
@property(nonatomic) __weak UIButton *permissionSettingsButton; // @synthesize permissionSettingsButton=_permissionSettingsButton;
@property(retain, nonatomic) UILabel *permissionLabel; // @synthesize permissionLabel=_permissionLabel;
@property(retain, nonatomic) UITapGestureRecognizer *focusGesture; // @synthesize focusGesture=_focusGesture;
@property(retain, nonatomic) UIPinchGestureRecognizer *pinchGesture; // @synthesize pinchGesture=_pinchGesture;
@property(retain, nonatomic) UIView *videoPreviewView; // @synthesize videoPreviewView=_videoPreviewView;
@property(retain, nonatomic) AVCaptureVideoPreviewLayer *captureVideoPreviewLayer; // @synthesize captureVideoPreviewLayer=_captureVideoPreviewLayer;
@property(retain, nonatomic) TLMAVCamCaptureManager *captureManager; // @synthesize captureManager=_captureManager;
@property(nonatomic) __weak id <TLMCaptureViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIColor *postColor; // @synthesize postColor=_postColor;
- (void).cxx_destruct;
- (void)cancelPressed:(id)arg1;
- (void)permissionsButtonPressed:(id)arg1;
- (void)toggleCamera:(id)arg1;
- (void)toggleFlash:(id)arg1;
- (void)captureManager:(id)arg1 didFailWithError:(id)arg2;
- (void)captureManagerStillImageCaptured:(id)arg1 image:(id)arg2;
- (void)animateScalePop:(id)arg1;
- (void)captureStillImage:(id)arg1;
- (_Bool)prefersStatusBarHidden;
- (void)didReceiveMemoryWarning;
- (void)updateToggleCameraButton;
- (void)updateFlashButton;
- (_Bool)isVideoPermissionAllowed;
- (_Bool)isVideoPermissionUnknown;
- (_Bool)isVideoPermissionDenied;
- (void)updatePermissionsStatusAuthorized:(_Bool)arg1;
- (void)viewDidLoad;
- (_Bool)shouldAutorotate;
- (void)initializeCaptureSession;
- (void)startCaptureSession;
- (void)askPermissionAndStartCaptureSession;
- (void)startSessionIfPermissionAlreadyAsked;
- (void)setupAndStartCaptureSessionAsync:(_Bool)arg1 askPermission:(_Bool)arg2;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)scaleZoom:(id)arg1;
- (void)handleDoubleTap:(id)arg1;
- (void)handleFocusAction:(id)arg1;
- (_Bool)disableAutomaticNetworkErrorMessageView;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

