//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JDLDraftStorable.h"

@class NSMutableDictionary, NSString;

@interface JDLInMemoryDraftStore : NSObject <JDLDraftStorable>
{
    NSMutableDictionary *_savedDrafts;
}

+ (id)sharedStore;
@property(copy, nonatomic) NSMutableDictionary *savedDrafts; // @synthesize savedDrafts=_savedDrafts;
- (void).cxx_destruct;
- (id)retrieveDraftWithId:(id)arg1;
- (void)removeDraft:(id)arg1;
- (void)saveDraft:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

