//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CLLocationManagerDelegate.h"

@class CLGeocoder, CLLocation, CLLocationManager, NSString, RACSubject;

@interface JDLLocationManager : NSObject <CLLocationManagerDelegate>
{
    id <JDLLocationDelegate> _delegate;
    CLGeocoder *_geocoder;
    CLLocationManager *_locationManager;
    CLLocation *_userLocation;
    NSString *_name;
    NSString *_city;
    NSString *_country;
    NSString *_countryCode;
    RACSubject *_sendLocationSubject;
}

+ (id)sharedManager;
@property(retain, nonatomic) RACSubject *sendLocationSubject; // @synthesize sendLocationSubject=_sendLocationSubject;
@property(retain, nonatomic) NSString *countryCode; // @synthesize countryCode=_countryCode;
@property(retain, nonatomic) NSString *country; // @synthesize country=_country;
@property(retain, nonatomic) NSString *city; // @synthesize city=_city;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) CLLocation *userLocation; // @synthesize userLocation=_userLocation;
@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property(retain, nonatomic) CLGeocoder *geocoder; // @synthesize geocoder=_geocoder;
@property(nonatomic) __weak id <JDLLocationDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)fakeLocationCityName;
- (id)fakeLocation;
- (void)updateUserLocation:(id)arg1 retryOnFailure:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (_Bool)isUserLocationAvailable;
- (_Bool)isLocationValid:(id)arg1;
- (id)userCoordinates;
- (void)getReverseGeocodedLocationDictionaryFromLocation:(id)arg1;
- (void)locationUpdateFailed;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
- (long long)distanceChangeThreshold;
- (void)trackSendNewUserLocationWithItem:(id)arg1;
- (void)subscribeSavingLocation;
- (id)formattedMinimalLocationObject;
- (id)formattedLocationObject;
- (id)userLocationCountryCode;
- (id)userLocationCountry;
- (id)userLocationNameWithFallback;
- (id)userLocationName;
- (void)tryToGetAuthorization;
- (void)stopUpdatingLocation;
- (void)startTrackingLocation;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

