//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UIColor, UILabel;

@interface JDLModerationDecisionButton : UIButton
{
    UILabel *_bottomTitleLabel;
    UIColor *_originalBgColor;
}

@property(retain, nonatomic) UIColor *originalBgColor; // @synthesize originalBgColor=_originalBgColor;
@property(nonatomic) __weak UILabel *bottomTitleLabel; // @synthesize bottomTitleLabel=_bottomTitleLabel;
- (void).cxx_destruct;
- (void)setHighlighted:(_Bool)arg1;
- (void)awakeFromNib;

@end

