//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JDLComboFeedFetchServiceProtocol.h"

@class NSString;

@interface JDLMainFeedViewModelFetchService : NSObject <JDLComboFeedFetchServiceProtocol>
{
    _Bool _nextComboRequestWillIncludeStickies;
}

@property(nonatomic) _Bool nextComboRequestWillIncludeStickies; // @synthesize nextComboRequestWillIncludeStickies=_nextComboRequestWillIncludeStickies;
- (void)dealloc;
- (id)latestCoordinates;
- (_Bool)isSetToHome;
- (id)fetchPostsForFeedOrder:(long long)arg1 afterId:(id)arg2 skip:(long long)arg3 completion:(CDUnknownBlockType)arg4;
- (id)fetchComboWithCompletion:(CDUnknownBlockType)arg1;
- (void)onUIApplicationDidBecomeActiveNotification:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

