//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JDLModerationStatusService : NSObject
{
}

+ (id)sharedInstance;
- (_Bool)isEnoughTimePassedToDisplayRedDotSinceModerationScreenLastTimeVisited;
- (void)markModerationVisitedForced:(_Bool)arg1;
- (void)markModerationVisited;
- (void)resetPostModerationCompletedOnce;
- (void)migrateRedDotThreshold;
- (void)setModerationRulesAccepted;
- (_Bool)shouldAcceptModerationRules;
- (_Bool)postModerationCompletedOnce;
- (unsigned long long)moderationCapabilities;
- (void)setUserModerationCapabilities:(unsigned long long)arg1;
- (_Bool)isModerator;
- (void)postModerationStateUpdateNotification;
- (void)setModerationCompleted;
- (_Bool)shouldDisplayRedDotForModerator;
- (id)init;

@end

