//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JDLComboBaseViewModel.h"

@class JDLMainFeedViewModelFetchService;

@interface JDLMainFeedViewModel : JDLComboBaseViewModel
{
    JDLMainFeedViewModelFetchService *_mainFeedFetchService;
}

@property(retain, nonatomic) JDLMainFeedViewModelFetchService *mainFeedFetchService; // @synthesize mainFeedFetchService=_mainFeedFetchService;
- (void).cxx_destruct;
- (_Bool)enableHometownFeature;
- (void)openPictureFeedForPostCellViewModel:(id)arg1;
- (id)buildCellViewModelForPost:(id)arg1;
- (void)setToHomeFeed:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (id)init;

@end

