//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface JDLPushNotification : NSObject
{
    unsigned long long _type;
    NSDictionary *_aps;
    NSString *_parentId;
    NSString *_postId;
    NSString *_postColor;
}

+ (unsigned long long)pushNotificationTypeFromString:(id)arg1;
@property(copy, nonatomic) NSString *postColor; // @synthesize postColor=_postColor;
@property(copy, nonatomic) NSString *postId; // @synthesize postId=_postId;
@property(copy, nonatomic) NSString *parentId; // @synthesize parentId=_parentId;
@property(copy, nonatomic) NSDictionary *aps; // @synthesize aps=_aps;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)fakePost;
- (id)initWithPushData:(id)arg1;

@end

