//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JDLPrefixHelper : NSObject
{
}

+ (_Bool)isEqualText:(id)arg1 toText:(id)arg2 sensitive:(_Bool)arg3;
+ (id)formatted:(id)arg1 withPrefix:(id)arg2;
+ (id)normalize:(id)arg1 withPrefix:(id)arg2;

@end

