//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JDLPictureFetchService : NSObject
{
    long long _order;
}

@property(nonatomic) long long order; // @synthesize order=_order;
- (void)fetchPictureFeedAfterPostId:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (_Bool)isSetToHome;
- (id)initWithOrder:(long long)arg1;

@end

