//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

@class NSArray, SWGPost, UILabel;

@interface JDLPostFlagViewController : UITableViewController
{
    SWGPost *_postToFlag;
    CDUnknownBlockType _completion;
    UILabel *_headerLabel;
    NSArray *_reasons;
    long long _selectedReason;
}

@property(nonatomic) long long selectedReason; // @synthesize selectedReason=_selectedReason;
@property(retain, nonatomic) NSArray *reasons; // @synthesize reasons=_reasons;
@property(nonatomic) __weak UILabel *headerLabel; // @synthesize headerLabel=_headerLabel;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(retain, nonatomic) SWGPost *postToFlag; // @synthesize postToFlag=_postToFlag;
- (void).cxx_destruct;
- (id)localisedReasonForIndexPath:(id)arg1;
- (long long)reasonForIndexPath:(id)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewDidLoad;

@end

