//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "JDLPictureFeedActionsProtocol.h"

@class JDLPictureFeedViewModel, NSString, UIButton, UIImageView, UILabel, UIView;

@interface JDLPictureFeedViewController : UIViewController <JDLPictureFeedActionsProtocol>
{
    _Bool _hideStatusBar;
    JDLPictureFeedViewModel *_viewModel;
    UIView *_closeButtonBackView;
    UIButton *_closeButton;
    UILabel *_commentsLabel;
    UIButton *_commentsButton;
    UIButton *_arrowUpButton;
    UIButton *_arrowDownButton;
    UIView *_hintView;
    UILabel *_hintLabel;
    UIImageView *_backgroundImageView;
}

@property(nonatomic) _Bool hideStatusBar; // @synthesize hideStatusBar=_hideStatusBar;
@property(nonatomic) __weak UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
@property(nonatomic) __weak UILabel *hintLabel; // @synthesize hintLabel=_hintLabel;
@property(nonatomic) __weak UIView *hintView; // @synthesize hintView=_hintView;
@property(nonatomic) __weak UIButton *arrowDownButton; // @synthesize arrowDownButton=_arrowDownButton;
@property(nonatomic) __weak UIButton *arrowUpButton; // @synthesize arrowUpButton=_arrowUpButton;
@property(nonatomic) __weak UIButton *commentsButton; // @synthesize commentsButton=_commentsButton;
@property(nonatomic) __weak UILabel *commentsLabel; // @synthesize commentsLabel=_commentsLabel;
@property(nonatomic) __weak UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(nonatomic) __weak UIView *closeButtonBackView; // @synthesize closeButtonBackView=_closeButtonBackView;
@property(retain, nonatomic) JDLPictureFeedViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
- (void)hideActionButtons:(_Bool)arg1;
- (void)showActionButtons:(_Bool)arg1;
- (void)showArrows:(unsigned long long)arg1;
- (void)refreshForPost:(id)arg1;
- (void)close;
- (void)commentsTap:(id)arg1;
- (void)closeTap:(id)arg1;
- (_Bool)prefersStatusBarHidden;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)bindViewModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

