//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SWGPost;

@protocol JDLPictureFeedActionsProtocol <NSObject>
- (void)close;
- (void)showActionButtons:(_Bool)arg1;
- (void)hideActionButtons:(_Bool)arg1;
- (void)refreshForPost:(SWGPost *)arg1;
- (void)showArrows:(unsigned long long)arg1;
@end

