//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class SWGPost, UIActivityIndicatorView, UIImageView, UILabel;

@interface JDLPictureFeedCell : UICollectionViewCell
{
    id <JDLPictureFeedCellDelegate> _delegate;
    UIImageView *_thumbnailImageView;
    UIImageView *_largeImageView;
    UIActivityIndicatorView *_activityIndicator;
    UILabel *_infoLabel;
    SWGPost *_post;
    long long _trackingSource;
}

@property(nonatomic) long long trackingSource; // @synthesize trackingSource=_trackingSource;
@property(retain, nonatomic) SWGPost *post; // @synthesize post=_post;
@property(nonatomic) __weak UILabel *infoLabel; // @synthesize infoLabel=_infoLabel;
@property(nonatomic) __weak UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(nonatomic) __weak UIImageView *largeImageView; // @synthesize largeImageView=_largeImageView;
@property(nonatomic) __weak UIImageView *thumbnailImageView; // @synthesize thumbnailImageView=_thumbnailImageView;
@property(nonatomic) __weak id <JDLPictureFeedCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)imageLoadRequestForURLString:(id)arg1;
- (void)loadImages:(id)arg1;
- (void)refreshLoadingState:(_Bool)arg1 isTheLast:(_Bool)arg2;
- (void)tap:(id)arg1;
- (void)configureForPost:(id)arg1;
- (void)awakeFromNib;

@end

