//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class JDLRestApiConfiguration, NSMutableDictionary, SWGApiClient;

@interface JDLRestApi : NSObject
{
    SWGApiClient *_swgApiClient;
    JDLRestApiConfiguration *_apiConfiguration;
    NSMutableDictionary *_requestsInProgress;
}

+ (_Bool)isNoInternetCode:(long long)arg1;
+ (_Bool)isHMACSigningFailing:(long long)arg1;
+ (_Bool)isUserUnAuthorized:(long long)arg1;
+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *requestsInProgress; // @synthesize requestsInProgress=_requestsInProgress;
@property(retain, nonatomic) JDLRestApiConfiguration *apiConfiguration; // @synthesize apiConfiguration=_apiConfiguration;
@property(retain, nonatomic) SWGApiClient *swgApiClient; // @synthesize swgApiClient=_swgApiClient;
- (void).cxx_destruct;
- (void)setupGeneralConfiguration;
- (void)logUnauthorizedErrorToCrashlytics:(id)arg1;
- (id)findBeanByRequestId:(id)arg1;
- (id)executeRequest:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3 cancelled:(CDUnknownBlockType)arg4 initialTask:(_Bool)arg5;
- (id)executeRequest:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (id)executeRequest:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3 cancelled:(CDUnknownBlockType)arg4;
- (id)buildRequestWithPath:(id)arg1 methodType:(long long)arg2 responseType:(id)arg3;
- (id)init;
- (id)executeQueryForMyPostsAtPath:(id)arg1 skip:(id)arg2 limit:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (id)fetchMyLoudestFeedWithSkip:(id)arg1 limit:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)fetchMyMostDiscussedFeedWithSkip:(id)arg1 limit:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)fetchMyNewestFeedWithWithSkip:(id)arg1 limit:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)fetchMyComboWithCompletionBlock:(CDUnknownBlockType)arg1;
- (id)fetchMyPinsWithSkip:(id)arg1 limit:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)fetchMyVotesWithSkip:(id)arg1 limit:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)fetchMyRepliesWithSkip:(id)arg1 limit:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)sendModerationResult:(id)arg1 withCompletionBlock:(CDUnknownBlockType)arg2;
- (id)fetchModerationFeedWithCompletionBlock:(CDUnknownBlockType)arg1;
- (id)executeQueryForRecentPostsAtPath:(id)arg1 afterPostId:(id)arg2 skip:(id)arg3 limit:(id)arg4 latitude:(id)arg5 longitude:(id)arg6 shouldRefreshTokenOnUnauthorized:(_Bool)arg7 isHome:(_Bool)arg8 completionBlock:(CDUnknownBlockType)arg9;
- (id)pinUnpinPostWithPath:(id)arg1 postId:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)voteOnPostWithPath:(id)arg1 postId:(id)arg2 votingReasonRequest:(id)arg3 isHome:(_Bool)arg4 completionBlock:(CDUnknownBlockType)arg5;
- (id)toggleNotificationForPostId:(id)arg1 enabled:(_Bool)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)unpinPostWithId:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)pinPostWithId:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)votePostWithId:(id)arg1 withUpvote:(_Bool)arg2 votingReason:(id)arg3 isHome:(_Bool)arg4 completionBlock:(CDUnknownBlockType)arg5;
- (id)giveThanksToPostWithId:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)hidePostWithPostId:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)deletePostWithPostId:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)flagPostWithId:(id)arg1 reasonId:(id)arg2 subreasonId:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (id)createPostWithPostRequest:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)fetchDetailedPostWithId:(id)arg1 highlightedPostId:(id)arg2 details:(_Bool)arg3 reply:(id)arg4 reversed:(_Bool)arg5 isHome:(_Bool)arg6 completionHandler:(CDUnknownBlockType)arg7;
- (id)fetchPostWithId:(id)arg1 highlightedPostId:(id)arg2 isHome:(_Bool)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (id)fetchLoudestFeedAfterPostId:(id)arg1 skip:(id)arg2 limit:(id)arg3 latitude:(id)arg4 longitude:(id)arg5 isHome:(_Bool)arg6 completionBlock:(CDUnknownBlockType)arg7;
- (id)fetchMostDiscussedFeedAfterPostId:(id)arg1 skip:(id)arg2 limit:(id)arg3 latitude:(id)arg4 longitude:(id)arg5 isHome:(_Bool)arg6 completionBlock:(CDUnknownBlockType)arg7;
- (id)fetchNewestFeedAfterPostId:(id)arg1 skip:(id)arg2 limit:(id)arg3 latitude:(id)arg4 longitude:(id)arg5 isHome:(_Bool)arg6 completionBlock:(CDUnknownBlockType)arg7;
- (id)fetchPostsComboForLatitude:(id)arg1 longitude:(id)arg2 withStickies:(_Bool)arg3 withHomeFeed:(_Bool)arg4 completionBlock:(CDUnknownBlockType)arg5;
- (id)fetchUserConfig:(CDUnknownBlockType)arg1;
- (id)fetchDistinctIdWithCompletionBlock:(CDUnknownBlockType)arg1;
- (id)sendDevicePushToken:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)setUserHome:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)sendUserLocation:(id)arg1 retryOnFailure:(_Bool)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)sendUserProfileType:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)refreshAccessTokenWithCredentials:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)fetchKarmaWithCompletion:(CDUnknownBlockType)arg1;
- (id)registerNewUserWithCredentials:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)executeQueryForChannelPostsAtPath:(id)arg1 forChannel:(id)arg2 afterPostId:(id)arg3 skip:(id)arg4 limit:(id)arg5 isHome:(_Bool)arg6 completionBlock:(CDUnknownBlockType)arg7;
- (id)executeQueryForChannel:(id)arg1 path:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)unfollowChannel:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)followChannel:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)searchChannel:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)getRecommendedChannelsForHome:(_Bool)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (id)getFollowedChannelsStatusForHome:(_Bool)arg1 timestamps:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)fetchLoudestFeedForChannel:(id)arg1 afterPostId:(id)arg2 skip:(id)arg3 limit:(id)arg4 isHome:(_Bool)arg5 completionBlock:(CDUnknownBlockType)arg6;
- (id)fetchMostDiscussedFeedForChannel:(id)arg1 afterPostId:(id)arg2 skip:(id)arg3 limit:(id)arg4 isHome:(_Bool)arg5 completionBlock:(CDUnknownBlockType)arg6;
- (id)fetchNewestFeedForChannel:(id)arg1 afterPostId:(id)arg2 skip:(id)arg3 limit:(id)arg4 isHome:(_Bool)arg5 completionBlock:(CDUnknownBlockType)arg6;
- (id)fetchComboForChannel:(id)arg1 lat:(id)arg2 lon:(id)arg3 isHome:(_Bool)arg4 completionBlock:(CDUnknownBlockType)arg5;
- (id)trackAction:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)sendInvestigation:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)executeQueryForHashtagPostsAtPath:(id)arg1 forHashtag:(id)arg2 afterPostId:(id)arg3 limit:(id)arg4 isHome:(_Bool)arg5 completionBlock:(CDUnknownBlockType)arg6;
- (id)fetchLoudestFeedForHashtag:(id)arg1 afterPostId:(id)arg2 limit:(id)arg3 isHome:(_Bool)arg4 completionBlock:(CDUnknownBlockType)arg5;
- (id)fetchMostDiscussedFeedForHashtag:(id)arg1 afterPostId:(id)arg2 limit:(id)arg3 isHome:(_Bool)arg4 completionBlock:(CDUnknownBlockType)arg5;
- (id)fetchNewestFeedForHashtag:(id)arg1 afterPostId:(id)arg2 limit:(id)arg3 isHome:(_Bool)arg4 completionBlock:(CDUnknownBlockType)arg5;
- (id)fetchPostsForHashtag:(id)arg1 withHomeFeed:(_Bool)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)makePutRequestForPath:(id)arg1 postId:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)downvoteStickyPostWithId:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)upvoteStickyPostWithId:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)dismissStickyPostWithId:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)executeQueryForPicturesAtPath:(id)arg1 afterPostId:(id)arg2 limit:(id)arg3 shouldRefreshTokenOnUnauthorized:(_Bool)arg4 isHome:(_Bool)arg5 completionBlock:(CDUnknownBlockType)arg6;
- (id)fetchLoudestPictureFeedAfterPostId:(id)arg1 limit:(id)arg2 isHome:(_Bool)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (id)fetchDiscussedPictureFeedAfterPostId:(id)arg1 limit:(id)arg2 isHome:(_Bool)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (id)fetchNewestPictureFeedAfterPostId:(id)arg1 limit:(id)arg2 isHome:(_Bool)arg3 completionBlock:(CDUnknownBlockType)arg4;

@end

