//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UIActivityIndicatorView;

@interface JDLRegistrationButton : UIButton
{
    UIActivityIndicatorView *_loadingIndicatorView;
}

@property(retain, nonatomic) UIActivityIndicatorView *loadingIndicatorView; // @synthesize loadingIndicatorView=_loadingIndicatorView;
- (void).cxx_destruct;
- (void)updateConstraints;
- (void)stopLoadingAnimation;
- (void)startLoadingAnimation;
- (void)setupView;
- (void)awakeFromNib;

@end

