//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSString, RACSubject, UIButton, UILabel;

@interface JDLSetHomeTutorialViewController : UIViewController
{
    RACSubject *_didPressSetHomeButton;
    UIButton *_setHomeButton;
    UILabel *_userCity;
    UILabel *_userCountry;
    NSString *_userCityText;
    NSString *_userCountryText;
}

@property(copy, nonatomic) NSString *userCountryText; // @synthesize userCountryText=_userCountryText;
@property(copy, nonatomic) NSString *userCityText; // @synthesize userCityText=_userCityText;
@property(nonatomic) __weak UILabel *userCountry; // @synthesize userCountry=_userCountry;
@property(nonatomic) __weak UILabel *userCity; // @synthesize userCity=_userCity;
@property(nonatomic) __weak UIButton *setHomeButton; // @synthesize setHomeButton=_setHomeButton;
@property(retain, nonatomic) RACSubject *didPressSetHomeButton; // @synthesize didPressSetHomeButton=_didPressSetHomeButton;
- (void).cxx_destruct;
- (void)didPressButton:(id)arg1;
- (void)setUserCity:(id)arg1 country:(id)arg2;
- (void)viewDidLoad;
- (void)awakeFromNib;

@end

