//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JDLSWGJSONRequestSerializer : NSObject
{
}

+ (id)sharedInstance;
- (void)debugPrintRequest:(id)arg1 queryParameters:(id)arg2 body:(id)arg3;
- (void)addHMACToTheRequest:(id)arg1 withQueryParameters:(id)arg2 withBody:(id)arg3;
- (void)addDefaultHeadersToTheRequest:(id)arg1;
- (void)signRequest:(id)arg1 withQueryParameters:(id)arg2 withBody:(id)arg3;

@end

