//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableDictionary, NSString;

@interface JDLSWGApiClientMutableRequest : NSObject
{
    _Bool _anonymousRequest;
    _Bool _shouldRetryFailedRequest;
    _Bool _shouldRefreshTokenOnUnauthorized;
    NSString *_path;
    long long _methodType;
    NSString *_responseType;
    NSMutableDictionary *_pathParameters;
    NSMutableDictionary *_queryParameters;
    id _body;
    NSDictionary *_headerParameters;
}

@property(nonatomic) _Bool shouldRefreshTokenOnUnauthorized; // @synthesize shouldRefreshTokenOnUnauthorized=_shouldRefreshTokenOnUnauthorized;
@property(nonatomic) _Bool shouldRetryFailedRequest; // @synthesize shouldRetryFailedRequest=_shouldRetryFailedRequest;
@property(nonatomic) _Bool anonymousRequest; // @synthesize anonymousRequest=_anonymousRequest;
@property(retain, nonatomic) NSDictionary *headerParameters; // @synthesize headerParameters=_headerParameters;
@property(retain, nonatomic) id body; // @synthesize body=_body;
@property(readonly, nonatomic) NSMutableDictionary *queryParameters; // @synthesize queryParameters=_queryParameters;
@property(readonly, nonatomic) NSMutableDictionary *pathParameters; // @synthesize pathParameters=_pathParameters;
@property(copy, nonatomic) NSString *responseType; // @synthesize responseType=_responseType;
@property(nonatomic) long long methodType; // @synthesize methodType=_methodType;
@property(copy, nonatomic) NSString *path; // @synthesize path=_path;
- (void).cxx_destruct;
- (void)addPathParameterValue:(id)arg1 forKey:(id)arg2;
- (void)addQueryParameterValue:(id)arg1 forKey:(id)arg2;
- (id)initWithPath:(id)arg1 methodType:(long long)arg2 responseType:(id)arg3;

@end

