//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewController.h"

@class NSArray, RACSignal;

@interface JDLSuggestedChannelsCollection : UICollectionViewController
{
    NSArray *_localTrendChannels;
    RACSignal *_openMoreChannels;
}

@property(retain, nonatomic) RACSignal *openMoreChannels; // @synthesize openMoreChannels=_openMoreChannels;
@property(retain, nonatomic) NSArray *localTrendChannels; // @synthesize localTrendChannels=_localTrendChannels;
- (void).cxx_destruct;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (_Bool)isChannelCell:(id)arg1;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)viewDidLoad;
- (void)awakeFromNib;

@end

