//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JDLBaseTabViewController.h"

@class JDLChannelFeedFollowOverlay, JDLFeedBottomPullToRefresh, JDLFeedFullScreenPreview, JDLFeedPullToRefresh, JDLFeedTableViewSource, JDLLoadingTableView, JDLSubfeedViewModel, NSLayoutConstraint, NSString, UIButton, UIButtonTitleBeforeImage;

@interface JDLSubfeedViewController : JDLBaseTabViewController
{
    JDLSubfeedViewModel *_viewModel;
    NSString *_feedNavbarTitle;
    JDLLoadingTableView *_tableView;
    NSLayoutConstraint *_replyButtonHeight;
    UIButton *_replyButton;
    UIButtonTitleBeforeImage *_pinUnpinButton;
    JDLFeedPullToRefresh *_pullToRefreshControl;
    JDLFeedBottomPullToRefresh *_bottomPullToRefresh;
    JDLFeedTableViewSource *_tableSource;
    JDLFeedFullScreenPreview *_fullScreenPreview;
    JDLChannelFeedFollowOverlay *_followButtonOverlay;
}

@property(retain, nonatomic) JDLChannelFeedFollowOverlay *followButtonOverlay; // @synthesize followButtonOverlay=_followButtonOverlay;
@property(retain, nonatomic) JDLFeedFullScreenPreview *fullScreenPreview; // @synthesize fullScreenPreview=_fullScreenPreview;
@property(retain, nonatomic) JDLFeedTableViewSource *tableSource; // @synthesize tableSource=_tableSource;
@property(retain, nonatomic) JDLFeedBottomPullToRefresh *bottomPullToRefresh; // @synthesize bottomPullToRefresh=_bottomPullToRefresh;
@property(retain, nonatomic) JDLFeedPullToRefresh *pullToRefreshControl; // @synthesize pullToRefreshControl=_pullToRefreshControl;
@property(retain, nonatomic) UIButtonTitleBeforeImage *pinUnpinButton; // @synthesize pinUnpinButton=_pinUnpinButton;
@property(nonatomic) __weak UIButton *replyButton; // @synthesize replyButton=_replyButton;
@property(nonatomic) __weak NSLayoutConstraint *replyButtonHeight; // @synthesize replyButtonHeight=_replyButtonHeight;
@property(nonatomic) __weak JDLLoadingTableView *tableView; // @synthesize tableView=_tableView;
@property(copy, nonatomic) NSString *feedNavbarTitle; // @synthesize feedNavbarTitle=_feedNavbarTitle;
@property(retain, nonatomic) JDLSubfeedViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
- (void)refreshFollowState;
- (void)bottomNotificationJoinChannel:(id)arg1;
- (void)setupFollowButtonOverlay;
- (void)unwindFromPostCreation:(id)arg1;
- (void)replyPressed:(id)arg1;
- (void)scrollToBottomAnimated:(_Bool)arg1;
- (void)tryToAskPushPermissions;
- (void)pinUnpinToggleTap:(id)arg1;
- (void)refreshPinButton;
- (void)refreshAfterFetchSuccess:(id)arg1 scrollToBottom:(_Bool)arg2;
- (void)refreshSubfeedAndScrollToBottom:(_Bool)arg1;
- (void)fetchInitialDataWithScrollingToBottom:(_Bool)arg1;
- (_Bool)updateTitleAndCoordinatesWithNewLocation;
- (_Bool)displayKarmaValueOnNavigationBar;
- (void)notificationNoValidLocationFound:(id)arg1;
- (void)setupImagePreviewHandler;
- (void)setupPullToRefresh;
- (void)hideReplyButton;
- (void)setupTableView;
- (_Bool)prefersStatusBarHidden;
- (void)dealloc;
- (_Bool)hidesBottomBarWhenPushed;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)bindViewModel:(id)arg1;

@end

