//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class JDLStickyPostCellViewModel, NSString;

@protocol JDLStickyPostCellParentProtocol <NSObject>
- (void)openPostForStickyCellViewModel:(JDLStickyPostCellViewModel *)arg1 postId:(NSString *)arg2 postColor:(NSString *)arg3;
- (void)openChannelForStickyCellViewModel:(JDLStickyPostCellViewModel *)arg1 channel:(NSString *)arg2;
- (void)openHashtagForStickyCellViewModel:(JDLStickyPostCellViewModel *)arg1 hashtag:(NSString *)arg2;
- (void)voteStickyPostForCellViewModel:(JDLStickyPostCellViewModel *)arg1 upvote:(_Bool)arg2 completion:(void (^)(NSError *))arg3;
- (void)dismissStickyPostForCellViewModel:(JDLStickyPostCellViewModel *)arg1;
@end

