//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSString, RACSubject, UIButton, UIImageView, UILabel, UITapGestureRecognizer;

@interface JDLSetHomeTitleViewController : UIViewController
{
    _Bool _homeIsChosen;
    NSString *_locationName;
    NSString *_homeName;
    UIButton *_button;
    UILabel *_titleLabel;
    UIImageView *_iconImage;
    RACSubject *_didTapHomeStatus;
    UITapGestureRecognizer *_titleTapGestureRecognizer;
}

@property(retain, nonatomic) UITapGestureRecognizer *titleTapGestureRecognizer; // @synthesize titleTapGestureRecognizer=_titleTapGestureRecognizer;
@property(retain, nonatomic) RACSubject *didTapHomeStatus; // @synthesize didTapHomeStatus=_didTapHomeStatus;
@property(nonatomic) __weak UIImageView *iconImage; // @synthesize iconImage=_iconImage;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak UIButton *button; // @synthesize button=_button;
@property(copy, nonatomic) NSString *homeName; // @synthesize homeName=_homeName;
@property(copy, nonatomic) NSString *locationName; // @synthesize locationName=_locationName;
@property(nonatomic) _Bool homeIsChosen; // @synthesize homeIsChosen=_homeIsChosen;
- (void).cxx_destruct;
- (void)animateTextChangeFromTop:(_Bool)arg1;
- (void)enableHomeButton:(_Bool)arg1;
- (void)tappedHomeButton:(id)arg1;
- (void)updateTitleLabelAnimated:(_Bool)arg1;
- (void)viewDidLoad;

@end

