//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class JDLSuggestedChannelsCollection, RACSignal;

@interface JDLSuggestedChannelsCell : UITableViewCell
{
    RACSignal *_openMoreChannels;
    JDLSuggestedChannelsCollection *_channelsCollection;
}

@property(retain, nonatomic) JDLSuggestedChannelsCollection *channelsCollection; // @synthesize channelsCollection=_channelsCollection;
@property(retain, nonatomic) RACSignal *openMoreChannels; // @synthesize openMoreChannels=_openMoreChannels;
- (void).cxx_destruct;
- (void)configureWithLocalTrends:(id)arg1;
- (void)awakeFromNib;

@end

