//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UITabBarControllerDelegate.h"

@class NSString, UIViewController;

@interface JDLTabBarControllerDelegate : NSObject <UITabBarControllerDelegate>
{
    UIViewController *_lastSelectedViewController;
}

@property(nonatomic) __weak UIViewController *lastSelectedViewController; // @synthesize lastSelectedViewController=_lastSelectedViewController;
- (void).cxx_destruct;
- (void)tabBarController:(id)arg1 didSelectViewController:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

