//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIPageViewController.h"

#import "UIPageViewControllerDataSource.h"
#import "UIPageViewControllerDelegate.h"

@class JDLSetHomeTutorialViewController, NSArray, NSString, RACSignal;

@interface JDLTutorialPageController : UIPageViewController <UIPageViewControllerDataSource, UIPageViewControllerDelegate>
{
    _Bool _canSetNextPage;
    RACSignal *_didPressWantSetHome;
    RACSignal *_didChangePage;
    NSArray *_tutorialPages;
    JDLSetHomeTutorialViewController *_setHomeTutorialViewController;
}

@property(nonatomic) _Bool canSetNextPage; // @synthesize canSetNextPage=_canSetNextPage;
@property(retain, nonatomic) JDLSetHomeTutorialViewController *setHomeTutorialViewController; // @synthesize setHomeTutorialViewController=_setHomeTutorialViewController;
@property(retain, nonatomic) NSArray *tutorialPages; // @synthesize tutorialPages=_tutorialPages;
@property(retain, nonatomic) RACSignal *didChangePage; // @synthesize didChangePage=_didChangePage;
@property(retain, nonatomic) RACSignal *didPressWantSetHome; // @synthesize didPressWantSetHome=_didPressWantSetHome;
- (void).cxx_destruct;
- (void)pageViewController:(id)arg1 didFinishAnimating:(_Bool)arg2 previousViewControllers:(id)arg3 transitionCompleted:(_Bool)arg4;
- (id)pageViewController:(id)arg1 viewControllerBeforeViewController:(id)arg2;
- (id)pageViewController:(id)arg1 viewControllerAfterViewController:(id)arg2;
- (void)nextPage;
- (void)setUserCity:(id)arg1 country:(id)arg2;
- (void)didPressSetHome;
- (void)viewDidLoad;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

