//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CAShapeLayer, UIColor;

@interface JDLTriangleView : UIView
{
    CAShapeLayer *_triangleLayer;
    UIColor *_triangleColor;
}

@property(retain, nonatomic) UIColor *triangleColor; // @synthesize triangleColor=_triangleColor;
- (void).cxx_destruct;
- (void)flipTriangleHorizontally;
- (void)adjustTriangle;
- (void)layoutSubviews;

@end

