//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class JDLUserUUIDCloudService;

@interface JDLUserUUID : NSObject
{
    JDLUserUUIDCloudService *_cloudService;
}

+ (id)sharedInstance;
@property(retain, nonatomic) JDLUserUUIDCloudService *cloudService; // @synthesize cloudService=_cloudService;
- (void).cxx_destruct;
- (void)WIPEKeychainAndCloud;
- (void)trackUUIDGetWithSubject:(id)arg1 uuid:(id)arg2 subItem:(id)arg3;
- (void)trackCloudStatus:(id)arg1;
- (void)trackICloudUuidsStatus;
- (void)trackUUIDStatus;
- (void)syncToCloud;
- (_Bool)storeUuidToCloud:(id)arg1 override:(_Bool)arg2;
- (_Bool)isCloudUuidSyncEnabled;
- (void)setCloudUuidSyncEnabled:(_Bool)arg1;
- (id)hashedUUID;
- (void)saveCurrentUuid:(id)arg1;
- (id)uuidForDevice;
- (id)uuid;
- (id)init;

@end

