//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JDLNetworkCheckingBaseViewController.h"

#import "UIScrollViewDelegate.h"
#import "WKUIWebViewDelegate.h"

@class JDLLoadingWebView, NSString, NSURL, UIButton, UIColor;

@interface JDLWebViewControllerWithButton : JDLNetworkCheckingBaseViewController <UIScrollViewDelegate, WKUIWebViewDelegate>
{
    float _acceptButtonHeight;
    UIColor *_backgroundColor;
    NSString *_acceptButtonTitle;
    NSString *_acceptButtonIdentifier;
    UIColor *_acceptButtonTitleColor;
    CDUnknownBlockType _acceptCompletion;
    JDLLoadingWebView *_webView;
    UIButton *_rulesAcceptButton;
    NSURL *_requestURL;
}

@property(copy, nonatomic) NSURL *requestURL; // @synthesize requestURL=_requestURL;
@property(retain, nonatomic) UIButton *rulesAcceptButton; // @synthesize rulesAcceptButton=_rulesAcceptButton;
@property(retain, nonatomic) JDLLoadingWebView *webView; // @synthesize webView=_webView;
@property(copy, nonatomic) CDUnknownBlockType acceptCompletion; // @synthesize acceptCompletion=_acceptCompletion;
@property(nonatomic) float acceptButtonHeight; // @synthesize acceptButtonHeight=_acceptButtonHeight;
@property(retain, nonatomic) UIColor *acceptButtonTitleColor; // @synthesize acceptButtonTitleColor=_acceptButtonTitleColor;
@property(copy, nonatomic) NSString *acceptButtonIdentifier; // @synthesize acceptButtonIdentifier=_acceptButtonIdentifier;
@property(copy, nonatomic) NSString *acceptButtonTitle; // @synthesize acceptButtonTitle=_acceptButtonTitle;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
- (void).cxx_destruct;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)acceptPressed:(id)arg1;
- (void)setupViews;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithURL:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

