//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView, UILabel;

@interface JTImageLabel : UIView
{
    UILabel *_textLabel;
    UIImageView *_imageView;
    double _space;
    double _leftOffset;
}

@property(nonatomic) double leftOffset; // @synthesize leftOffset=_leftOffset;
@property(nonatomic) double space; // @synthesize space=_space;
@property(readonly, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(readonly, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)commonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

