//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDate.h"

@interface NSDate (ISO8601)
+ (id)dateWithISO8601String:(id)arg1 timeZone:(inout id *)arg2 usingCalendar:(id)arg3;
+ (id)dateWithISO8601String:(id)arg1;
- (id)ISO8601StringWithTimeZone:(id)arg1 usingCalendar:(id)arg2;
- (id)ISO8601String;
@end

