//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (JDLAttributedString)
- (id)attributedGothamBoldWithSize:(double)arg1 lineHeight:(double)arg2;
- (id)attributedGothamBookWithSize:(double)arg1 lineHeight:(double)arg2;
- (id)attributedStringWithBuilderBlock:(CDUnknownBlockType)arg1;
@end

