//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber;

@interface RLTAnalyticsViewControllerPageLifetimeBean : NSObject
{
    id _controller;
    NSNumber *_didAppearTime;
}

@property(retain, nonatomic) NSNumber *didAppearTime; // @synthesize didAppearTime=_didAppearTime;
@property(nonatomic) __weak id controller; // @synthesize controller=_controller;
- (void).cxx_destruct;
- (id)initWithController:(id)arg1 didAppearTime:(id)arg2;

@end

