//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIControl, UIViewController;

@protocol RLTAnalyticsBModuleButtonWrapperProtocol <NSObject>
@property(readonly, nonatomic) UIViewController *parentViewController;
@property(readonly, copy, nonatomic) NSString *label;
@property(readonly, nonatomic) UIControl *instance;
@end

