//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol RLTAnalyticsRegistryProtocol <NSObject>
@property(readonly, nonatomic) id <RLTAnalyticsModuleManagerProtocol> moduleManager;
- (_Bool)stopModuleWithType:(long long)arg1 error:(id *)arg2;
- (_Bool)startModuleWithType:(long long)arg1 error:(id *)arg2;
- (_Bool)hasModuleWithType:(long long)arg1;
- (_Bool)addModule:(id <RLTAnalyticsModuleProtocol>)arg1 error:(id *)arg2;
- (void)startOrStopModules;
- (void)createAndRegisterModuleWithType:(long long)arg1 moduleProviderBlock:(id <RLTAnalyticsModuleProtocol> (^)(void))arg2;
@end

