//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RLTAnalyticsPermanentSwizzlingModule.h"

#import "RLTAnalyticsButtonsModuleProtocol.h"
#import "RLTAnalyticsPermanentSwizzlingModuleDelegate.h"

@class NSString;

@interface RLTAnalyticsButtonsModule : RLTAnalyticsPermanentSwizzlingModule <RLTAnalyticsPermanentSwizzlingModuleDelegate, RLTAnalyticsButtonsModuleProtocol>
{
    id <RLTAnalyticsButtonsModuleDelegate> _delegate;
}

+ (void)performPermanentSwizzleWithModuleManager:(id)arg1;
@property(retain, nonatomic) id <RLTAnalyticsButtonsModuleDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)handleUIButtonTap:(id)arg1;
- (void)messageReceived:(id)arg1 ofType:(id)arg2;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

