//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RLTAnalyticsRegistryDelegateProtocol.h"
#import "RLTAnalyticsRegistryProtocol.h"

@class NSString;

@interface RLTAnalyticsRegistry : NSObject <RLTAnalyticsRegistryDelegateProtocol, RLTAnalyticsRegistryProtocol>
{
    id <RLTAnalyticsModuleManagerProtocol> _moduleManager;
    id <RLTAnalyticsConfigurationProtocol> _configuration;
    id <RLTAnalyticsRegistryDelegateProtocol> _delegate;
}

@property(nonatomic) __weak id <RLTAnalyticsRegistryDelegateProtocol> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) id <RLTAnalyticsConfigurationProtocol> configuration; // @synthesize configuration=_configuration;
@property(retain, nonatomic) id <RLTAnalyticsModuleManagerProtocol> moduleManager; // @synthesize moduleManager=_moduleManager;
- (void).cxx_destruct;
- (void)analytics:(id)arg1 moduleStoppedWithType:(long long)arg2 error:(id)arg3;
- (void)analytics:(id)arg1 moduleStartedWithType:(long long)arg2 error:(id)arg3;
- (void)analytics:(id)arg1 moduleCreatedAndRegisteredWithType:(long long)arg2 error:(id)arg3;
- (void)startOrStopModuleWithType:(long long)arg1;
- (_Bool)stopModuleWithType:(long long)arg1 error:(id *)arg2;
- (_Bool)startModuleWithType:(long long)arg1 error:(id *)arg2;
- (_Bool)hasModuleWithType:(long long)arg1;
- (_Bool)addModule:(id)arg1 error:(id *)arg2;
- (void)startOrStopModules;
- (void)createAndRegisterModuleWithType:(long long)arg1 moduleProviderBlock:(CDUnknownBlockType)arg2;
- (id)initWithModuleManager:(id)arg1 configuration:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

