//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol RLTAnalyticsDelegate <NSObject>

@optional
- (void)analyticsTrackButtonTapWithEventName:(NSString *)arg1 label:(NSString *)arg2 contentName:(NSString *)arg3;
- (void)analyticsTrackContentViewWithEventName:(NSString *)arg1 content:(NSString *)arg2;
- (void)analyticsTrackNavigationWithEventName:(NSString *)arg1 from:(NSString *)arg2 to:(NSString *)arg3 navigationMethod:(NSString *)arg4 duration:(unsigned long long)arg5;
- (void)analyticsTrackSessionInfoWithEventName:(NSString *)arg1 info:(NSString *)arg2 status:(NSString *)arg3 appPreviousVersion:(NSString *)arg4;
- (void)analyticsTrackSessionTimeWithEventName:(NSString *)arg1 time:(unsigned long long)arg2;
- (void)analyticsTrackSessionWithEventName:(NSString *)arg1 type:(NSString *)arg2 appPreviousVersion:(NSString *)arg3;
@end

