//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIViewController;

@protocol RLTAnalyticsViewControllersModuleDelegate <NSObject>
- (void)viewControllersModule:(id <RLTAnalyticsModuleProtocol>)arg1 navigationStackChangedFrom:(UIViewController *)arg2 to:(UIViewController *)arg3 withDurationOnPreviousPage:(double)arg4 method:(long long)arg5;
- (void)viewControllersModule:(id <RLTAnalyticsModuleProtocol>)arg1 viewControllerDidAppear:(UIViewController *)arg2;

@optional
- (void)viewControllersModule:(id <RLTAnalyticsModuleProtocol>)arg1 didDisappearSameControllerSkipped:(UIViewController *)arg2;
- (void)viewControllersModule:(id <RLTAnalyticsModuleProtocol>)arg1 didDisappearChildControllerSkipped:(UIViewController *)arg2;
- (void)viewControllersModule:(id <RLTAnalyticsModuleProtocol>)arg1 didAppearSameControllerSkipped:(UIViewController *)arg2;
- (void)viewControllersModule:(id <RLTAnalyticsModuleProtocol>)arg1 didAppearChildControllerSkipped:(UIViewController *)arg2;
- (void)viewControllersModule:(id <RLTAnalyticsModuleProtocol>)arg1 willAppearChildControllerSkipped:(UIViewController *)arg2;
@end

