//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RLTAnalyticsModuleManagerProtocol.h"

@class NSMutableDictionary, NSString;

@interface RLTAnalyticsModuleManager : NSObject <RLTAnalyticsModuleManagerProtocol>
{
    NSMutableDictionary *_modules;
    double _applicationStartTime;
}

@property(nonatomic) double applicationStartTime; // @synthesize applicationStartTime=_applicationStartTime;
@property(retain, nonatomic) NSMutableDictionary *modules; // @synthesize modules=_modules;
- (void).cxx_destruct;
- (_Bool)isModuleEnabled:(long long)arg1;
- (void)sendMessage:(id)arg1 forModule:(long long)arg2 ofType:(id)arg3;
- (_Bool)registerModule:(id)arg1 error:(id *)arg2;
- (id)moduleWithType:(long long)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

