//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol RLTAnalyticsApplicationSessionModuleDelegate <NSObject>
- (void)applicationSessionModule:(id <RLTAnalyticsModuleProtocol>)arg1 applicationColdStartWithType:(long long)arg2 appPreviousVersion:(NSString *)arg3;
- (void)applicationSessionModule:(id <RLTAnalyticsModuleProtocol>)arg1 applicationSessionBeingInBackgroundInterval:(double)arg2;
- (void)applicationSessionModule:(id <RLTAnalyticsModuleProtocol>)arg1 applicationDidEnterBackgroundWithSessionInterval:(double)arg2;
@end

