//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol RLTAnalyticsModuleManagerProtocol <NSObject>
@property(readonly, nonatomic) double applicationStartTime;
- (_Bool)isModuleEnabled:(long long)arg1;
- (void)sendMessage:(id)arg1 forModule:(long long)arg2 ofType:(id)arg3;
- (_Bool)registerModule:(id <RLTAnalyticsModuleProtocol>)arg1 error:(id *)arg2;
- (id <RLTAnalyticsModuleProtocol>)moduleWithType:(long long)arg1;
@end

