//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RLTConfigControllerProtocol.h"

@class NSString, RLTConfigParser;

@interface RLTConfigController : NSObject <RLTConfigControllerProtocol>
{
    id <RLTConfigStorageProtocol> _storageAdapter;
    id <RLTConfigSyncProtocol> _syncManager;
    RLTConfigParser *_parser;
}

@property(retain, nonatomic) RLTConfigParser *parser; // @synthesize parser=_parser;
@property(retain, nonatomic) id <RLTConfigSyncProtocol> syncManager; // @synthesize syncManager=_syncManager;
@property(retain, nonatomic) id <RLTConfigStorageProtocol> storageAdapter; // @synthesize storageAdapter=_storageAdapter;
- (void).cxx_destruct;
- (void)fetch:(CDUnknownBlockType)arg1;
- (long long)getCurrentUpdateId;
- (void)resetCurrentUpdateId;
- (void)setCurrentUpdateId:(long long)arg1;
- (id)refreshStoredConfigWithNewConfig:(id)arg1;
- (void)storeConfig:(id)arg1;
- (id)currentConfig;
- (id)initWithStorage:(id)arg1 syncManager:(id)arg2 parser:(id)arg3;
- (id)initWithConfiguration:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

