//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RLTConfigSyncProtocol.h"

@class NSString, RLTConfigConfiguration;

@interface RLTConfigSyncRestManager : NSObject <RLTConfigSyncProtocol>
{
    _Bool _inProgress;
    RLTConfigConfiguration *_configuration;
    NSString *_urlTemplate;
}

@property(nonatomic) _Bool inProgress; // @synthesize inProgress=_inProgress;
@property(copy, nonatomic) NSString *urlTemplate; // @synthesize urlTemplate=_urlTemplate;
@property(retain, nonatomic) RLTConfigConfiguration *configuration; // @synthesize configuration=_configuration;
- (void).cxx_destruct;
- (void)fetchConfigFromTheServer:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (id)buildRequestURLForUpdateId:(long long)arg1;
- (void)buildURL;
- (id)initWithConfiguration:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

