//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString, RLTLocalizationAppStateHookService, RLTLocalizationController;

@interface RLTLocalization : NSObject
{
    NSObject *_lock;
    RLTLocalizationController *_controller;
    NSDictionary *_currentLanguageData;
    RLTLocalizationAppStateHookService *_taskPerformer;
    NSString *_currentLanguage;
}

+ (id)sharedInstance;
+ (id)startWithConfiguration:(id)arg1;
+ (id)startWithServerURLString:(id)arg1;
@property(copy, nonatomic) NSString *currentLanguage; // @synthesize currentLanguage=_currentLanguage;
@property(retain, nonatomic) RLTLocalizationAppStateHookService *taskPerformer; // @synthesize taskPerformer=_taskPerformer;
@property(retain, nonatomic) NSDictionary *currentLanguageData; // @synthesize currentLanguageData=_currentLanguageData;
@property(retain, nonatomic) RLTLocalizationController *controller; // @synthesize controller=_controller;
@property(retain, nonatomic) NSObject *lock; // @synthesize lock=_lock;
- (void).cxx_destruct;
- (void)cleanup;
- (void)fetchAsync;
- (void)registerForEvents;
- (id)localizedStringForKey:(id)arg1;
- (id)initWithLocalizationController:(id)arg1;
- (id)initWithConfiguration:(id)arg1;

@end

