//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, NSURL;

@protocol RLTLocalizationDelegate <NSObject>

@optional
- (void)rltLocalizationParsedWithDuration:(unsigned long long)arg1;
- (void)rltLocalizationFetchedFromServerWithDuration:(unsigned long long)arg1;
- (void)rltLocalizationFetchingFromServerFailedWithError:(NSError *)arg1;
- (void)rltLocalizationFetchingFromServerStartedWithURL:(NSURL *)arg1;
- (void)rltLocalizationFetchingFromServerSkippedWithError:(NSError *)arg1;
- (void)rltLocalizationFetchingFromServerSkipped;
@end

