//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface RLTLocalizationLocaleProvider : NSObject
{
}

- (id)requestLocalesWithDefaultLanguage:(id)arg1;
- (id)localeWithUnderscore:(id)arg1;
- (id)availableNormalizedLocaleCodes;
- (id)normalizedLanguageCode:(id)arg1;
- (id)preferredLanguages;
- (id)currentLanguage;
- (id)currentLanguageWithFallbackToDefault:(id)arg1 supportedLanguages:(id)arg2;

@end

