//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, RLTLocalizationConfiguration;

@interface RLTLocalizationRestManager : NSObject
{
    _Bool _inProgress;
    RLTLocalizationConfiguration *_configuration;
    NSString *_urlTemplate;
}

@property(nonatomic) _Bool inProgress; // @synthesize inProgress=_inProgress;
@property(copy, nonatomic) NSString *urlTemplate; // @synthesize urlTemplate=_urlTemplate;
@property(retain, nonatomic) RLTLocalizationConfiguration *configuration; // @synthesize configuration=_configuration;
- (void).cxx_destruct;
- (void)fetchLocalizationForUpdateId:(id)arg1 priorityLocales:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)buildRequestURLForUpdateId:(id)arg1 locales:(id)arg2;
- (void)buildURL;
- (id)initWithConfiguration:(id)arg1;

@end

