//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RLTStatsCollectorDelegate.h"

@class NSDictionary, NSString;

@protocol RLTStatsDelegate <RLTStatsCollectorDelegate>

@optional
- (void)trackActivity:(NSString *)arg1 type:(NSString *)arg2 subtype:(NSString *)arg3;
- (void)trackEvent:(NSString *)arg1 attributes:(NSDictionary *)arg2 status:(long long)arg3 duration:(unsigned long long)arg4;
@end

