//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURLSession, RLTStatsReachability;

@interface RLTStatsConfiguration : NSObject
{
    _Bool _dryRun;
    NSString *_applicationId;
    NSString *_clientId;
    NSString *_uniqueId;
    double _flushTimeInterval;
    long long _serializerVersion;
    NSURLSession *_urlSession;
    RLTStatsReachability *_statsReachability;
}

@property(retain, nonatomic) RLTStatsReachability *statsReachability; // @synthesize statsReachability=_statsReachability;
@property(nonatomic) _Bool dryRun; // @synthesize dryRun=_dryRun;
@property(retain, nonatomic) NSURLSession *urlSession; // @synthesize urlSession=_urlSession;
@property(nonatomic) long long serializerVersion; // @synthesize serializerVersion=_serializerVersion;
@property(nonatomic) double flushTimeInterval; // @synthesize flushTimeInterval=_flushTimeInterval;
@property(copy, nonatomic) NSString *uniqueId; // @synthesize uniqueId=_uniqueId;
@property(copy, nonatomic) NSString *clientId; // @synthesize clientId=_clientId;
@property(copy, nonatomic) NSString *applicationId; // @synthesize applicationId=_applicationId;
- (void).cxx_destruct;
- (long long)reachabilityStatus;
- (id)metaInformation;
- (id)initWithApplicationId:(id)arg1;

@end

