//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RLTStatsDispatchObject.h"

@class NSString;

@interface RLTStatsActivity : NSObject <RLTStatsDispatchObject>
{
    NSString *_name;
    NSString *_type;
    NSString *_subType;
}

@property(copy, nonatomic) NSString *subType; // @synthesize subType=_subType;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)dictionaryRepresentationWithConfiguration:(id)arg1;
- (id)initWithName:(id)arg1 type:(id)arg2 subType:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

