//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, SWGApiClient;

@protocol SWGApi <NSObject>
@property(nonatomic) SWGApiClient *apiClient;
- (unsigned long long)requestQueueSize;
- (NSString *)defaultHeaderForKey:(NSString *)arg1;
- (void)setDefaultHeaderValue:(NSString *)arg1 forKey:(NSString *)arg2;
- (void)addHeader:(NSString *)arg1 forKey:(NSString *)arg2;
- (id)initWithApiClient:(SWGApiClient *)arg1;
@end

