//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SWGObject.h"

@class NSArray<SWGPost>, NSArray<SWGStickypost>, NSNumber;

@interface SWGComboPostsWithStickies : SWGObject
{
    NSArray<SWGPost> *_recent;
    NSArray<SWGPost> *_replied;
    NSArray<SWGPost> *_voted;
    NSArray<SWGStickypost> *_stickies;
    NSNumber *_max;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
@property(retain, nonatomic) NSNumber *max; // @synthesize max=_max;
@property(retain, nonatomic) NSArray<SWGStickypost> *stickies; // @synthesize stickies=_stickies;
@property(retain, nonatomic) NSArray<SWGPost> *voted; // @synthesize voted=_voted;
@property(retain, nonatomic) NSArray<SWGPost> *replied; // @synthesize replied=_replied;
@property(retain, nonatomic) NSArray<SWGPost> *recent; // @synthesize recent=_recent;
- (void).cxx_destruct;
- (id)init;

@end

