//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SWGObject.h"

@class NSString, SWGCustomObject;

@interface SWGError : SWGObject
{
    NSString *_error;
    SWGCustomObject *_metadata;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
@property(retain, nonatomic) SWGCustomObject *metadata; // @synthesize metadata=_metadata;
@property(retain, nonatomic) NSString *error; // @synthesize error=_error;
- (void).cxx_destruct;
- (id)init;
- (id)getLocalisationKey;

@end

