//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SWGObject.h"

@class NSNumber;

@interface SWGFlagRequest : SWGObject
{
    NSNumber *_reasonId;
    NSNumber *_subreasonId;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
@property(retain, nonatomic) NSNumber *subreasonId; // @synthesize subreasonId=_subreasonId;
@property(retain, nonatomic) NSNumber *reasonId; // @synthesize reasonId=_reasonId;
- (void).cxx_destruct;
- (id)init;

@end

