//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SWGObject.h"

@class NSNumber, NSString, SWGCoordinates;

@interface SWGLocationMin : SWGObject
{
    SWGCoordinates *_locCoordinates;
    NSNumber *_locAccuracy;
    NSString *_city;
    NSString *_country;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
@property(retain, nonatomic) NSString *country; // @synthesize country=_country;
@property(retain, nonatomic) NSString *city; // @synthesize city=_city;
@property(retain, nonatomic) NSNumber *locAccuracy; // @synthesize locAccuracy=_locAccuracy;
@property(retain, nonatomic) SWGCoordinates *locCoordinates; // @synthesize locCoordinates=_locCoordinates;
- (void).cxx_destruct;
- (id)init;

@end

