//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSFileHandle, NSString;

@interface SWGLogger : NSObject
{
    _Bool _enabled;
    NSString *_loggingFile;
    NSFileHandle *_loggingFileHandler;
}

+ (id)sharedLogger;
@property(readonly, nonatomic) NSFileHandle *loggingFileHandler; // @synthesize loggingFileHandler=_loggingFileHandler;
@property(retain, nonatomic) NSString *loggingFile; // @synthesize loggingFile=_loggingFile;
@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
- (void).cxx_destruct;
- (void)logResponse:(id)arg1 responseObject:(id)arg2 request:(id)arg3 error:(id)arg4;
- (void)debugLog:(id)arg1 message:(id)arg2;

@end

