//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SWGObject.h"

@class NSArray<SWGModerationPost>, SWGModerationPostsBounty;

@interface SWGModerationPosts : SWGObject
{
    NSArray<SWGModerationPost> *_posts;
    SWGModerationPostsBounty *_bounty;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
@property(retain, nonatomic) SWGModerationPostsBounty *bounty; // @synthesize bounty=_bounty;
@property(retain, nonatomic) NSArray<SWGModerationPost> *posts; // @synthesize posts=_posts;
- (void).cxx_destruct;
- (id)init;

@end

