//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SWGObject.h"

@class NSArray<SWGPost>, NSNumber, NSString, SWGLocation;

@interface SWGPost : SWGObject
{
    NSString *_postId;
    NSString *_createdAt;
    NSString *_updatedAt;
    NSString *_message;
    NSArray<SWGPost> *_children;
    NSNumber *_childCount;
    NSString *_creator;
    NSNumber *_distance;
    NSString *_postOwn;
    NSNumber *_parentCreator;
    NSNumber *_voteCount;
    NSString *_voted;
    NSNumber *_pinned;
    NSNumber *_pinCount;
    NSNumber *_notificationsEnabled;
    NSNumber *_discovered;
    NSNumber *_discoveredBy;
    NSString *_imageUrl;
    NSString *_thumbnailUrl;
    SWGLocation *_location;
    NSString *_color;
    NSString *_userHandle;
    NSNumber *_fromHome;
    NSNumber *_gotThanks;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
@property(retain, nonatomic) NSNumber *gotThanks; // @synthesize gotThanks=_gotThanks;
@property(retain, nonatomic) NSNumber *fromHome; // @synthesize fromHome=_fromHome;
@property(retain, nonatomic) NSString *userHandle; // @synthesize userHandle=_userHandle;
@property(retain, nonatomic) NSString *color; // @synthesize color=_color;
@property(retain, nonatomic) SWGLocation *location; // @synthesize location=_location;
@property(retain, nonatomic) NSString *thumbnailUrl; // @synthesize thumbnailUrl=_thumbnailUrl;
@property(retain, nonatomic) NSString *imageUrl; // @synthesize imageUrl=_imageUrl;
@property(retain, nonatomic) NSNumber *discoveredBy; // @synthesize discoveredBy=_discoveredBy;
@property(retain, nonatomic) NSNumber *discovered; // @synthesize discovered=_discovered;
@property(retain, nonatomic) NSNumber *notificationsEnabled; // @synthesize notificationsEnabled=_notificationsEnabled;
@property(retain, nonatomic) NSNumber *pinCount; // @synthesize pinCount=_pinCount;
@property(retain, nonatomic) NSNumber *pinned; // @synthesize pinned=_pinned;
@property(retain, nonatomic) NSString *voted; // @synthesize voted=_voted;
@property(retain, nonatomic) NSNumber *voteCount; // @synthesize voteCount=_voteCount;
@property(retain, nonatomic) NSNumber *parentCreator; // @synthesize parentCreator=_parentCreator;
@property(retain, nonatomic) NSString *postOwn; // @synthesize postOwn=_postOwn;
@property(retain, nonatomic) NSNumber *distance; // @synthesize distance=_distance;
@property(retain, nonatomic) NSString *creator; // @synthesize creator=_creator;
@property(retain, nonatomic) NSNumber *childCount; // @synthesize childCount=_childCount;
@property(retain, nonatomic) NSArray<SWGPost> *children; // @synthesize children=_children;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
@property(retain, nonatomic) NSString *updatedAt; // @synthesize updatedAt=_updatedAt;
@property(retain, nonatomic) NSString *createdAt; // @synthesize createdAt=_createdAt;
@property(retain, nonatomic) NSString *postId; // @synthesize postId=_postId;
- (void).cxx_destruct;
- (id)init;
- (_Bool)isPinned;
- (_Bool)isEqual:(id)arg1;
- (_Bool)votedAlreadyOnJodel;
- (_Bool)votedDown;
- (_Bool)votedUp;
- (id)replyCount;
- (_Bool)hasReplies;
- (long long)contentType;
- (id)locationName;
- (_Bool)containsImage;
- (_Bool)isMyJodel;

@end

