//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SWGObject.h"

@class NSNumber;

@interface SWGPinCount : SWGObject
{
    NSNumber *_pinCount;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
@property(retain, nonatomic) NSNumber *pinCount; // @synthesize pinCount=_pinCount;
- (void).cxx_destruct;
- (id)init;

@end

