//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SWGResponseDeserializer.h"

@class NSArray, NSNumberFormatter, NSRegularExpression, NSString;

@interface SWGResponseDeserializer : NSObject <SWGResponseDeserializer>
{
    _Bool _treatNullAsError;
    NSNumberFormatter *_numberFormatter;
    NSArray *_primitiveTypes;
    NSArray *_basicReturnTypes;
    NSRegularExpression *_arrayOfModelsPatExpression;
    NSRegularExpression *_arrayOfPrimitivesPatExpression;
    NSRegularExpression *_dictPatExpression;
    NSRegularExpression *_dictModelsPatExpression;
}

@property(retain, nonatomic) NSRegularExpression *dictModelsPatExpression; // @synthesize dictModelsPatExpression=_dictModelsPatExpression;
@property(retain, nonatomic) NSRegularExpression *dictPatExpression; // @synthesize dictPatExpression=_dictPatExpression;
@property(retain, nonatomic) NSRegularExpression *arrayOfPrimitivesPatExpression; // @synthesize arrayOfPrimitivesPatExpression=_arrayOfPrimitivesPatExpression;
@property(retain, nonatomic) NSRegularExpression *arrayOfModelsPatExpression; // @synthesize arrayOfModelsPatExpression=_arrayOfModelsPatExpression;
@property(retain, nonatomic) NSArray *basicReturnTypes; // @synthesize basicReturnTypes=_basicReturnTypes;
@property(retain, nonatomic) NSArray *primitiveTypes; // @synthesize primitiveTypes=_primitiveTypes;
@property(retain, nonatomic) NSNumberFormatter *numberFormatter; // @synthesize numberFormatter=_numberFormatter;
@property(nonatomic) _Bool treatNullAsError; // @synthesize treatNullAsError=_treatNullAsError;
- (void).cxx_destruct;
- (id)unknownResponseErrorWithExpectedType:(id)arg1 data:(id)arg2;
- (id)emptyValueOccurredError;
- (id)typeMismatchErrorWithExpectedType:(id)arg1 data:(id)arg2;
- (id)deserializeDateValue:(id)arg1 error:(id *)arg2;
- (id)deserializePrimitiveValue:(id)arg1 class:(id)arg2 error:(id *)arg3;
- (id)deserializeArrayValue:(id)arg1 innerType:(id)arg2 error:(id *)arg3;
- (id)deserializeDictionaryValue:(id)arg1 valueType:(id)arg2 error:(id *)arg3;
- (id)deserialize:(id)arg1 class:(id)arg2 error:(id *)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

