//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SWGObject.h"

@class NSArray<SWGChannelWithRecommendation>;

@interface SWGRecommendedChannels : SWGObject
{
    NSArray<SWGChannelWithRecommendation> *_recommended;
    NSArray<SWGChannelWithRecommendation> *_local;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
@property(retain, nonatomic) NSArray<SWGChannelWithRecommendation> *local; // @synthesize local=_local;
@property(retain, nonatomic) NSArray<SWGChannelWithRecommendation> *recommended; // @synthesize recommended=_recommended;
- (void).cxx_destruct;
- (id)init;

@end

