//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SWGObject.h"

@class NSString;

@interface SWGRefreshTokenRequest : SWGObject
{
    NSString *_refreshToken;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
+ (id)storedCredentials;
@property(retain, nonatomic) NSString *refreshToken; // @synthesize refreshToken=_refreshToken;
- (void).cxx_destruct;
- (id)init;

@end

