//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SWGObject.h"

@class NSNumber, NSString;

@interface SWGRefreshTokenResponse : SWGObject
{
    NSString *_accessToken;
    NSNumber *_expirationDate;
    NSNumber *_expiresIn;
    NSString *_tokenType;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
@property(retain, nonatomic) NSString *tokenType; // @synthesize tokenType=_tokenType;
@property(retain, nonatomic) NSNumber *expiresIn; // @synthesize expiresIn=_expiresIn;
@property(retain, nonatomic) NSNumber *expirationDate; // @synthesize expirationDate=_expirationDate;
@property(retain, nonatomic) NSString *accessToken; // @synthesize accessToken=_accessToken;
- (void).cxx_destruct;
- (id)init;

@end

