//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SWGObject.h"

@class NSString;

@interface SWGStickypost : SWGObject
{
    NSString *_stickypostId;
    NSString *_message;
    NSString *_type;
    NSString *_color;
    NSString *_linkColor;
    NSString *_locationName;
    NSString *_link;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
@property(retain, nonatomic) NSString *link; // @synthesize link=_link;
@property(retain, nonatomic) NSString *locationName; // @synthesize locationName=_locationName;
@property(retain, nonatomic) NSString *linkColor; // @synthesize linkColor=_linkColor;
@property(retain, nonatomic) NSString *color; // @synthesize color=_color;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
@property(retain, nonatomic) NSString *stickypostId; // @synthesize stickypostId=_stickypostId;
- (void).cxx_destruct;
- (id)init;

@end

