//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SWGObject.h"

@class NSArray, NSArray<SWGExperiment>, NSNumber, NSString;

@interface SWGUserConfig : SWGObject
{
    NSNumber *_moderator;
    NSString *_userType;
    NSArray<SWGExperiment> *_experiments;
    NSArray *_followedChannels;
    NSNumber *_channelsFollowLimit;
    NSNumber *_tripleFeedEnabled;
    NSNumber *_homeSet;
    NSString *_homeName;
    NSString *_location;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
@property(retain, nonatomic) NSString *location; // @synthesize location=_location;
@property(retain, nonatomic) NSString *homeName; // @synthesize homeName=_homeName;
@property(retain, nonatomic) NSNumber *homeSet; // @synthesize homeSet=_homeSet;
@property(retain, nonatomic) NSNumber *tripleFeedEnabled; // @synthesize tripleFeedEnabled=_tripleFeedEnabled;
@property(retain, nonatomic) NSNumber *channelsFollowLimit; // @synthesize channelsFollowLimit=_channelsFollowLimit;
@property(retain, nonatomic) NSArray *followedChannels; // @synthesize followedChannels=_followedChannels;
@property(retain, nonatomic) NSArray<SWGExperiment> *experiments; // @synthesize experiments=_experiments;
@property(retain, nonatomic) NSString *userType; // @synthesize userType=_userType;
@property(retain, nonatomic) NSNumber *moderator; // @synthesize moderator=_moderator;
- (void).cxx_destruct;
- (id)init;

@end

