//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SWGObject.h"

@class NSNumber;

@interface SWGUserModeration : SWGObject
{
    NSNumber *_moderator;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
@property(retain, nonatomic) NSNumber *moderator; // @synthesize moderator=_moderator;
- (void).cxx_destruct;
- (id)init;

@end

