//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, TLMAVCamCaptureManager, UIImage;

@protocol TLMAVCamCaptureManagerDelegate <NSObject>

@optional
- (void)captureManagerDeviceConfigurationChanged:(TLMAVCamCaptureManager *)arg1;
- (void)captureManagerStillImageCaptured:(TLMAVCamCaptureManager *)arg1 image:(UIImage *)arg2;
- (void)captureManagerRecordingFinished:(TLMAVCamCaptureManager *)arg1;
- (void)captureManagerRecordingBegan:(TLMAVCamCaptureManager *)arg1;
- (void)captureManager:(TLMAVCamCaptureManager *)arg1 didFailWithError:(NSError *)arg2;
@end

