//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TLMAVCamRecorderDelegate.h"

@class AVCaptureDeviceInput, AVCaptureSession, AVCaptureStillImageOutput, TLMAVCamRecorder;

@interface TLMAVCamCaptureManager : NSObject <TLMAVCamRecorderDelegate>
{
    AVCaptureSession *session;
    long long orientation;
    AVCaptureDeviceInput *videoInput;
    AVCaptureDeviceInput *audioInput;
    AVCaptureStillImageOutput *stillImageOutput;
    TLMAVCamRecorder *recorder;
    id deviceConnectedObserver;
    id deviceDisconnectedObserver;
    unsigned long long backgroundRecordingID;
    id <TLMAVCamCaptureManagerDelegate> delegate;
    double _effectiveScale;
}

@property(nonatomic) double effectiveScale; // @synthesize effectiveScale=_effectiveScale;
@property(nonatomic) id <TLMAVCamCaptureManagerDelegate> delegate; // @synthesize delegate;
@property(nonatomic) unsigned long long backgroundRecordingID; // @synthesize backgroundRecordingID;
@property(nonatomic) id deviceDisconnectedObserver; // @synthesize deviceDisconnectedObserver;
@property(nonatomic) id deviceConnectedObserver; // @synthesize deviceConnectedObserver;
@property(retain, nonatomic) TLMAVCamRecorder *recorder; // @synthesize recorder;
@property(retain, nonatomic) AVCaptureStillImageOutput *stillImageOutput; // @synthesize stillImageOutput;
@property(retain, nonatomic) AVCaptureDeviceInput *audioInput; // @synthesize audioInput;
@property(retain, nonatomic) AVCaptureDeviceInput *videoInput; // @synthesize videoInput;
@property(nonatomic) long long orientation; // @synthesize orientation;
@property(retain, nonatomic) AVCaptureSession *session; // @synthesize session;
- (void).cxx_destruct;
- (void)continuousFocusAtPoint:(struct CGPoint)arg1;
- (void)autoFocusAtPoint:(struct CGPoint)arg1;
- (unsigned long long)micCount;
- (unsigned long long)cameraCount;
- (_Bool)toggleCamera;
- (_Bool)isFrontCamera;
- (void)setUpCamera;
- (_Bool)captureStillImage;
- (long long)cameraPermissions;
- (void)stopRecording;
- (void)startRecording;
- (_Bool)setupSession;
- (void)setFlashEnabled:(_Bool)arg1;
- (void)dealloc;
- (id)init;
- (void)copyFileToDocuments:(id)arg1;
- (void)removeFile:(id)arg1;
- (id)tempFileURL;
- (id)audioDevice;
- (id)getDefaultCamera;
- (id)backFacingCamera;
- (id)frontFacingCamera;
- (id)cameraWithPosition:(long long)arg1;
- (void)recorder:(id)arg1 recordingDidFinishToOutputFileURL:(id)arg2 error:(id)arg3;
- (void)recorderRecordingDidBegin:(id)arg1;

@end

