//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JDLNetworkCheckingBaseViewController.h"

#import "UIBarPositioningDelegate.h"
#import "UITextViewDelegate.h"

@class JDLComposeRulesViewController, JDLDraftManager, NSLayoutConstraint, NSString, SWGPost, UIActivityIndicatorView, UIBarButtonItem, UIColor, UITextView;

@interface TLMComposeViewController : JDLNetworkCheckingBaseViewController <UITextViewDelegate, UIBarPositioningDelegate>
{
    _Bool _showKeyboardOnStart;
    _Bool _viewAlreadyAppeared;
    id <TLMComposeViewControllerDelegate> _delegate;
    UIBarButtonItem *_backButton;
    UIBarButtonItem *_sendButton;
    UITextView *_textView;
    SWGPost *_ancestorPost;
    UIColor *_postColor;
    NSString *_currentPlaceholder;
    NSString *_hashtag;
    NSString *_channel;
    NSLayoutConstraint *_photoButtonTrailingConstraint;
    NSLayoutConstraint *_keyboardHeight;
    UIActivityIndicatorView *_loadingIndicator;
    JDLComposeRulesViewController *_rulesWebViewController;
    JDLDraftManager *_draftManager;
}

@property(nonatomic) _Bool viewAlreadyAppeared; // @synthesize viewAlreadyAppeared=_viewAlreadyAppeared;
@property(retain, nonatomic) JDLDraftManager *draftManager; // @synthesize draftManager=_draftManager;
@property(retain, nonatomic) JDLComposeRulesViewController *rulesWebViewController; // @synthesize rulesWebViewController=_rulesWebViewController;
@property(retain, nonatomic) UIActivityIndicatorView *loadingIndicator; // @synthesize loadingIndicator=_loadingIndicator;
@property(nonatomic) __weak NSLayoutConstraint *keyboardHeight; // @synthesize keyboardHeight=_keyboardHeight;
@property(nonatomic) __weak NSLayoutConstraint *photoButtonTrailingConstraint; // @synthesize photoButtonTrailingConstraint=_photoButtonTrailingConstraint;
@property(nonatomic) _Bool showKeyboardOnStart; // @synthesize showKeyboardOnStart=_showKeyboardOnStart;
@property(copy, nonatomic) NSString *channel; // @synthesize channel=_channel;
@property(copy, nonatomic) NSString *hashtag; // @synthesize hashtag=_hashtag;
@property(retain, nonatomic) NSString *currentPlaceholder; // @synthesize currentPlaceholder=_currentPlaceholder;
@property(retain, nonatomic) UIColor *postColor; // @synthesize postColor=_postColor;
@property(retain, nonatomic) SWGPost *ancestorPost; // @synthesize ancestorPost=_ancestorPost;
@property(nonatomic) __weak UITextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) UIBarButtonItem *sendButton; // @synthesize sendButton=_sendButton;
@property(nonatomic) __weak UIBarButtonItem *backButton; // @synthesize backButton=_backButton;
@property(nonatomic) __weak id <TLMComposeViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)dismissEULA;
- (void)showEULA;
- (void)jodelSentSuccessFully;
- (void)sendPostPressed:(id)arg1;
- (void)openCameraPressed:(id)arg1;
- (void)backPressed:(id)arg1;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)setSendButtonVisible:(_Bool)arg1;
- (void)updatePlaceholderActiveState;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)textViewDidEndEditing:(id)arg1;
- (void)hidePhotoButtonAnimated;
- (void)animateConstraintChanges;
- (void)textViewDidChange:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)changeTextViewManually:(id)arg1;
- (void)didReceiveMemoryWarning;
- (long long)positionForBar:(id)arg1;
- (void)checkEULA;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)observeKeyboard;
- (void)appWillResignActive:(id)arg1;
- (void)configureObservers;
- (_Bool)draftFeatureEnabled;
- (void)removeDraft;
- (void)retrieveDraft;
- (void)saveDraft;
- (id)threadId;
- (_Bool)disableAutomaticNetworkErrorMessageView;
- (void)hideKeyboard;
- (void)openKeyboard;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

