//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@interface UIColor (JDL)
+ (id)getImagePalette;
+ (id)jdl_randomColor;
+ (id)getColorPalette;
+ (double)colorComponentFrom:(id)arg1 start:(unsigned long long)arg2 length:(unsigned long long)arg3;
+ (id)jdl_colorWithString:(id)arg1;
+ (id)jdl_badgeIconColor;
+ (id)jdl_colorSix;
+ (id)jdl_colorFive;
+ (id)jdl_colorFour;
+ (id)jdl_colorThree;
+ (id)jdl_colorOne;
+ (id)jdl_greyishBrownColor;
+ (id)bottomTabbarBorderColor;
+ (id)separatorColor;
+ (id)settingsColor;
+ (id)meSectionColor;
+ (id)channelsColor;
+ (id)hotspotsColor;
+ (id)jdl_midGray;
+ (id)jdl_navigationBarButtonItemColor;
+ (id)stickyPostDefaultColor;
+ (id)navigationTitleColor;
+ (id)unselectedButtonGrayColor;
+ (id)globalTintColor;
+ (id)grayColorWithValue:(double)arg1;
+ (id)borderColor;
+ (id)grayBackgroundColor;
- (id)jdl_sameColoredButtonImage;
- (id)jdl_transparentColorWithAlpha:(double)arg1;
- (id)jdl_toHexString;
@end

