//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (APToast)
- (struct CGPoint)ap_centerPointForPosition:(long long)arg1 toastView:(id)arg2;
- (id)ap_toastViewForText:(id)arg1;
- (void)ap_ejectToast:(long long)arg1 animated:(_Bool)arg2;
- (void)ap_ejectToast:(long long)arg1;
- (long long)ap_makeToastView:(id)arg1 duration:(double)arg2 center:(struct CGPoint)arg3 tapToComplete:(_Bool)arg4 completion:(CDUnknownBlockType)arg5;
- (long long)ap_makeToastView:(id)arg1 duration:(double)arg2 position:(long long)arg3;
- (long long)ap_showToastView:(id)arg1 duration:(double)arg2;
- (long long)ap_makeToastView:(id)arg1;
- (long long)ap_makeToast:(id)arg1 duration:(double)arg2 center:(struct CGPoint)arg3 tapToComplete:(_Bool)arg4 completion:(CDUnknownBlockType)arg5;
- (long long)ap_makeToast:(id)arg1 duration:(double)arg2 position:(long long)arg3 completion:(CDUnknownBlockType)arg4;
- (long long)ap_makeToast:(id)arg1 duration:(double)arg2 position:(long long)arg3;
- (long long)ap_makeToast:(id)arg1 duration:(double)arg2;
- (long long)ap_makeToast:(id)arg1;
@end

