//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (_BLKFlexibleHeightNavigationBarSubview)
- (id)layoutAttributesAtIndex:(unsigned long long)arg1;
- (double)progressAtIndex:(unsigned long long)arg1;
- (unsigned long long)numberOfLayoutAttributes;
- (void)removeLayoutAttributesForProgress:(double)arg1;
- (void)addLayoutAttributes:(id)arg1 forProgress:(double)arg2;
- (void)setLayoutAttributesForProgressValues:(id)arg1;
- (id)layoutAttributesForProgressValues;
- (void)setProgressValues:(id)arg1;
- (id)progressValues;
@end

