//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (Separators)
- (void)addSeparatorWithColor:(id)arg1 frame:(struct CGRect)arg2;
- (void)addBottomSeparatorWithColor:(id)arg1;
- (void)addTopSeparatorWithColor:(id)arg1;
@end

